Azure/azure-functions-durable-extension

- src/WebJobs.Extensions.DurableTask/AssemblyInfo.cs
- src/WebJobs.Extensions.DurableTask/DurableOrchestrationClient.cs
- src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/EndToEndTraceHelper.cs
- src/WebJobs.Extensions.DurableTask/EtwEventSource.cs
- src/WebJobs.Extensions.DurableTask/FunctionState.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskActivityShim.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/BindingTests.cs
- test/DurableTaskEndToEndTests.cs
- test/LogMessage.cs
- test/TestHelpers.cs
- test/TestLogger.cs
- test/TestLoggerProvider.cs
- test/WebJobs.Extensions.DurableTask.Tests.csproj
Addressing open issue https://github.com/Azure/azure-functions-durable-extension/issues/35
1. Added support for structured logs to Application Insights.
2. Added tests.
**Sample query for structure log on Application Insights:**
```
traces
| extend isReplay = customDimensions["prop__isReplay"]
| extend hubName = customDimensions["prop__hubName"]
| extend functionName = customDimensions ["prop__functionName"]
| extend state = customDimensions ["prop__state"]
| extend instanceId = customDimensions ["prop__instanceId"]
| extend category = customDimensions ["Category"]
| where timestamp >= ago(10m)
| where category == "Microsoft.Azure.WebJobs.Extensions.DurableTask"
| where hubName == "UnhandledActivityException"
| order by timestamp asc
| project timestamp, instanceId, category, hubName, …
```
> Structured Logging to Application Insights.

- src/WebJobs.Extensions.DurableTask/EndToEndTraceHelper.cs
- src/WebJobs.Extensions.DurableTask/EtwEventSource.cs
Addressing issue https://github.com/Azure/azure-functions-durable-extension/issues/39
**Sample query for structure log on Application Insights:**
```
traces
| extend isReplay = customDimensions["prop__isReplay"]
| extend hubName = customDimensions["prop__hubName"]
| extend functionName = customDimensions ["prop__functionName"]
| extend state = customDimensions ["prop__state"]
| extend instanceId = customDimensions ["prop__instanceId"]
| extend category = customDimensions ["Category"]
| extend extensionVersion = customDimensions ["prop__extensionVersion"]
| where timestamp >= ago(10m)
| where category == "Host.Triggers.DurableTask"
| where hubName == "UnhandledActivityException"
| order by timestamp asc
| project timestamp, extensionVersion, instanceId, category, hubName, state, isReplay, …
```
> Added Extension Version to log and trace entries.

- test/TestHelpers.cs
I think a previous change I made may have possibly regressed the two timer tests, `TimerCancellation` and `TimerExpiration`. The problem was that some regex logic was returning incorrect data when parsing the log messages.
My fix was to replace the regex with a few simple string parsing rules. I tend to trust string parsing more than regex when possible anyways. :)
> Fix timer test regressions.

- src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
- test/DurableTaskEndToEndTests.cs
- test/TestOrchestrations.cs
This is related to issue https://github.com/Azure/azure-functions-durable-extension/issues/14: Allow timers to last longer than 7 days.
It's an update to the `CreateTimer` API which checks to see whether the created timer would last longer than 6 days. We want to prevent this because the storage provider layer doesn't support timers longer than 7 days. We stop at 6 days just to make sure that a delay in message processing doesn't cause a message to accidentally go over the 7 day limit and get silently deleted by Azure Storage.
Throwing an exception early is considered better than letting it fail in the storage layer because the user code will get an exception that they can easily see and react to.
> Block user code from scheduling long (7+ day) timers

- src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/RetryOptions.cs
- test/DurableTaskEndToEndTests.cs
- test/TestHelpers.cs
- test/TestOrchestrations.cs
Addressing issue https://github.com/Azure/azure-functions-durable-extension/issues/30
1. Added support for retry options using `DurableTask.Core.OrchestrationContext.ScheduleWithRetry`.
**Sample client code snippet:**
```
// Given RetryOptions scoped to Extensions.DurableTask.RetryOptions, 
RetryOptions options = new RetryOptions(TimeSpan.FromSeconds(5), 3); // FirstRetryInterval = 5 seconds, MaxNumberOfAttempts = 3
await ctx.CallFunctionWithRetryAsync(nameof(TestActivities.Throw), options, message);
```
2. Added end-to-end tests.
> Added support for retry options for activity functions.

- src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- test/DurableTaskEndToEndTests.cs
- test/TestHelpers.cs
- test/TestOrchestrations.cs
Addressed issue https://github.com/Azure/azure-functions-durable-extension/issues/54
1. Added new API named `CallOrchestratorAsync` and `CallOrchestratorWithRetryAsync` to allow customers to call orchestrator function types.
2. Added/updated tests.
> Added CallOrchestratorAsync and CallOrchestratorWithRetryAsync APIs.

- test/DurableTaskEndToEndTests.cs
Test is failing, possibly due to sluggish test environment.  Fixed test to pass by extending timeout.
> Extended timeout to allow test to pass.

- src/WebJobs.Extensions.DurableTask/DurableActivityContext.cs
- src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/MessagePayloadDataConverter.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/BindingTests.cs
- test/DurableTaskEndToEndTests.cs
- test/DurableTaskHostExtensions.cs
- test/TestActivities.cs
- test/TestOrchestrations.cs
There is currently a 64 KB size limit on queue messages and table columns in Azure Storage. However, no validation existed to fail-fast when these limits are exceeded. The result is that failures would occur silently in the DTFx storage provider when these limits were exceeded.
This PR is primarily intended to address this issue: https://github.com/Azure/azure-functions-durable-extension/issues/79
Note that this PR only addresses function return values. Function inputs are harder to validate efficiently since the serialization happens in the DTFx layer and there are no hooks to add any validation. The common case is expected to be return values, however, so I think it's worth pushing this partial fix anyways.
The long term solution is to support large return values: …
> Return Value Size validation

- src/WebJobs.Extensions.DurableTask/OrchestrationClientAttribute.cs
- src/WebJobs.Extensions.DurableTask/OrchestrationTriggerAttribute.cs
This seems like it'll fix #120
> Support cross-language return values for orchestration triggers

- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
The default number of partitions for the control queue is 4. Customers will now be able to configure the partition count in the **host.json** file.
This is done to address https://github.com/Azure/azure-functions-durable-extension/issues/73
1. Open the `VSSample.sln` provided in [docs](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-install).
2. Add the `PartitionCount` property to the default the `host.json `file, e.g. set **PartitionCount** to 8
```
{
"http": {
"routePrefix": ""
},
"applicationInsights": {
"sampling": {
"isEnabled": false
}
},
"durableTask": {
"HubName": "SampleHubVS",
"PartitionCount" : 8  
}
}
```
3. Launch the function host and run the `E1_HelloSequence` function.
4. Verify that the storage queue has a **8** partitions instead of the default …
> Adding support for setting partition count in host.json

- src/WebJobs.Extensions.DurableTask/Bindings/ActivityTriggerAttributeBindingProvider.cs
- src/WebJobs.Extensions.DurableTask/DurableActivityContext.cs
- test/BindingTests.cs
- test/TestActivities.cs
This PR fixes #123 (enable binding expressions in activity functions. it allows the function author to bind to the name of the parameter or to one of the top-level fields in the activity payload.
This activity function takes a string argument (the name of a blob) and uses that value to bind to blob input and output bindings.
**Activity Function**
```csharp
public static async Task ArchiveBlob(
[ActivityTrigger] string name,
[Blob("test/{name}", FileAccess.Read)] Stream input,
[Blob("test/{name}-archive", FileAccess.Write)] Stream output)
{
await input.CopyToAsync(output);
}
```
**Orchestrator Function**
```csharp
public static async Task Orchestrator([OrchestrationTrigger] DurableOrchestrationContext ctx)
{
string blobName = ctx.GetInput<string>();
await …
```
> Support for binding expressions in activity functions

- src/WebJobs.Extensions.DurableTask/MessagePayloadDataConverter.cs
- test/DurableTaskEndToEndTests.cs
This fix addresses the issue https://github.com/Azure/azure-functions-durable-extension/issues/189
> Fix message size limit check to use UTF-16 to align with Azure Storage.

- samples/precompiled/HttpSyncStart.cs
All the other .cs files had the copyright & license at the top of the file. Please reject if the omission was intentional.
> add comment with copyright & license information

- src/WebJobs.Extensions.DurableTask/DurableOrchestrationClient.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
This is a temporary fix that addresses https://github.com/Azure/azure-functions-durable-extension/issues/177, which was a problem that was introduced in beta3. A more permanent fix will be added later.
To disable the polling in StartNewAsync, simply update the host.json file as follows:
```json
{
"durableTask": {
"disableStartInstancePolling": true
}
}
```
> Enable opting-out of the StartNewAsync polling

- src/WebJobs.Extensions.DurableTask/Bindings/ActivityTriggerAttributeBindingProvider.cs
- src/WebJobs.Extensions.DurableTask/DurableActivityContext.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/EndToEndTraceHelper.cs
- src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/WebJobs.Extensions.DurableTask.Tests.csproj
Fixes https://github.com/Azure/azure-functions-durable-extension/issues/210. This is fairly urgent since durable functions on v2 is broken in production due to the recent beta5 breaking change roll-out.
Two main changes in this PR:
1. Replace all usage of `TraceWriter` with `ILogger`.
2. Remove all usage of converters in binding trigger providers.
It turns out that these changes actually make the code cleaner by simply removing unnecessary code.
> Functions V2 Compatibility Update

- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
Previous package accidentally included StyleCop analyzers, which meant that users using the package in Visual Studio would get StyleCop warnings for their own code.
> Updating package version to v1.2.2-beta3

- src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/DurableOrchestrationContextBase.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskActivityShim.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
- src/WebJobs.Extensions.DurableTask/MessagePayloadDataConverter.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/DurableTaskEndToEndTests.cs
- test/DurableTaskLifeCycleNotificationTest.cs
- test/TestActivities.cs
- test/TestHelpers.cs
- test/TestOrchestrations.cs
- test/WebJobs.Extensions.DurableTask.Tests.csproj
Fixes https://github.com/Azure/azure-functions-durable-extension/issues/84. The new behavior is that activity and sub-orchestrator functions will continue to throw `FunctionFailedException`, but the `InnerException` will now contain the details of the original exception.
This required taking a new version of **DurableTask.Core**, which has fixes for https://github.com/Azure/azure-functions-durable-extension/issues/146 as well.
> Flow exception details between orchestrator and activity functions

- src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/DurableOrchestrationContextBase.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/DurableTaskEndToEndTests.cs
- test/TestOrchestrations.cs
May I ask you when you have time to check this implementation for exposing parent orchestrator instance id in the sub-orchestrator as specified here - [#246](https://github.com/Azure/azure-functions-durable-extension/issues/246).
Thank you!
> Expose parent orchestration instance id in a sub-orchestrator

- src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
- test/HttpApiHandlerTests.cs
I started to think how we can implement this issue - [154](https://github.com/Azure/azure-functions-durable-extension/issues/154).
May I ask you when you have time to review the proposed changes and let me know if the current approach is correct?
Thank you!
> Returing 500 Http Status code on Orchestrator failure

- src/WebJobs.Extensions.DurableTask/LifeCycleNotificationHelper.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/DurableTaskLifeCycleNotificationTest.cs
This pull request is for the https://github.com/Azure/azure-functions-durable-extension/issues/285 . 
I change EventGridPayload eventType -> runtimeStatus. 
Here is an example of the current paylod:
```
[
{
"id": "aeafd489-ee98-4b2e-b77f-2aac2594b4b2",
"topic": null,
"subject": "durable/orchestrator/Running",
"data": {
"hubName": "DFHub",
"functionName": "Counter",
"instanceId": "13b602a9d2914d7c981016acbee0b941",
"reason": "",
"eventType": 0
},
"eventType": "orchestratorEvent",
"eventTime": "2018-04-29T04:41:43.5299974Z",
"metadataVersion": null,
"dataVersion": "1.0"
}
]
```
This pull request change it like this. 
```
[
{
"id": "aeafd489-ee98-4b2e-b77f-2aac2594b4b2",
"topic": null,
"subject": "durable/orchestrator/Running",
"data": {
"hubName": "DFHub",
"functionName": "Counter", …
```
> Change custom Event Grid eventType property from an int to a string

- src/WebJobs.Extensions.DurableTask/Bindings/OrchestrationTriggerAttributeBindingProvider.cs
The C# **E1_HelloSequence** sample silently hangs when run with the latest code from **dev**. Further investigation revealed that this is due to the `isOutOfProc` check.
The problem is that **E1_HelloSequence** uses `DurableOrchestrationContextBase` instead of `DurableOrchestrationContext`. The `isOutOfProc` logic only checked for `DurableOrchestrationContext` as the orchestration argument type, so it incorrectly thought the C# **E1_HelloSequence** orchestrator function was out-of-proc.  This resulted in a hang because the shim was blocking on `Task.Result`, which never completes by-design for in-proc orchestrations.
The fix is to make `isOutOfProc` aware of `DurableOrchestrationContextBase`.
> Fix isOutOfProc detection logic to work with DurableOrchestrationContextBase

- src/WebJobs.Extensions.DurableTask/DurableOrchestrationClient.cs
- src/WebJobs.Extensions.DurableTask/DurableOrchestrationClientBase.cs
- src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/StatusResponsePayload.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/HttpApiHandlerTests.cs
- test/WebJobs.Extensions.DurableTask.Tests.csproj
Hi @cgillum 
I start this pull request to start conversation. 
This pull request is for this issue. 
https://github.com/Azure/azure-functions-durable-extension/issues/316
Also, related this pull request for DurableTask
https://github.com/Azure/durabletask/pull/187
If you do CI for this pull request, currently it must fail.   This fix need the code change of the durable task pull request. I write a code with the nuget packages of DurableTask.AzureStorage (2.0.0.5) I don't include  csproj file since it is changed to load local file.
I have some questions for you. 
* Should I change the version of the DurableTaskStorage? or leave it to you?
* For writing test, we need to add method to the DurableOrchestrationClientMock.cs. However, it is just mplement DurableOrchestrationClientBase. As we …
> APIs to enumerate all orchestration instances

- src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/DurableOrchestrationContextBase.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/DurableTaskEndToEndTests.cs
- test/TestOrchestrations.cs
This is a first attempt at implementing overloads of `WaitForExternalEvent` with timeout support as discussed in issue #365. There are two overloads - one that throws a `TimeoutException`, the other returns a user-specified default value.
I'd like to get some end to end tests going for this. At the moment, I'm still getting my machine configured to run the tests (ActorOrchestration is currently failing for me).
> WaitForExternalEvent with timeout support

- src/WebJobs.Extensions.DurableTask/DurableOrchestrationClient.cs
- src/WebJobs.Extensions.DurableTask/DurableOrchestrationClientBase.cs
- test/DurableTaskEndToEndTests.cs
- test/TestOrchestratorClient.cs
Hi.
I created this PullRequest because I wanted to specify TaskHubName as a parameter of RiaseEventAsync function of DurableTaskClient.
There are two kinds of means to activate Orchestrator waiting in WaitForExternal: a method of making a Post request to Api and a method of using DurableOrchestrationClient.RaiseEventAsync function.
The way to make a Post request to Api is to specify InstanceId, event name and TaskHubName, but with the method using DurableOrchestrationClient.RaiseEventAsync function you can only specify event name and InstanceId.
> Add TaskHubName parameter to RaiseEventAsync method

- src/WebJobs.Extensions.DurableTask/Bindings/BindingHelper.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
This commit adds a converter for OrchestrationClient when used as output. This is necessary to enable an [improved orchestration client experience](https://github.com/Azure/azure-functions-durable-js/issues/12) in Durable JS and other (upcoming) out-of-proc languages, given current limitations on out-of-proc bindings in Azure Functions.
Partially enables #296.
> Added OrchestrationClient binding output converter.

- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
Resolves https://github.com/Azure/azure-functions-durable-extension/issues/449.
**DurableTask.AzureStorage** has a queue polling optimization where if a client sends a message to a queue, then the polling loop will pick it up immediately instead of waiting for the next polling interval. This optimization only works if both the client and host are using the same `AzureStorageOrchestrationService` instance in memory. This was not the case previously, defeating the purpose of this optimization.
This PR also includes a change to target our full framework tests to **.NET Framework 4.6.1** instead of 4.7. This is to make it easier for developers to run these tests (.NET 4.6.1 is installed by default by Visual Studio 2017, but .NET 4.7 is not).
> Reuse AzureStorageOrchestrationService instances across client and host

- src/WebJobs.Extensions.DurableTask/Bindings/BindingHelper.cs
- src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
- src/WebJobs.Extensions.DurableTask/HttpCreationPayload.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
Added orchestration start webhook templates to out-of-proc OrchestrationClient binding data, modified said data structure to resemble the following:
```json
{
"taskHubName": "SampleHubJS",
"creationPayload": {
"createNewInstancePostUri": "http://localhost:7071/runtime/webhooks/durabletask/orchestrators/{functionName}[/{instanceId}]?code=code",
"waitOnNewInstancePostUri": "http://localhost:7071/runtime/webhooks/durabletask/orchestrators/{functionName}[/{instanceId}]?timeoutInterval={timeoutInSeconds}&pollingInterval={intervalInSeconds}&code=code"
},
"managementPayload": {
"id": "some-guid",
"statusQueryGetUri": "http://localhost:7071/runtime/webhooks/durabletask/instances/some-guid?taskHub=SampleHubJS&connection=Storage&code=code",
"sendEventPostUri": …
```
> Modified out-of-proc OrchestrationClient binding data.

- src/WebJobs.Extensions.DurableTask/DurableOrchestrationClient.cs
- src/WebJobs.Extensions.DurableTask/DurableOrchestrationClientBase.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/HttpApiHandlerTests.cs
- test/Common/TestOrchestrations.cs
This is PR for integrating the changes made in Durable Task project for the History Retention feature - https://github.com/Azure/azure-functions-durable-extension/issues/17.
When you have time, please take a look.
Thank you!
> Adding new Purging History API-s

- src/WebJobs.Extensions.DurableTask/HttpRequestMessageExtensions.cs
Resolve #470 
This updates the query string parsing code to _never_ return nulls for the query string key.
> Remove possibility of nulls in query string args

- src/WebJobs.Extensions.DurableTask/DurableOrchestrationClient.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/OrchestrationClientAttribute.cs
- test/Common/ClientFunctions.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/DurableTaskHostExtensions.cs
- test/Common/DurableTaskLifeCycleNotificationTest.cs
- test/Common/HttpApiHandlerTests.cs
- test/Common/TestHelpers.cs
I wanted to open this PR and start the discussion for resolving https://github.com/Azure/azure-functions-durable-extension/issues/499.
Thank you for the guidance for the `AutoResolve` attribute. It works as expected and it is able to resolve the value of the app setting variable. However, when using it the orchestration gets stacked in the pending state. We don't get any entries to the History table and the initial control queue message stays unprocessed. I think the runtime for some reason is trying to pull from the original task hub (configured in `host.json`) control queues. My guess is it is because the `TaskHubWorker` is initialized with the original `TaskHubName` set in `host.json` in `DurableTaskExtension.Initialize` :
```csharp
this.orchestrationServiceSettings = …
```
> Adding support for configuring Task Hub Name via OrchestrationClientAttribute

- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
May I ask you to take a look on this first commit for adding support for source-link as described in https://github.com/Azure/azure-functions-durable-extension/issues/526?
Thank you!
> Adding support for source-link

- test/Common/DurableTaskEndToEndTests.cs
- test/Common/LogEventTraceListener.cs
- test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
- test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj
It's currently very difficult to debug test failures due to underlying DTFx issues. This PR updates the end-to-end tests to capture the DTFx ETW events and include them in the test output.
> Add DTFx ETW traces to test output

- src/WebJobs.Extensions.DurableTask/DurableOrchestrationClient.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestHelpers.cs
- test/Common/TestOrchestratorClient.cs
- test/FunctionsV1/PlatformSpecificHelpers.FunctionsV1.cs
- test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
- test/FunctionsV2/PlatformSpecificHelpers.FunctionsV2.cs
- test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj
* Updated to DurableTask.AzureStorage v1.4.2 which has a fix for the abandon scenario
* Added flakey test category
* Added improved test tracing
* Fixed race condition w/RaiseEventAsync + ContinueAsNew which was causing several tests to be flakey.
> Fix race condition with RaiseEventAsync and ContinueAsNew

- src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/EndToEndTraceHelper.cs
- src/WebJobs.Extensions.DurableTask/EtwEventSource.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestActivities.cs
- test/Common/TestOrchestrations.cs
**Problem:** If no orchestrator is listening for a specific event at a given time, then that event will be discarded. This causes dropped messages, even when there is an orchestrator listening for that event at around the same time (due to the race conditions seen in #573). This PR should address the main issue brought up in #378.
**Solution:** Messages that would have been dropped before are now added to an (in-memory) queue. When `WaitForExternalEvent(name)` is called, it checks its queues for an event associated with `name.` If found, `RaiseEvent` is called on it immediately.
**Notes**: This is my first stab at solving this problem - I'm not sure if it fully solves issue 573, but it does make the 10 activities/events execute in the proper order in 378. 
I also need to think about how …
> Save dropped events

- src/WebJobs.Extensions.DurableTask/EndToEndTraceHelper.cs
Fix issue where FunctionFailed ETW events have the incorrect value for the IsReplay column.
The app insights logging does the right thing, it's just the ETW logs (used internally by Microsoft) which are incorrect.
> ETW spam: FunctionFailed ETW events hardcode IsReplay to false

- src/WebJobs.Extensions.DurableTask/EndToEndTraceHelper.cs
@glennamanns noticed an issue in [my previous PR](https://github.com/Azure/azure-functions-durable-extension/pull/585) where it turns out we are also spamming Application Insights (and probably the console in the case of local development) with replayed exception messages. This PR addresses that issue, so that by default we only log function exceptions when they actually happen, and not during replay.
Possibly related issue: https://github.com/Azure/azure-functions-durable-extension/issues/586
> Fixed issue where function failures were always being logged on replays

- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskOptions.cs
- src/WebJobs.Extensions.DurableTask/EventGridLifeCycleNotificationHelper.cs
- src/WebJobs.Extensions.DurableTask/FunctionType.cs
- src/WebJobs.Extensions.DurableTask/ILifeCycleNotificationHelper.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/NullLifeCycleNotificationHelper.cs
- test/Common/DurableTaskLifeCycleNotificationTest.cs
Change LifeCycle notification helper to extensible. #602 
- Introduced `ILifeCycleNotificationHelper` and `NullLifeCycleNotificationHelper`
- Renamed `LifeCycleNotificationHelper` to `EventGridLifeCycleNotificationHelper`
- Added `CustomLifeCycleNotificationHelperType` option
- Added test cases
> Adding custom LifeCycle notification helper

- src/WebJobs.Extensions.DurableTask/MessagePayloadDataConverter.cs
- test/Common/DurableTaskEndToEndTests.cs
Keep actual `Exception` type in serialization. #361
- Check if the exception was defined in C# script
- Use type namespace (ex. `Submission#0.TestException`) or assembly location (`Assembly.Location` is empty from C# script)
- Switch `TypeNameHandling.None` for exceptions defined in C# script
> Adding TypeNameHandling to Exception serializer settings

- src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
Bugfix: TaskOrchestrationShim.Execute calls for out-of-procedure orchestrators will not complete unless the orchestration is complete. This fixes the case of waiting on multiple waitForExternalEvent calls to complete. Currently the orchestrator is marked Completed after the first event is received.
The Durable Task Framework currently does something similar, by abandoning an orchestration's Task if the orchestration is not completed.
> Out-of-proc handling: don't complete Execute until orchestration completes.

- src/WebJobs.Extensions.DurableTask/FunctionFailedException.cs
`SerializableAttribute` is required when serialize using Json.NET.
Therefore, `InnerException` is empty in the case of serializing `FunctionFailedException` (mainly using sub orchestrator).
Already serialized exceptions can not deserialize correctly before adding [Serializable].
> Mark Serializable to FunctionFailedException

- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskOptions.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/Common/TestHelpers.cs
- test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
- test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj
Makes the maximum queue polling interval configurable via host.json.
Second step to resolving [Azure/azure-functions-durable-extension#618](https://github.com/Azure/azure-functions-durable-extension/issues/618).
> Allow to configure max polling interval via host.json

- src/WebJobs.Extensions.DurableTask/Bindings/OrchestrationTriggerAttributeBindingProvider.cs
- src/WebJobs.Extensions.DurableTask/Bindings/RegisteredFunctionInfo.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
Fixes https://github.com/Azure/azure-functions-durable-extension/issues/577
This PR addresses a race condition that happens during Functions host shutdown. Instead of removing deregistered functions from internal dictionary, we keep them in that dictionary and just set a `IsDeregistered` bit to `true`. This avoids the exception which can happen if an orchestrator function tries to schedule an activity function at the same time as a host shutdown.
> Remove validation for deregistered functions

- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskOptions.cs
This PR adds two new properties to the `DurableTaskOptions` class. It allows multiple function apps to share a common History and Instances table, while having separate queues for polling.
The two main scenarios for this PR are:
* Zero downtime deployments (side-by-side versioning)
* Improved scalability - multiple function apps can all use separate storage accounts for queues and a common storage account for tables.
It is the followup change to https://github.com/Azure/durabletask/pull/252
> Added TrackingStoreConnectionStringName and TrackingStoreNamePrefix settings

- src/WebJobs.Extensions.DurableTask/DurableTaskOptions.cs
- src/WebJobs.Extensions.DurableTask/EventGridLifeCycleNotificationHelper.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/DurableTaskLifeCycleNotificationTest.cs
- test/Common/TestHelpers.cs
I care about 'Failed' life cycle events in order to generate operational alerts in my system. I don't need to receive events for other the other life cycle events.
Yes, using Event Grid I can subscribe to only the 'Failed' events, but I am still charged to publish all the events to the Topic.
This isn't a problem when the volume of Orchestration instances is low, but in a high volume scenario (millions of new instances starting and completing every day) this can be a source of considerable, and unnecessary financial cost, not to mention the overhead of unnecessary HTTP traffic.
This pull request gives the integrator the power to decide what, if any, events should be published at source.
This change has been implemented in an 'opt-out' manner so that existing integrations will continue …
> Opt-out of specific lifecycle events that are published to Event Grid

- test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj
This fixes a few things:
1. We can now run `dotnet build` and `dotnet test` in `test/FunctionsV2` directory and directly against `test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj` without errors.
2. Enables running and debugging tests via [OmniSharp for VS Code](https://github.com/OmniSharp/omnisharp-vscode/wiki/How-to-run-and-debug-unit-tests).
3. Enables [.NET test explorer in VS Code](https://marketplace.visualstudio.com/items?itemName=formulahendry.dotnet-test-explorer). This likely is just a side affect of fixing Omnisharp, but it seems to be a popular tool for .NET develoment with VS Code.
> Eliminate usage of $(SolutionDir) in test .csproj file

- src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
- src/WebJobs.Extensions.DurableTask/StatusResponsePayload.cs
- test/Common/HttpApiHandlerTests.cs
Simple modification to add the `name` property to the payload returned by the HTTP API's instance queries. Addresses the initial concern of #567 and aligns the behavior of the JavaScript OrchestrationClient.getStatus methods in line with that of their C# counterparts.
> Added name property to HTTP API instance queries.

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationClient.cs
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationClient.cs
- src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/OrchestrationStatusQueryCondition.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/HttpApiHandlerTests.cs
- test/Common/TestOrchestratorClient.cs
- test/FunctionsV2/OrchestrationStatusQueryConditionTest.cs
Hi @cgillum ,
I enable the GetStatus query with condition object. This PR is created toward V2 implementation.  I see the V2 introduce the structure change. So I thought that it might be better to contribute towards V2 branch. 
This is related issue.
https://github.com/Azure/azure-functions-durable-extension/issues/668
* Adding GetStatus with Condition query
* Refactor the duplication between GetStatus methods
* Introduce OrchestrationStatusQueryCondition which is the durable extension representation of the OrchestrationInstanceStatusQueryCondition that is DurableTask object. 
* Create Unit Test for the QueryCondition 
* Create E2E Test for testing GetStatus
* Add TaskHubNames Query for HttpApi side
Currently, E2E test takes two minutes. If you have a suggestion to shorten the E2E test …
> Adding query feature for the conditional query

- src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/DurableOrchestrationContextBase.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/OrchestrationRuntimeStatus.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/LogEventTraceListener.cs
- test/Common/TestActivities.cs
- test/Common/TestOrchestrations.cs
Fixes https://github.com/Azure/azure-functions-durable-extension/issues/676 (Events added to in-memory queue are not being raised after ContinueAsNew called)
Included in this PR are also some test fixes which may help resolve https://github.com/Azure/azure-functions-durable-extension/issues/646 (integration test flakiness)
> Ability to carry over buffered external events on ContinueAsNew

- src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/Common/DurableTaskEndToEndTests.cs
- test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
- test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj
* Fixes part of https://github.com/Azure/azure-functions-durable-extension/issues/695 (Purge API should not return 404 if the instance exists)
* Fixes https://github.com/Azure/durabletask/issues/271 (incorrect handling of messages for instances which don't exist)
> Additional fixes for v1.8.1

- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- test/Common/BindingTests.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/DurableTaskLifeCycleNotificationTest.cs
- test/Common/TestOrchestratorClient.cs
This is expected to help with https://github.com/Azure/azure-functions-durable-extension/issues/646 because many failed tests seem to just need more time. The reason they need more time is not always understood but a lot of it seems to do with partition management operations.
> Refactored test timeout settings to improve consistency

- src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs
- src/WebJobs.Extensions.DurableTask/Options/StorageProviderOptions.cs
- src/WebJobs.Extensions.DurableTask/OrchestrationServiceFactory.cs
- test/Common/TestHelpers.cs
- test/FunctionsV2/DurableOptionsConfigurationTests.cs
- test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj
This PR addresses stops throwing exceptions when the host.json either has `storageProvider` as `null` or `{}`.
The new behavior is to default to `Storage`, which is the same behavior as v1 if no connection string was provided.
> Restore v1 Azure Storage default behavior to v2

- src/WebJobs.Extensions.DurableTask/ActorScheduler/ReleaseMessage.cs
- src/WebJobs.Extensions.DurableTask/ActorScheduler/RequestMessage.cs
- src/WebJobs.Extensions.DurableTask/ActorScheduler/ResponseMessage.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableActorContext.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableCommonContext.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableActorContext.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/EndToEndTraceHelper.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskActorShim.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/TestActors.cs
Several fixes and improvements to the new actor scheduler.
- add locks to fix race condition between finishing/queueing operations
- keep list of outgoing messages instead of list of orchestrator actions
- change continue-as-new logic so it always processes exactly the batch of messages being delivered
- remove operation limit
- fix the counting of messages, and the waiting for pending operations
Also, some other changes:
- remove `IDeterministicExecutionContext` from `IDurableActorContext` (since it is not deterministic anymore)
- add more precise tracing for actor messages
> Actor scheduler overhaul

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableCommonContext.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationClient.cs
- src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
- test/Common/HttpApiHandlerTests.cs
A basic implementation of the feature request #733.
Entities have a path of the form 
- GET operations return the state of the entity, as JSON content, or 404 (NotFound) if the entity does not exist.
- POST operations send a signal to the entity and return 202 (Accepted). 
- The operation name is given by the query argument `?op=opname`. It is optional and defaults to the empty string.
- The operation content is retrieved from the content. If the content type is 'application/json', we parse it to make sure it is valid JSON before sending the signal. Otherwise, we consider it to be plain string.
> Simple REST API for durable entities

- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
Legacy assembly load manipulation used to be required with Function
extensions. Now they interfere with the functions runtime, causing stack
overflow exceptions.
> Remove manual assembly load manipulation

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
Makes it very easy to specify an initial state for the entity when accessing it via `GetState<T>`.
For example, 
```csharp
var state = context.GetState(() => new List<int>())
```
> add optional initializer argument to GetState

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableCommonContext.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestEntities.cs
Fixes a bug where tracing functions throw an exception because `InnerContext` is null with the new scheduler.
This bug was missed by our tests (I found it while testing samples), so I modified one of the tests to catch future regressions.
> fix NullReferenceException thrown during IDurableEntityContext.SignalEntity

- src/WebJobs.Extensions.DurableTask/FunctionFailedException.cs
> Expose FunctionFailedException constructors for easier unit testing

- src/WebJobs.Extensions.DurableTask/EntityScheduler/Entity.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/TypedInvocationExtensions.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestEntities.cs
- test/Common/TestEntityClasses.cs
- test/Common/TestHelpers.cs
- test/Common/TestOrchestrations.cs
This PR adds a new feature that allows actors to be called or signaled using C# interfaces and reflection. 
On the actor side, incoming operations can be dispatched to the object type representing the actor using reflection, e.g.
```csharp
ctx.Dispatch<Room>()
```
On the caller side, an operation is chosen by providing a delegate that performs the invocation on an interface, e.g.
```csharp
ctx.SignalActor<IRoom>(actorId, r => r.MethodToBeCalled(typedArg1, typedArg2))
```
or
```csharp
var result = await ctx.CallActorAsync<IRoom,int>(actorId, r => r.MethodReturningInteger())
```
> Signal or call actors using interfaces and reflection (step 1)

- samples/v2/entitites-csharp/RideSharing/RideSharing/Entities/UserEntity.cs
- src/WebJobs.Extensions.DurableTask/Bindings/EntityTriggerAttributeBindingProvider.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/TestEntities.cs
Use consistent naming of fields that give access to entity properties.
Before: (`EntityName`, `Key`, `Self`).
Proposed: (`EntityName`, `EntityKey`, `EntityId`).
> minor renaming in IDurableEntityContext

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableActivityContext.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationClient.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/LegacyCompatibility.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestActivities.cs
- test/Common/TestOrchestrations.cs
This is a little change meant to ease the transition to v2.
Rather than breaking v1 orchestration triggers based on `DurableOrchestrationContextBase` and `DurableActivityContextBase`, this change keeps them defined and functional, but marked as obsolete. So users get warnings that tell them what to do, that they can fix at their leisure.
I think this is better than reverting back to the old scheme because I think public interfaces are usually preferable to public base classes as they keep the options open for how things are implemented internally.
> Add legacy compatibility for abstract base classes

- src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
- test/Common/DurableTaskEndToEndTests.cs
> Prevent sub-orchestrations from using the instance ID of the parent

- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/Options/EventGridNotificationOptions.cs
- src/WebJobs.Extensions.DurableTask/Options/NotificationOptions.cs
- src/WebJobs.Extensions.DurableTask/Options/TraceOptions.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/Common/TestEntityClasses.cs
- test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj
I fixed some warnings in the build, and added some settings to make it so Release builds fail on any warnings from Roslyn or StyleCop. This means CIs should catch any warnings before they get introduced into our codebase, without blocking developers from rapidly prototyping and being bogged down by documentation and other style-based warnings.
The only downside to this approach I see is the annoyance of having a build pass locally but fail in the CI. Maybe I could add something to the contribution guidelines recommending a local "Release" build before opening a PR?
> Fix warnings and make warnings fail on Release builds

- samples/javascript/extensions.csproj
- samples/javascript/package-lock.json
- samples/javascript/package.json
* Microsoft.Azure.WebJobs.Extensions.DurableTask: 1.8.0 -> 1.8.2
* durable-functions: 1.1.2 -> 1.2.2
This update puts the samples on the latest versions of the extension and JS library, taking advantage of several bugfixes and resolving a security vulnerability in the axios library.
> Updated JavaScript samples' dependencies:

- src/WebJobs.Extensions.DurableTask/Bindings/EntityTriggerAttributeBindingProvider.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableCommonContext.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/EndToEndTraceHelper.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/RequestMessage.cs
- src/WebJobs.Extensions.DurableTask/EtwEventSource.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskActivityShim.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskCommonShim.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/DurableTaskEndToEndTests.cs
For out-of-proc, we need to batch multiple operations into a single call (since we cannot change any of the parameters after the binding has taken place, and can therefore not call the function multiple times). 
To support this 
- I rewrote the scheduler a bit. It now collects all the operations to execute, before executing any of them. This is actually cleaner than what we had before, it gets rid of the concurrency control (no more locking needed).
- I modified the JSON fields on the context object passed to the out-of-proc function:
- 'batch' is an array of objects describing the operations to execute
- 'exists' is a boolean indicating whether the entity exists 
- 'state' is the state of the entity as a string (if `exists`)
- I modified the JSON fields on the result object returned from …
> Batch-processing of entity operations for out-of-proc support

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableCommonContext.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/MessageSorter.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/RequestMessage.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/SchedulerState.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs
- test/Common/MessageSorterTests.cs
This PR fixes the issue described in #762.
Our current implementation does not guarantee exactly-once and in-order delivery. Depending on various timing aspects messages can be delivered out of order. They can also be duplicated in some circumstances involving failures or lease timeouts.
The reordering of messages currently causes several of our tests to fail occasionally (DurableEntity_EntityProxy, DurableEntity_BasicObjects, DurableEntity_EntityProxy_NameResolution) because they expect signals and operations targeting an entity from an orchestration to be delivered in the same order as they appear in the orchestration. 
Also, several of our examples include operations (e.g. increment) that by design implicitly assume that each message is delivered exactly once.
This PR adds a mechanism …
> Provide sorting and deduplication for entity messages

- src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
We identified that we need small change in the `TaskOrchestrationShim` so we can parse the string (JSON) passed by the Python worker as specified [here](https://github.com/Azure/azure-functions-durable-extension/wiki/Out-of-Proc-Orchestrator-Execution-Schema-Reference#sample-orchestrator-execution-result).
Let us know what you think when you have time.
If you think it is a good fit for Durable for the project we will add unit and integration test to solidify it.
Thank you!
> Adding small change to accommodate the way Python worker passes JSON

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/DurableHttpClientFactory.cs
- src/WebJobs.Extensions.DurableTask/DurableHttpMessageHandlerFactory.cs
- src/WebJobs.Extensions.DurableTask/DurableHttpRequest.cs
- src/WebJobs.Extensions.DurableTask/DurableHttpRequestJsonConverter.cs
- src/WebJobs.Extensions.DurableTask/DurableHttpResponse.cs
- src/WebJobs.Extensions.DurableTask/DurableHttpResponseJsonConverter.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskJobHostConfigurationExtensions.cs
- src/WebJobs.Extensions.DurableTask/IDurableHttpMessageHandlerFactory.cs
- src/WebJobs.Extensions.DurableTask/ITokenSource.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskHttpActivityShim.cs
- src/WebJobs.Extensions.DurableTask/ManagedIdentityTokenSource.cs
- src/WebJobs.Extensions.DurableTask/MessagePayloadDataConverter.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs
- src/WebJobs.Extensions.DurableTask/Options/HttpOptions.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/Common/DurableOrchestrationClientBaseTests.cs
- test/Common/HttpApiHandlerTests.cs
- test/Common/TestDurableHttpRequest.cs
- test/Common/TestHelpers.cs
- test/Common/TestOrchestrations.cs
- test/FunctionsV1/PlatformSpecificHelpers.FunctionsV1.cs
- test/FunctionsV2/DurableHttpTests.cs
- test/FunctionsV2/PlatformSpecificHelpers.FunctionsV2.cs
Includes CallHttpAsync API to DurableOrchestrationContext. Also, adds
support for Bearer tokens to the CallHttpAsync API. This API supports an
asynchronous 202 HTTP pattern.
Resolves https://github.com/Azure/azure-functions-durable-extension/issues/469
> Adding first class support for HTTP calls in Orchestration functions.

- src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/DurableOrchestrationContextBase.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestOrchestrations.cs
Previously, `WaitForExternalEvent` when invoked with a specified timeout value would create a Timer instance that was uncancelable by the surrounding orchestration.  This could have the practical effect of making orchestrations hang until either the event was received (causing the timer to be cancelled) or the timeout was reached (because the timer expired).
This change adds overloads for `TimeSpan`-accepting overloads of `WaitForExternalEvent` that allow providing a `CancellationToken`, which the calling orchestration can cancel if it no longer intends to wait for the event to be raised.
Fixes #816
> Add WaitForExternalEvent with CancellationToken overloads

- samples/precompiled/host.json
`logging/applicationinsights/sampling` has changed to `logging/applicationinsights/samplingsettings` per the host.json schema.
> fixing 'sampling' host setting to match latest schema

- samples/v2/VSSample.Tests/VSSample.Tests.csproj
- samples/v2/precompiled/RestartVMs.cs
- samples/v2/precompiled/VSSample.csproj
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
Adding RestartVMs.cs as a sample of how to use Durable HTTP.
Note: Wait until beta 2 is released to merge these changes.
> Adding Durable HTTP Sample

- samples/v2/precompiled/HttpStart.cs
- samples/v2/precompiled/HttpSyncStart.cs
- samples/v2/precompiled/RestartVMs.cs
This PR makes the Durable HTTP sample a bit more robust. It also fixes the breaking changes we introduced in the precompiled sample.
I was able to get this running using the following [httpie](https://httpie.org/) commands.
```
http POST http://localhost:7071/RestartVMs_HttpStart subscriptionId=abc resourceGroup=rg
```
> Make Durable HTTP sample more robust

- src/WebJobs.Extensions.DurableTask/DurableTaskJobHostConfigurationExtensions.cs
Added default factory only when `IDurableHttpMessageHandlerFactory` is not added.
Azure Functions runtime executes the initialization code in the following order.
1. `FunctionsStartup` code
2. Extensions `Startup` code
Dependency Injection uses the last added service, so customized classes are not used.
Ref #923
> Fixed default durable http factory registration

- src/WebJobs.Extensions.DurableTask/EntityScheduler/TypedInvocationExtensions.cs
- test/FunctionsV2/EntityMethodDiscoveryTests.cs
I extracted the logic for the looking for the method that does the lookup of the member on an entity so that it was easier to test in isolation.
Created some tests for the main scenarios of method discovery (that I could think of).
#928
> Implementing a fix for #928

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestEntities.cs
- test/Common/TestOrchestrations.cs
- test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
- test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj
As discussed in #715, this PR provides the capability to start new orchestrations from within orchestrations and entities, without waiting for them to complete (fire-and-forget). 
It is based on the corresponding feature recently added to DTFx azure/durabletask#312, and thus depends on using a very recent version of DTFx.
(Do not merge until this DTFx dependency is resolved).
> support StartNewOrchestration from within orchestrations and entities

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/EndToEndTraceHelper.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/EntitySchedulerException.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/OperationErrorException.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/RequestMessage.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/ResponseMessage.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs
- src/WebJobs.Extensions.DurableTask/MessagePayloadDataConverter.cs
This PR fixes multiple issues to improve the overall experience with how exceptions are caught, transmitted, and surfaced in entities and the calling orchestrations.
- Inside client, when signaling or reading an entity, throw an exception if there is no entity function with that name.
- Fix serialization settings for exceptions, so reference loops are ignored (this is needed so it does not trip over some AzureStorageExceptions).
- If an operation throws an unserializable exception, wrap the info into a serializable exception, so it can still be sent back to the calling orchestration and observed there
- Catch serialization exceptions, and wrap them into a EntitySchedulerException that states the precise situation in which this happened (serialization/deserialization of input/state)
- …
> Overhaul exception handling for entities

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/MessageSorter.cs
Fix a bug that was exposed by the recent changes in #946: forwarded lock messages must not participate in message sorting. I discovered this bug because it caused a deadlock in the RideSharing sample.
> fix bug in sorting of lock messages

- test/Common/DurableTaskEndToEndTests.cs
- test/Common/MessageSorterTests.cs
- test/Common/TestEntityClasses.cs
Fixing two tests that were written incorrectly - the tests assumed `DateTime.UtcNow` always increases and therefore failed in situations where two successive invocations returned the same `DateTime`.
> Fix 2 flakey tests

- samples/v2/entitites-csharp/RideSharing/RideSharing/Entities/UserEntity.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs
- test/Common/TestEntities.cs
- test/Common/TestEntityClasses.cs
- test/FunctionsV2/TestEntityWithDependencyInjectionHelpers.cs
In the current implementation, "the existence of state" is somewhat independent of "the existence of an entity". State is created by `ctx.GetState<T>` or `ctx.SetState` (where ctx is the entity context, which can only be accessed while executing an entity operation), and can not be deleted; an entity is created implicitly by any operation, which can be detected after the fact by `ctx.IsFreshlyCreated` and is deleted by calling `ctx.DestructOnExit()` (which also deletes the state). 
*I think this is too confusing* - why not just unify the concepts and the terminology, i.e. consider "entity exists = state exists".
Proposed semantics:
- State is created when an operation calls `ctx.GetState<T>` or `ctx.SetState`
- Existence of State can be tested with `ctx.HasState` 
- State is deleted when …
> Simplify entity state handling

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/TypedInvocationExtensions.cs
Fixes #954 
The `GetState<TState>(Func<TState> initializer` breaks when `TState` is not a complex type. For example, consider the following "functional" entity definition:
```csharp
[FunctionName("MyClass")]
public static void RunOperation([EntityTrigger] IDurableEntityContext ctx)
{
int state = ctx.GetState(() => 0);
state++;
ctx.SetState(state);
}
```
The entity gets and saves its state correctly the first time, but subsequent calls to `GetState` fail with a JSON deserialization exception:
```
Microsoft.Azure.WebJobs.EntitySchedulerException
HResult=0x80131500
Message=Failed to deserialize entity state: Unexpected initial token 'Integer' when populating object. Expected JSON object or array. Path '', line 1, position 1.
Source=Microsoft.Azure.WebJobs.Extensions.DurableTask
StackTrace: …
```
> Fix a bug related to using default state initialization + primitives

- src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/RetryOptions.cs
- test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
Our current version of the storage SDK limits our timer functionality to a maximum of 7 days. We already had these checks for timers, but the same limitations apply to our retry intervals. Without enforcing these limits, customers could get permenantly stuck, and it was difficult to debug why. This silently sets the interval to our maximum when the customer attempts to use intervals larger than our maximum.
Addresses issue #944.
> Enforce a maximum of 6 day intervals for RetryOptions

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs
- src/WebJobs.Extensions.DurableTask/OverridableStates.cs
Added the ability to configure which states you would like to override an existing orchestrator with the same instanceId.
fixes #367
> Added Option to Configure Behavior When Starting a New Orchestrator With an Existing Instance Id

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net471.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-netstandard2.0.xml
- src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestOrchestrations.cs
Limits the number of actions per orchestration in order to prevent performance from dropping with instances with a large history.
MaxOrchestrationActions is a configurable value that is defaulted to 100,000.
Fixes #522
> Limit the number of actions per orchestration

- src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProvider.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/DurabilityProvider.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net471.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-netstandard2.0.xml
- src/WebJobs.Extensions.DurableTask/RetryOptions.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestOrchestrations.cs
Ensure we never schedule a queue message longer than 6 days when using the Azure Storage durability provider.
> Add Azure Storage time delay exceptions

- src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProviderFactory.cs
- src/WebJobs.Extensions.DurableTask/Options/AzureStorageOptions.cs
- src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs
- test/Common/DurableTaskEndToEndTests.cs
In a previous release, we started using the site name as the default
task hub value. However, it is possible for the site name not to be a
valid task hub name for Azure Storage, due to having '-' characters and
not meeting the length requirements. We now ensure that no matter the
sitename, the customer will have a valid task hub.
Addresses issue #976
> Sanitize the default task hub names for Azure Storage

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/DurableContextExtensions.cs
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationClient.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net471.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-netstandard2.0.xml
- test/Common/DurableClientBaseTests.cs
Duplicate of #986 but rebased on to `dev` since v2 got merged in
---
Problem:
The following code:
```csharp
var instanceId = await client.StartNewAsync(@"MyOrchestrator", "thisInstanceId");
Debug.Assert(instanceId == @"thisInstanceId");
```
Will throw the assertion. This is because if a user wishes to specify the instanceId for a new orchestration they _must_ give some form of input - `null` or otherwise. While intellisense is the way one would realize what they're doing wrong, it's only after they attempt this and end up getting back an instanceId value other than the one they specified that they realize something's gone awry due to the fact that `string : object` so the `StartNewAsync(string, object)` overload gets hit and executed.
By using generics we can not only prevent this runtime …
> [Refactor] Generically-typed StartNewAsync() overloads

- src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProviderFactory.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/DurableTaskLifeCycleNotificationTest.cs
- test/Common/TestHelpers.cs
Starting a new orchestration with an existing instance id now has configurable behavior (#987 ). This PR changes the behavior to throw an exception when attempting to start a new orchestration in an invalid dedupe status.
This PR also adds tests for each of the configurable OverridableStates to test this behavior.
Issue related to this change:
#367
> Throws an exception on invalid dedupe status when starting a new orchestration

- test/Common/DurableTaskEndToEndTests.cs
The test was failing because it used a hardcoded instance ID. It passed the very first time it ran, but failed every time afterwards. This fix makes it random so that the test can pass every time.
FYI @amdeel
> Fix Dedupe_Default_NotRunning_ThrowsException

- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs
Recently we changed the namespace of all of our durable classes. #1004 
This PR fixes the namespace references in the Durable Functions Analyzer to match those changes.
resolves #1018 
resolves #1019
> Analyzer: Fixed V2 namespace references

- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionReturnTypeAnalyzer.cs
Fixed activity FunctionReturnTypeAnalyzer to accept the expected return type to be Task regardless of activity function definition return type.
resolves #998
> Analyzer: FunctionReturnTypeAnalyzer wont flag code when expected return type is Task

- src/WebJobs.Extensions.DurableTask/ContextInterfaces/LegacyCompatibility.cs
I found this while looking at the auto-generated API documentation. It appears to be a simple copy/paste error.
> Fix [Obsolete] warning messages

- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Binding/ClientAnalyzer.cs
Currently, the binding analyzer only allows for parameters of type
`DurableOrchestrationClient` for the `OrchestrationClientAttribute`.
This change also allows for `DurableOrchestrationClientBase` as the
abstract base class can be used to facilitate unit testing of the orchestration starter.
This change only affects the analyzer for V1 function apps.
resolves #1053
> Allow OrchestrationClientAttribute on DurableOrchestrationClientBase

- src/WebJobs.Extensions.DurableTask/DurabilityProvider.cs
A typo in the wrapping of
IOrchestrationService.GetDleayInSecondsAfterOnProcessException() method
leads to infinite recursion, causing a StackOverflowException.
Fixes #1077
> Fix infinite recursion in DurabilityProvider

- samples/VSSample.Tests/VSSample.Tests.csproj
- samples/fsharp/DurableFSharp.fsproj
- samples/javascript/extensions.csproj
- samples/precompiled/VSSample.csproj
- samples/webjobssdk/chaining/DFWebJobsSample.csproj
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
- test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj
- Update to version 1.8.4
- Use DurableTask.AzureStorage to 1.6.5
- Update samples to use new version.
> Prepare release for 1.8.4

- src/WebJobs.Extensions.DurableTask/EntityScheduler/TypedInvocationExtensions.cs
This simplifies the code introduced in #935.
It's a small change, but useful in the long run:
- Simplifies and optimizes code
- Making code more safe as we don't rely on the details of the `Type.FullName` string (e.g. how nested types are represented)
- Handles type names edge cases we don't know of yet or other .NET languages introduce later on.
Instead of searching for the correct method on the concrete type itself after one failed attempt, we look for the method with the desired name directly on the interface type, thus having a `MethodInfo` related to the implemented interface. The invokation later on will succeed as long as the durable entity object implements the interface (which is should).
> Simplify Durable Entity operation method discovery for implicit interface implementations

- src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProviderFactory.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net471.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs
Changed TaskHubName in DurableTaskOptions to compare to default value instead of using get and set logic to set a bool field.
This fixes many issues with TaskHub names using slots.
resolves #1068 
resolves #1057
> Fixed TaskHubName to work regardless of get/set order

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableEntityClient.cs
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/EntityMessageEventNames.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/Proxy/DurableEntityProxyExtensions.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/Proxy/EntityClientProxy.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/Proxy/EntityContextProxy.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/Proxy/OrchestrationContextProxy.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/RequestMessage.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net471.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestEntities.cs
- test/Common/TestEntityClient.cs
- test/Common/TestOrchestrations.cs
- test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
- test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj
Adding support for specifying a delivery time for scheduled signals.
The idea is that anyone who can signal an operation (whether it is a client, an orchestration, or an entity), can specify an intended delivery time. When the signal reaches the entity, and the time has not yet arrived, the operation is durably buffered. 
This feature can also be used for timer/reminder type functionality, as entities can signal an operation to themselves.
> Support for scheduled signals

- src/WebJobs.Extensions.DurableTask/EntityScheduler/TypedInvocationExtensions.cs
- src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
- test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj
As discussed in #931, this PR adds a bit of convenience for implementing deletion of entities. 
- One can now issue a DELETE request to the HTTP API, with the effect of signaling an operation called 'delete' on the entity.
- For the class-based syntax, one can call `delete` on an entity with class `T` even if `T` does not have a delete method. In that case `DispatchAsync<T>` simply calls `Entity.Current.Delete()`.
> Add support for delete operation in DispatchAsync and in Http API

- src/WebJobs.Extensions.DurableTask/Bindings/BindingHelper.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/RequestMessage.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/ResponseMessage.cs
- src/WebJobs.Extensions.DurableTask/EventGridLifeCycleNotificationHelper.cs
- src/WebJobs.Extensions.DurableTask/HttpRequestMessageExtensions.cs
- src/WebJobs.Extensions.DurableTask/Listener/DurableTaskListener.cs
- src/WebJobs.Extensions.DurableTask/Listener/DurableTaskScaleMonitor.cs
- src/WebJobs.Extensions.DurableTask/Listener/OutOfProcOrchestrationShim.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskHttpActivityShim.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net471.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/MessageSorterTests.cs
- test/FunctionsV2/DurableTaskScaleMonitorTests.cs
- test/FunctionsV2/OutOfProcTests.cs
I basically updated all the RequestMessage and ResponseMessage APIs to take a MessagePayloadDataConverter as a parameter. It's a pretty simple solution that removes some of the state management we have to do otherwise.
(Note that this currently conflicts with the latest change you added a few minutes ago)
> Alternate proposal for fixing failing unit tests caused by deserialization

- azure-pipelines.yml
Previously, tests did not run on PRs that use a base branch other than dev. This fix allows tests to run on all PRs on this repository. There will be no change in behavior for outside contributors.
> Update azure-pipelines.yml to run on all branches

- src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs
The original PR forgot to add the value of the new config to the debug string, which is important for supportability reasons.
> Add logging of the configured value for UseGracefulShutdown

- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Orchestrator/MethodAttributeAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Resources.Designer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Resources.resx
- src/WebJobs.Extensions.DurableTask.Analyzers/WebJobs.Extensions.DurableTask.Analyzers.csproj
Fixed bug that caused functions defined in an orchestrator to be flagged unless the orchestrator had the Deterministic attribute. Also updated the message appearing on the diagnostic to be more clear.
resolves #1045
> Analyzer: Fixed MethodAttributeAnalyzer to allow local functions inside an orchestrator

- src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProviderFactory.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net471.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/Options/AzureStorageOptions.cs
- test/Common/DurableTaskEndToEndTests.cs
TaskHub validation needs to occur after the TaskHub has been resolved.
To achieve this, we resolve app settings earlier in the pipeline, as
well as waiting to validate the TaskHub until after finishing
constructing AzureStorageDurabilityProviderFactory.
Resolves #1122
> Fix TaskHub validation

- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskActivityShim.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
- test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj
Fixes https://github.com/Azure/azure-functions-durable-extension/issues/472.
This PR currently has a lot of commits because it is waiting for multiple other PRs to be merged.
This PR improves upon https://github.com/Azure/azure-functions-durable-extension/pull/1132 by throwing a `SessionAbortedException` inside `TaskActivityShim` if the WebJobs APIs throw any exception (such as `ObjectDisposedException`).
As part of https://github.com/Azure/durabletask/pull/359, the `SessionAbortedException` now is capable of aborting activity execution. Instead of the activity going into a "failed" state, the execution is abandoned and restarted. The restart will happen on an alternate, healthy instance of the functions runtime and will complete successfully.
I used the following orchestration code to …
> Gracefully handle ObjectDisposedException on host shutdown

- src/WebJobs.Extensions.DurableTask/EndToEndTraceHelper.cs
- src/WebJobs.Extensions.DurableTask/EtwEventSource.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskActivityShim.cs
There are two problems with the current trace experience for the newly added function aborted logic:
1. It's an error, but it should actually be a warning since it's a transient issue.
2. We trace `FunctionFailed` but it didn't actually "fail".
I'm adding a new `FunctionAborted` trace instead of reusing `FunctionFailed`. This is both to improve clarity but also to avoid counting problems. For example, it would be odd to have a function that both failed and completed, and could cause existing Kusto or AI queries to double-count function executions in some cases.
> Change FunctionAborted trace from error to warning

- samples/VSSample.Tests/VSSample.Tests.csproj
- samples/csx/extensions.csproj
- samples/entitites-csharp/Chirper/Chirper.Service/Chirper.Service.csproj
- samples/entitites-csharp/RideSharing/RideSharing/RideSharing.csproj
- samples/fsharp/DurableFSharp.fsproj
- samples/javascript/extensions.csproj
- samples/javascript/host.json
- samples/javascript/local.settings.json
- samples/precompiled/VSSample.csproj
- samples/precompiled/host.json
- samples/precompiled/local.settings.json
* Updating all sample projects to point to v2.1.1 of the extension
* Updating the main precompiled sample to use the latest analyzer version, v0.1.3
* Also updated the precompiled sample to use an app setting for the task hub name (this capability was broken in previous releases)
> Update samples to point to latest package versions

- src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
Functions V3 now uses .NET Core 3.1. Starting in .NET Core 3.0, AllowSynchronousIO defaults to false. Therefore, we needed to change our JSON deserialization logic in the Start Orchestration API to avoid synchronous stream reads
Fixes #1178
> Update HttpApiHandler to work with AllowSynchronousIO = false (#1085)

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/EndToEndTraceHelper.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/MessageSorter.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/RequestMessage.cs
- src/WebJobs.Extensions.DurableTask/EtwEventSource.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestOrchestrations.cs
Previously, for messages sent to entities, the execution id of the originating orchestration was not being tracked, only the instance id. This can lead to problems with the message sorter logic, as discussed in #1152. I added
- tracking and tracing of execution id for messages sent from orchestrations to entities
- include this execution id in events representing responses
- add a testcase where an orchestration sends multiple messages separated by continueAsNew
- modify the message sorter so it starts over when receiving a message from a different execution id
> Fix message sorter

- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskOptions.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-netstandard2.0.xml
This buffer size appears to impact throughput in a substantial way, so
we are allowing customers to configure this in their host.json to try
and optimize throughput.
> Make ControlQueueBufferThreshold configurable for Durable 1.x

- src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs
This is a fix for my previous HTTP listener PR. I uncovered this issue when doing end-to-end testing of all APIs from a JavaScript client.
This PR targets the `dev` branch. A separate PR will target the `v1` branch.
> Fixed null-ref exception in local HTTP listener (V2)

- src/WebJobs.Extensions.DurableTask/DurableOrchestrationClient.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskOptions.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-netstandard2.0.xml
- src/WebJobs.Extensions.DurableTask/OverridableStates.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestHelpers.cs
Like in v2.0.0, added OverridableStates, a configurable option to allow users to specify which states they would like to override an orchestrator instance if an existing instanceId exists.
Defaults to AnyState to avoid changing behavior.
Resolves #1203 
Related to https://github.com/Azure/azure-functions-durable-extension/pull/987 and https://github.com/Azure/azure-functions-durable-extension/pull/1014
> Added configurable OverridableStates

- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net471.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
The tooling finally supports upgrading to 2.3.0, which resolves #771.
> Upgrade WebJobs to 2.3.0 for Functions V1

- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net471.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/Options/AzureStorageOptions.cs
- test/Common/DurableTaskEndToEndTests.cs
Azure Table storage requires names that do not begin with a number. The
current default task hub name does not account for this. We now prepend
't' to the front of the default task hub if it would start with a
number.
Resolves #1210
> Ensure default task hub names are compatible with Azure Tables

- src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProvider.cs
- src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProviderFactory.cs
- src/WebJobs.Extensions.DurableTask/DurabilityProvider.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net471.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs
Default values for Storage Providers are currently not emitted, which
makes servicability much harder. This change adds a virtual method to
DurabilityProvider that allows the default provider to provide its
configuration in JSON form for us to log. Resolves #1137
> Add proper storage provider logging

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/DurableContextExtensions.cs
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/DurableContextExtensionsTests.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestOrchestrations.cs
Rebased original fix from #816 that was lost in the run-up to v2.0.
Previously, `WaitForExternalEvent` when invoked with a specified timeout value would create a Timer instance that was uncancelable by the surrounding orchestration.  This could have the practical effect of making orchestrations hang until either the event was received (causing the timer to be cancelled) or the timeout was reached (because the timer expired).
This change adds overloads for `TimeSpan`-accepting overloads of `WaitForExternalEvent` that allow providing a `CancellationToken`, which the calling orchestration can cancel if it no longer intends to wait for the event to be raised.
Fixes #1041
> Update WaitForExternalEvent to use CancellationTokens

- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
Fixes two bugs:
1. The introduction of IWebHost in LocalHttpListener.cs created a runtime error in Functions V1 due a mismatch in AspNetCore HTTP dependencies between our extension and the Functions V1 webhost.
2. The new serialization handlers were not properly instantiated in the Functions V1 extension initialization process. This led to null reference exceptions. Resolves #1234
> Fix functions v1

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/Listener/OutOfProcOrchestrationShim.cs
This is the C# component of: https://github.com/Azure/azure-functions-durable-js/issues/134
This PR extends the orchestrator shim to accept SignalEntity messages from an out-of-process language like JavaScript. It's quite a _simple_ change but it also contains some preliminary work for requesting Locks from Entities by out-of-process languages. I'd be happy to remove the latter if you all believe it would be better suited for its own PR.
Also, this is my first PR here so I'm happy to take suggestions on formatting and others.
> Allows out-of-proc Orchestration to SignalEntity

- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/NameAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/StringExtension.cs
- test/WebJobs.Extensions.DurableTask.Analyzers.Test/ActivityFunction/NameAnalyzerTests.cs
I got DF0109 warnings when I used `nameof(ActivityFunctionX)` in my `CallActivityAsync` calls. The analyzer tries to compare `"nameof(ActivityFunctionX)"` with `"ActivityFunctionX"`, which fails.
I therefore made a small change to the NameAnalyzer.cs so it compares function names regardless of `nameof()` usage in either the `FunctionNameAttribute` or the `CallActivityAsync` method. I've extended the `Name_NonIssueCalls` unittest with 3 test cases.
> Roslyn Analyzer: Comparing function names which use `nameof()`

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/ResponseMessage.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/SchedulerState.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs
- src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestEntityClasses.cs
- test/Common/TestHelpers.cs
- test/Common/TestOrchestrations.cs
This is the feature we discussed in #1223. It is configurable as an option `RollbackEntityStateOnExceptions` which is true by default.
With rollback enabled, exceptions inside entity operations cause the state of the entity to be rolled back to what it was before the operation. This rollback also undoes creation and deletion of state, and discards any signals sent by the operation.  
To make this possible, the entity state is serialized after each individual operation that accesses the state, which makes it possible to restore that state if the next operation fails. If rollback is disabled (which is the previous behavior), the entity state is not serialized after each individual operation, but only after an entire batch of operations completes, which can be faster.
This PR also includes …
> Implement state rollback for exceptions inside entity operations

- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/TestOrchestrations.cs
- test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj
The introduction of some new test cases add warnings with the analyzers.
To allow the release to continue, we will temporarily stop treating
warnings in test code as reasons to fail a release build.
> Stop treating warnings as errors in tests

- src/WebJobs.Extensions.DurableTask/DurableHttpRequest.cs
Makes a copy of the input serializer and sets TypeNameHandling to Objects to assure correct serialization of ITokenSource in case customers use their own custom serialization settings.
Updated the past implementation to now copy the input settings and add TypeNameHandling.Objects to avoid changing the input JsonSerializer.
> Updated TokenSource serializer

- src/WebJobs.Extensions.DurableTask/DurableClientAttribute.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/OrchestrationClientAttribute.cs
- test/Common/BindingTests.cs
- test/Common/ClientFunctions.cs
- test/Common/DurableTaskHostExtensions.cs
This PR addresses: https://github.com/Azure/azure-functions-durable-extension/issues/1290
There changes are few and simple (_except I apparently pushed other people's commits, more on this later_):
1. `DurableClientAttribute` is no longer a `sealed` class, so we can subclass it.
2. The declaration of a new dummy subclass of `DurableClientAttribute` named `OrchestrationClientAttribute`
3. A new binding rule in `DurableTaskExtension.cs` that explicitly accepts `OrchestrationClientAttribute`. This solution is less than ideal, because there's a handful of copy-pasted lines from the rule accepting `DurableClientAttribute`. Ideally, we would have a single line allowing us to select between the two attributes. If anyone knows how to do this, *please let me know*
So, while this works, I'm still …
> Backwards compatibility for orchestrationClient

- src/WebJobs.Extensions.DurableTask/EntityScheduler/Proxy/EntityProxyFactory.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/TypedInvocationExtensions.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestEntityClasses.cs
- test/Common/TestOrchestrations.cs
Addresses #1276 
This PR allows for Durable Entities classes to be proxied by more than one implemented interface. This current restriction is not explicitly defined on [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-dotnet-entities#restrictions-on-entity-interfaces).
All tests are passing, except for [`ReplaySafeLogger_LogsOnlyOnce`](https://github.com/Azure/azure-functions-durable-extension/blob/dev/test/Common/DurableTaskEndToEndTests.cs#L4310-L4336) on tests for V1 (not sure how to/if address it).
@cgillum @ConnorMcMahon
> Durable Entity proxy with multiple interfaces

- src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
- src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs
- test/Common/DurableTaskEndToEndTests.cs
Our initial implementation of Local HTTP for out-of-proc languages always uses the port 17071. This can cause issues with slots, as well as caused some noisy telemetry when hosts would shut down occasionally.
We now check to see if the default port is available before attempting to bind to it. There is still some degree of race condition if the extensions are instantiated before the port is being listened to, but in general the OS should provide some protections against this.
> Allow for dynamic port usage for local rpc endpoint if 17071 in use

- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Entity/DispatchEntityNameAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Entity/StaticFunctionAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Orchestrator/MethodAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Orchestrator/OrchestratorAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/CodefixProviders/Entity/DispatchEntityNameCodeFixProvider.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/StringExtension.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/WebJobs.Extensions.DurableTask.Analyzers.csproj
- test/WebJobs.Extensions.DurableTask.Analyzers.Test/ActivityFunction/NameAnalyzerTests.cs
- test/WebJobs.Extensions.DurableTask.Analyzers.Test/Orchestrator/MethodAnalyzerTests.cs
resolves #1292 
resolves #1287 
resolves #1310 
Fixes an issue where Orchestrator analyzer threw an InvalidCastException, casting to MethodDeclarationSyntax, when analyzing LocalFunctionStatementSyntax.
Fixes the CallActivityAsync piece of recognizing FunctionNames can be constants in FunctionAnalyzers.
Fixes a bug with MethodAnalyzer that causes a StackOverflowException when analyzing a recursive method.
> Analyzer: FunctionName can be constant in CallActivityAsync, Fixes InvalidCastException

- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskJobHostConfigurationExtensions.cs
- src/WebJobs.Extensions.DurableTask/HostLifecycleService.cs
- src/WebJobs.Extensions.DurableTask/Listener/FunctionExecutionHelper.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskActivityShim.cs
- src/WebJobs.Extensions.DurableTask/Listener/WrappedFunctionResult.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/Common/TestHostShutdownNotificationService.cs
When the Functions JobHost is shutting down, there are often exceptions
occuring in the function execution pipeline unrelated to customer code.
This can lead to cases where the orchestration fails unecessarily, or
in some cases where the exception is largely swallowed, can lead to
orchestrations stuck in an eternally pending state.
We now utilize common logic to try to differentiate between actual user
code failures, and when the failures come from the function pipeline. In
the case where it is a failure in the functions pipeline, we abort the
session, so that Durable Task will try again later.
Resolves #1081
> Abort Durable Task session on Functions runtime failures

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- test/Common/DurableClientBaseTests.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestHelpers.cs
resolves #1248 
related to #1281 
Updated ThrowIfDoesNotExist check to only be called if the connectionName matches the connectionName in DurableTaskOptions.StorageProvider. This prevents an exception from being thrown when a user is signaling an entity or starting an orchestrator in another app.
> Updated DurableClient ThrowIfFunctionDoesNotExist calls to work with correctly when calling a function in another app

- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
This addresses: https://github.com/Azure/azure-functions-durable-extension/issues/1172
This PR aims to add custom App Insights dimensions to enable querying recent orchestrators and entity calls.
For Orchestrators, we add the following fields:
- `DurableFunctionsType` as "Orchestrator"
- `DurableFunctionsInstanceID`
- `DurableFunctionsStatus`
For Entities, we add the following fields:
- `DurableFunctionsType` as "Entity".  I believe this tag name is a confusing, I'm open to improvements. Overall, it was unclear to me if these tags should also be prefixed with `DurableFunctions-` or `DurableEntity`
- `DurableEntityInstanceID`
- `DurableEntityStatus`
I added these tags at the beginning of the "execute" methods, but if mid-execution their state is changed, then maybe this is not a good idea. …
> App Insights Tags for Orchestrators and Entities

- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/ArgumentAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionReturnTypeAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/WebJobs.Extensions.DurableTask.Analyzers.csproj
- test/WebJobs.Extensions.DurableTask.Analyzers.Test/ActivityFunction/ArgumentAnalyzerTests.cs
- test/WebJobs.Extensions.DurableTask.Analyzers.Test/ActivityFunction/FunctionReturnTypeAnalyzerTests.cs
- test/WebJobs.Extensions.DurableTask.Analyzers.Test/ActivityFunction/NameAnalyzerTests.cs
Made several FunctionAnalyzer changes and bug fixes:
resolves #1320 -- 'System.ArgumentException' with message 'Syntax node is not within syntax tree'. due to SemanticModel being passed around without getting new SemanticModel for the node being analyzed
resolves #1322 -- Bug where ReturnTypeAnalyzer didn't properly handle function return types of Task<T> when T was a mismatch JsonArray serialized type (types that implement IEnumerable)
resolves #1324 -- Bug where ValueTuples would be incorrectly labeled as Tuples causing incorrect warnings when using ValueTuples
Adds logic to ArgumentAnalyzer to allow passed input to be a subclass or implementation of the defined input.
Adds logic to ReturnTypeAnalzyer to allow expected return type to be a base/interface for the defined return type. …
> Analyzer: Fixed several FunctionAnalyzer bugs

- src/WebJobs.Extensions.DurableTask/EntityScheduler/Proxy/EntityProxyFactory.cs
It's possible that an interface might only implement another interface, consider for example:
```csharp
public interface IPhoneToUser : ISignalEntityIndex<UserId> {}
```
where `ISignalEntityIndex<UserId>` contains methods to signal. There may be no need for `IPhoneToUser` to expose methods itself.
This PR checks for methods after we've discovered all the methods on the interface and will throw if there are no methods.
> Check for interface methods after we've found them

- src/WebJobs.Extensions.DurableTask/Listener/OutOfProcOrchestrationShim.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskActivityShim.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/OutOfProcExceptionHelpers.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/Common/BindingTests.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/DurableTaskLifeCycleNotificationTest.cs
- test/FunctionsV2/OutOfProcTests.cs
In order to prevent non-determinism errors when out-of-proc
orchestrations throw an exception, we need to read state from the
RpcException. We can then properly replay the actions performed by the
out-of-proc orchestration before throwing the exception.
See https://github.com/Azure/azure-functions-durable-extension/pull/1171 for the equivalent PR for Durable 1.x.
> Handle out-of-process exceptions properly

- src/WebJobs.Extensions.DurableTask/EntityScheduler/Proxy/EntityContextProxy.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestEntityClasses.cs
Fixes the bug found in #1282. 
The conditional that tests whether there is a scheduled time was missing in two of the three methods of the proxy context. Because it was assuming this time is only specified for signals, not for calls. However for interface methods that return a `Task`, the generated proxy is calling not the signal method but one of the call methods so the scheduled time was ignored.
It's an easy fix (just add the missing tests).
> Fix entity proxy base class so it properly schedules signals

- src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProviderFactory.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- test/Common/DurableClientBaseTests.cs
- test/Common/DurableTaskLifeCycleNotificationTest.cs
- test/Common/HttpApiHandlerTests.cs
- test/FunctionsV1/PlatformSpecificHelpers.FunctionsV1.cs
- test/FunctionsV2/AzureStorageDurabilityProviderFactoryTests.cs
- test/FunctionsV2/DurableTaskListenerTests.cs
Worker ids are used to generate unique lease ids for partition
management. Currently this uses Environment.MachineName, which is
currently not unique when running in Azure App Service VMSS
environments.
The App Service on VMSS team is working to make these more unique, but
this will only help within a stamp. Environment.MachineName is
guaranteed to be non-unique across stamps, so we should use a safer
value based on environment varibles present in that environment.
Addresses #1323
> Make worker ids unique when running in App Service VMSS environment

- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/DurableTaskLifeCycleNotificationTest.cs
- test/FunctionsV2/EntityDependencyInjectionTests.cs
- test/FunctionsV2/OutOfProcTests.cs
CIs run tests heavily in parallel, meaning duplciate task hub names on
the storage account will cause tests to conflict with each other. This
is causing the CI to hang indefinitely until the hour time limit
expires. This is odd, as most of the tests have built in timeouts, but
it is best practice to fix the duplicate task hubs anyways.
> Fix duplicate task hub names in tests

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableCommonContext.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/Listener/FunctionExecutionHelper.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestHelpers.cs
- test/Common/TestOrchestrations.cs
- test/Common/UnconstructibleClass.cs
Fixes a bug where constructor failures for non-static orchestrators or entities lead to incorrect behavior, and added testcases.
The desired behavior is to treat constructor exceptions as if they were thrown by the function call.
For entities this means that general entity behaviors (e.g. locking) keep working  even if the function cannot be constructed.
> Handle constructor failures for non-static functions

- test/Common/DurableHttpTests.cs
- test/Common/DurableTaskEndToEndTests.cs
Another round of removing duplicate task hub names in our tests to make
our CI more reliable.
> Remove more duplicate task hub names in tests

- src/WebJobs.Extensions.DurableTask/EndToEndTraceHelper.cs
Due to what appears to be copy-paste errors, some event types were always being logged, even when replay logging is disabled (ExternalEventRaised, ExternalEventSaved, and TimerExpired).  This PR fixes those three event types to pass in the value of `isReplay` to `ShouldLogEvent`, and also cleans up some of the other code in the file to be more consistent (and hopefully avoid copy-paste failures in the future).
Resolves #1351
> EndToEndTraceHelper should respect TraceReplayEvents setting

- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/EndToEndTraceHelper.cs
- src/WebJobs.Extensions.DurableTask/EtwEventSource.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskActivityShim.cs
Resolves #1382.
With this PR, both our ETW traces and the Application Insight traces will have a new `TaskEventId` column for activity function executions. The `TaskEventId` integer value can be used to distinguish two different activity function executions that have the same name. For example, in the `HelloSequence` example, you'd see that each `SayHello` execution has a different `TaskEventId` value (0, 1, and 2).
For orchestrator and entity functions, this value will always be -1 since there isn't a way to associate a single event to a single orchestration function execution (there could be multiple events corresponding to a single execution).
We already have this data in the **DurableTask-AzureStorage** traces. This PR adds the same data to the **WebJobs-Extensions-DurableTask** …
> Add TaskEventId to function traces

- test/Common/DurableTaskEndToEndTests.cs
- test/Common/DurableTaskLifeCycleNotificationTest.cs
- test/Common/TestHelpers.cs
- test/FunctionsV1/PlatformSpecificHelpers.FunctionsV1.cs
- test/FunctionsV2/PlatformSpecificHelpers.FunctionsV2.cs
Our end-to-end tests currently rely on having unique taskhub names so
that tests can be run safely in parallel. This has been proven to be
hard to catch/maintain this restriction, so we add a random 4
alphanumeric suffix to each task hub to make sure that there are never
duplicate taskhub names.
> Make E2E tests more robust in CI pipeline

- test/Common/DurableHttpTests.cs
Changing the test name passed to `GetJobHost()` to be accurate for the `DurableHttpAsync_Asynchronous_AddsBearerToken` test.
> DurableHttp test name fix

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
This change resolves #1344 . The location polling request is a GET request, so removing the content should be fine.
> DurableHttpRequest Content exception during location polling

- src/WebJobs.Extensions.DurableTask/ManagedIdentityTokenSource.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
Resolves #1232 by using DefaultAzureCredential from Azure.Identity instead of AzureServiceTokenProvider from Microsoft.Azure.Services.AppAuthentication.
> Swapping Microsoft.Azure.Services.AppAuthentication nuget dependency for Azure.Identity

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableActivityContext.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/DurableTaskEndToEndTests.cs
resolves #1389 
When the custom setting TypeNameHandling.All is used, GetInputAsJson would throw an exception when attempting to parse the Json to a JArray. This fix adds a check to handle that case.
> Updated DurableActivityContext GetInputAsJson to handle TypeNameHandling All

- src/WebJobs.Extensions.DurableTask/DurableHttpRequest.cs
- src/WebJobs.Extensions.DurableTask/ITokenSource.cs
- src/WebJobs.Extensions.DurableTask/ManagedIdentityOptions.cs
- src/WebJobs.Extensions.DurableTask/ManagedIdentityTokenSource.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/DurableHttpTests.cs
- test/FunctionsV2/OutOfProcTests.cs
These changes resolve #1279 by adding an optional `ManagedIdentityOptions` parameter to `ManagedIdentityTokenSource()`. `ManagedIdentityOptions` is a new type that is introduced with these changes.
The issue mentioned wanted the ability to configure `azureAdInstance` and `tenantId`. `ManagedIdentityOptions.AuthorityHost` is equivalent to `azureAdInstance` and `ManagedIdentityOptions.TenantId` is equivalent to `tenantId`.
> Adding DefaultAzureCredentialOptions to ManagedIdentityTokenSource()

- src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProviderFactory.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/Common/ClientFunctions.cs
- test/Common/DurableClientBaseTests.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/DurableTaskLifeCycleNotificationTest.cs
- test/Common/HttpApiHandlerTests.cs
- test/Common/TestEntityClasses.cs
- test/FunctionsV1/PlatformSpecificHelpers.FunctionsV1.cs
- test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
- test/FunctionsV2/AzureStorageDurabilityProviderFactoryTests.cs
- test/FunctionsV2/AzureStorageShortenedTimerDurabilityProviderFactory.cs
- test/FunctionsV2/DurableTaskListenerTests.cs
- test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj
Updates the following dependencies:
* Microsoft.Azure.WebJobs.Extensions.DurableTask --> 2.3.0
* Microsoft.Azure.WebJobs.Extensions.Analyzers --> 0.3.0
* Microsoft.Azure.DurableTask.AzureStorage --> 1.8.0
* Microsoft.Azure.DurableTask.Core --> 2.4.0
This PR also enables the new structured logging changes by passing in the Azure Functions `ILoggerFactory` into the `TaskHubWorker` and `TaskHubClient` objects we internally manage.
> Update DTFx and analyzer dependencies

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- src/WebJobs.Extensions.DurableTask/DurabilityProvider.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/DurableClientBaseTests.cs
Moved the logic to determine if the connectionName matches to the DurabilityProvider.
Added a check to SignalEntity to check the EntityKey for validity.
resolves #1425
> Updated DurableClient ConnectionName matching function and EntityKey validity checks

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableActivityContext.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
- src/WebJobs.Extensions.DurableTask/MessagePayloadDataConverter.cs
- src/WebJobs.Extensions.DurableTask/MessageSerializerSettingsFactory.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
This change prevents strings that look like dates from being serialized into DateTime objects.
related to Azure/azure-functions-durable-js#208
> Updated default JsonSerializerSetting to include DateParseHandling.None

- .gitignore
- samples/VSSample.Tests/VSSample.Tests.csproj
- samples/csx/extensions.csproj
- samples/csx/host.json
- samples/entitites-csharp/Chirper/Chirper.Service/Chirper.Service.csproj
- samples/entitites-csharp/Chirper/Chirper.Service/host.json
- samples/entitites-csharp/RideSharing/RideSharing/RideSharing.csproj
- samples/entitites-csharp/RideSharing/RideSharing/host.json
- samples/fsharp/DurableFSharp.fsproj
- samples/fsharp/host.json
- samples/javascript/extensions.csproj
- samples/javascript/host.json
- samples/javascript/package-lock.json
- samples/javascript/package.json
- samples/precompiled/VSSample.csproj
- samples/precompiled/host.json
- samples/precompiled/local.settings.json
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
This is for the v2.3.0 release. I looked through all our sample projects and made sure they were up-to-date in terms of the versions of our nuget packages they use.
Related to https://github.com/Azure/azure-functions-durable-extension/issues/1444
> Update samples and XML doc comments

- src/WebJobs.Extensions.DurableTask/CleanEntityStorageResult.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableEntityClient.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestHelpers.cs
- test/Common/TestOrchestrations.cs
Add support for cleaning empty entities and releasing orphaned entity locks.
Addresses the issues discussed in #1325 and #1065.
> support for cleaning entity storage

- samples/precompiled/RestartVMs.cs
This change updates the `ManagedIdentityTokenSource` resource URL in the RestartVMs sample to be `https://management.core.windows.net/.default` as mentioned in #1480.
> Update RestartVMs sample

- src/WebJobs.Extensions.DurableTask/ManagedIdentityTokenSource.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/FunctionsV2/OutOfProcTests.cs
Resolves #1481. This change supports docs that use `https://management.core.windows.net`, `https://management.core.windows.net/`, `https://graph.microsoft.com`, or `https://graph.microsoft.com/` as the `ManagedIdentityTokenSource` resource URL. It replaces those URLs with `https://management.core.windows.net/.default` and `https://graph.microsoft.com/.default` which are the resource URLs used in the new Azure.Identity libraries.
> Resource URL check for ManagedIdentityTokenSource

- test/Common/DurableTaskEndToEndTests.cs
Fixes the tests I saw failing occasionally in other PRs.
The problem is that these tests check the number of empty entities removed, but this number can be off if other tests that run before these also create empty entities.
The solution is to clean the storage prior to the tests, so it starts with a known count of zero.
> fix flaky tests for CleanEntityStorage

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/RequestMessage.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs
- test/FunctionsV2/TimerTests.cs
Addresses issue #1463.
If scheduling signals beyond what the durability provider can take responsibility for, the signal is scheduled for a shorter duration. When receiving a signal ahead of the time it is scheduled to execute, it is then rescheduled (instead of being processed). This keeps going until the scheduled time has been reached. 
This implementation uses the same parameters (DurabilityProvider.MaximumDelayTime and DurabilityProvider.LongRunningTimerIntervalLength) as the corresponding functionality for Timers.
> Support scheduling entity signals without limit on duration

- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs
- test/Common/DurableTaskEndToEndTests.cs
Currently, when extended sessions is set to true for out-of-proc
languages, orchestrations will silently fail. Now, if we detect
out-of-proc languages when extended sessions are true, we emit a warning
and set extended sessions to false.
Fixes #1452.
> Gracefully handle extended sessions for out-of-proc languages

- src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationClient.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/InterfaceOverloadTests.cs
While refactoring IDurableOrchestrationClient in #1422, the eventData parameter for an overload of `IDurableOrchestrationClient.RaiseEventAsync()` was accidentally made optional. This made C# bind `RaiseEventAsync(string, string, string)` to `RaiseEventAsync(string taskHubName, string instanceId, string eventName, object eventData, string connectionName = null)` instead of `RaiseEventAsync(string instanceId, string eventName, object eventData = null)` as intended.
This PR reverts that unintentional change, and adds a test to ensure
this won't happen again in the future.
Fixes #1472
> Fix unintentional breaking change with IDurableClient.RaiseEventAsync

- src/WebJobs.Extensions.DurableTask.Analyzers/ActivityFunctionCall.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/ActivityFunctionDefinition.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/ArgumentAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionReturnTypeAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Entity/StaticFunctionAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/EntityInterface/InterfaceAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/EntityInterface/ParameterAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Orchestrator/ThreadTaskAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/CodeFixProviderUtils.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/CodefixProviders/Orchestrator/TimerCodeFixProvider.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Resources.Designer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Resources.resx
- src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/WebJobs.Extensions.DurableTask.Analyzers.csproj
- test/WebJobs.Extensions.DurableTask.Analyzers.Test/ActivityFunction/ArgumentAnalyzerTests.cs
- test/WebJobs.Extensions.DurableTask.Analyzers.Test/ActivityFunction/FunctionReturnTypeAnalyzerTests.cs
Fixed NullReferenceException when using Nullable types in FunctionAnalyzer by adding a check for them. Added tests to cover Nullable types in ReturnTypeAnalyzerTests. resolves #1428
Fixed another ArgumentException related to SemanticModels. resovles #1457 
Added another error message in ArgumentAnalyzer when using null inputs for a value type. Added tests for this new check.
Refactored FunctionAnalyzer to get ITypeSymbols and store them in ActivityFunctionCall and ActivityFunctionDefinition so the child analyzers no longer have to get that information. Simplified some logic in ArgumentAnalyzer and ReturnTypeAnalyzer.
Incremented the version.
> Anaylzer: 0.3.1 bug fixes and small FunctionAnalyzer refactor

- test/Common/DurableTaskEndToEndTests.cs
Wait a bit longer for partitions to stabalize before scheduling entities
for DurableEntity_ScheduledSignal.
> Fix flaky entity scheduling test

- src/WebJobs.Extensions.DurableTask/LinuxAppServiceLogger.cs
- test/Common/DurableTaskEndToEndTests.cs
_This was originally a small test PR, but now it's grown in scope_
This PR adds missing fields to our LinuxLogger class, providing now a fuller scope of logs and, hopefully, enough to make our telemetry and existing diagnostics tools more effective in debugging linux apps.
The logging validation test has been updated accordingly
> Adding Missing Fields to Linux Logger: ProviderName, TaskName, ActivityId, RelatedActivityId, StampName, etc

- src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/WebJobs.Extensions.DurableTask.Analyzers.csproj
A small typo in PR #1494 resulted in the analyzer failing to load due to
an argument exception. Fixing this typo fixes the problem.
A future PR should be add a test to make sure this doesn't regress in the
future.
> Fix AD0001 warning in Durable Analyzer

- src/WebJobs.Extensions.DurableTask/EndToEndTraceHelper.cs
Part of our effort to shrink our logging footprint in App Service.  The previous behavior can be re-enabled by setting `traceReplayEvents: true` in host.json.
This PR is meant to be merged into https://github.com/Azure/azure-functions-durable-extension/pull/1522.
> Stop logging replays to EventSource by default

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClientFactory.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/IDurableClientFactory.cs
- src/WebJobs.Extensions.DurableTask/DurableClientAttribute.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskJobHostConfigurationExtensions.cs
- src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
- src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/Options/DurableClientOptions.cs
- src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs
- src/WebJobs.Extensions.DurableTask/StandardConnectionStringProvider.cs
Ref  : https://github.com/Azure/azure-functions-durable-extension/issues/161
This is intended to init azure durable functions outside of an azure function orchestrators host.
It could have extensive applications to init durable functions from different applications event from other azure functions applications.
Usability is straight forward for a client. Let's take an Asp.Net Core application.
To configure the application just call AddDurableTask, this will use service collection instead of webjob extension builder. 
```C#
public void ConfigureServices(IServiceCollection services)
{
services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
services.AddDurableTask();
}
```
To create the client just inject `IDurableClientFactory` under the hood this will create a client …
> Durable Client Factory (DurableOrchestrationClient outside Azure Functions )

- src/WebJobs.Extensions.DurableTask/DurableClientAttribute.cs
Our CI fails on warnings, and a warning was being generated because
documentation didn't end in a period.
> Remove documentation warning so CI can pass

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/Listener/OutOfProcOrchestrationShim.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/FunctionsV2/LongTimerTests.cs
Internally WaitForExternalEvent with a timeout uses a timer. In v2.3.0
we added support for long-running timers, we just didn't remove the
now unecessary validation from the WaitForExternalEvent API. This PR
validates the scenario with a test and removes this validation.
Note that initially this PR attempted to expand this functionality to
RetryOptions in CallActivity/SubOrchestrationWithRetry, but
unfortunately the timer used by that retry is lower level than the
Durable Functions layer, meaning we can't use our long-running support.
Addresses #1538
> Expand long running timer functionality to WaitForExternalEvent

- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
I noticed that the task hub worker does not shut down correctly if some functions are disabled with the [Disable] attribute.
The reason is that the `info` variable can be null in the following checks that happen during shutdown:
```csharp
if (this.isTaskHubWorkerStarted &&
!this.knownOrchestrators.Values.Any(info => info.HasActiveListener) &&
!this.knownActivities.Values.Any(info => info.HasActiveListener) &&
!this.knownEntities.Values.Any(info => info.HasActiveListener))
```
As far as I can see this is easily fixed by ignoring null entries for the purpose of this check.
> fix NullReferenceException in task hub worker shutdown

- azure-pipelines.yml
Second attempt to fix the CI nuget tool installer issue. This time I am updating the task for the FunctionsV2Tests job as well.
> Update NugetToolInstaller for Azure Pipelines v2 tests

- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/DurableTaskLifeCycleNotificationTest.cs
- test/Common/TestHelpers.cs
- test/FunctionsV1/PlatformSpecificHelpers.FunctionsV1.cs
- test/FunctionsV2/PlatformSpecificHelpers.FunctionsV2.cs
- test/FunctionsV2/TestCleanup.cs
Our end-to-end tests currently rely on having unique taskhub names so
that tests can be run safely in parallel. This has been proven to be
hard to catch/maintain this restriction, so we add a random 4
alphanumeric suffix to each task hub to make sure that there are never
duplicate taskhub names.
The other benefit of creating non-deterministic taskhubs for each test
run is that we should no longer end up with the corrupted state problem,
where a previous test run somehow corrupted a task hub and the test now
fails until we use a new storage account or preform manual intervention.
Finally, this test adds a dummy test that deletes up to 2000 taskhubs
older than 3 days, to ensure that we don't collect to many entities in
our storage account over time.
> Make E2E tests more robust in CI pipeline (#1385)

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableCommonContext.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/DurabilityProvider.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
- src/WebJobs.Extensions.DurableTask/ProviderUtils.cs
Support for using the EventSourced backend, as in the work-in-progress PR azure/durabletask#461.
Besides adding a durability provider, the changes include:
- turn off message sorter logic for backend that delivers messages in order
- support poll-free version of WaitForOrchestration for backends that support client responses
- change tracing options for unit tests
> Allow Netherite provider to be implemented separately

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestEntities.cs
Adds two properties to `IDurableEntityContext`:
```csharp
/// <summary>
/// The size of the current batch of operations.
/// </summary>
int BatchSize { get; }
/// <summary>
/// The position of the currently executing operation within the current batch of operations.
/// </summary>
int BatchPosition { get; }
```
as discussed in #1456.
> Provide batch position and size information inside entity operations

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/DurableHttpRequest.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskHttpActivityShim.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/Common/DurableHttpTests.cs
- test/Common/TestDurableHttpRequest.cs
- test/Common/TestOrchestrations.cs
These changes resolve #1278 by adding a `Timeout` property to `DurableHttpRequest`. This property defines the timeout for each individual HTTP request. This timeout applies to each asynchronous polling request too.
> Adding Timeout Property to DurableHttpRequest

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableActivityContext.cs
- src/WebJobs.Extensions.DurableTask/MessagePayloadDataConverter.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/Common/TestHelpers.cs
- test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj
Update to DurableTask.AzureStorage v1.8.3, which due to DurableTask.Core, has some changes in how `null` is serialized.
This PR required some small changes to our serialization + test logic to reflect this. None of these changes should be breaking.
> Update Durable Task Framework dependencies

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClientFactory.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskJobHostConfigurationExtensions.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/DurableClientBaseTests.cs
These changes are for the new Durable Client feature (#1125). With the new feature, there isn't a way to create the HTTP management payloads from the lack of a webhook URL so exceptions are thrown when a user tries to call `CreateCheckStatusResponse` or `CreateHttpManagementPayload`.
> Updates to support Durable Client feature

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationClient.cs
- src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/HttpApiHandlerTests.cs
Updated WaitForCompletionOrCreateCheckStatusResponseAsync API to include the parameter returnInternalServerErrorOnFailure. This was left out when we added this parameter to the other CreateCheckStatusResponseAsync APIs.
resolves #1471
> Updated WaitForCompletionOrCreateCheckStatusResponseAsync API

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationClient.cs
- src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
- src/WebJobs.Extensions.DurableTask/HttpManagementPayload.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/HttpApiHandlerTests.cs
Added RestartAsync(string instanceId, bool restartWithNewInstanceId = true) API to rerun orchestrators. Given a valid instance Id of an existing orchestrator, a new orchestrator will be started reusing the same input.
restartWithNewInstanceId is an optional input determining if the started orchestrator instance should reuse the same instance Id or be started with a new instance Id.
resolves #1243
> Added RestartAsync API to rerun existing orchestrator instances

- test/Common/HttpApiHandlerTests.cs
One test did not have the newly added WaitForCompletionOrCreateCheckStatusResponseAsync parameter.
> Fixed test without the newly added WaitForCompletionOrCreateCheckStatusResponse parameter

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
I found this while investigating an unrelated customer issue. The `Status` message represents custom status, which is not what we intended to log (it's also dangerous to log this since it could include sensitive customer data). We should actually be logging the `OrchestrationStatus` value - i.e. "Running", "Completed", "Failed", etc.
> Fix the warning message for unsuccessful termination

- .github/ISSUE_TEMPLATE/new-release-template.md
- .github/pull_request_template.md
- pending_docs.md
- release_notes.md
This PR attempts to tackle the following issues created as a part of the
v2.4.0 retrospective:
- PR template that requires docs to be completed and release notes to be
written before merging a PR (fixes #1603)
- Update our release template to be more up to date, and to split the
tasks into seperate roles (fixes #1604)
Both of these are first efforts, and we may need to tweak them to make
sure that they are providing value.
> Add process changes based on v2.4.0 team retrospective

- src/WebJobs.Extensions.DurableTask/LinuxAppServiceFileLogger.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
Mono.Posix.NETStandard was included since Durable Functions v2.3.1, which increased the size of the deployment package by nearly three times.
This is a contribution by @shibayan :) 
And I have verified that this implementation still raises the correct `inotify` signal, so our telemetry pipeline should continue to work with it
https://github.com/Azure/azure-functions-durable-extension/issues/1597
resolves #1597
> Replace the impl of Syscall.rename and remove Mono.Posix.NETStandard

- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
The `Microsoft.ApplicationInsights.DependencyCollector` package is not used, but it will be included in the artifacts and unnecessarily increases the artifacts size
The tests were run locally. cc @TsuyoshiUshio @cgillum
> Remove ApplicationInsights.DependencyCollector package

- release_notes.md
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableEntityClient.cs
Remove the section about state above 16KB returning default(T), which
has never been true after entities went GA.
Resolves #1631
> Fix incorrect documentation for ReadEntityStateAsync()

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
- test/Common/TestOrchestrations.cs
The current implementation re-constructs the entity state (i.e. constructs the object and populates the fields by deserializing the json) prior to processing each operation (if RollbackEntityOperationsOnExceptions=true, default) or each operation batch (if RollbackEntityOperationsOnExceptions=false). This happens even if that entity state is still in memory.
This seems wasteful; in this PR I modified the state management slightly so it can reuse the already existing object.
> Reduce number of entity deserializations

- release_notes.md
- src/WebJobs.Extensions.DurableTask/DurableTaskJobHostConfigurationExtensions.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/InterfaceOverloadTests.cs
Some customers with .NET Framework apps may be using the
IServiceCollection dependency injection model for their applications, so
these extension methods should be exposed for that scenario.
For a future release, we should expose a simple static method to create
an instance of IDurableClientFactory so .NET Framework apps using other
dependency injection methods can still take advantage of the new
external client work.
> Expose AddDurableTaskFactory methodss to .NET Framework release

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- test/Common/DurableClientBaseTests.cs
Fixed the parameter `returnInternalServerErrorOnFailure` in the `WaitForCompletionOrCreateCheckStatusResponseAsync` method not working as expected.
> Fixed returnInternalServerErrorOnFailure not working as expected

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- test/Common/DurableTaskEndToEndTests.cs
Previously, passing a non-UTC time instead of the expected UTC caused problems in the backend.
To fix this, we call `ToUniversalTime()` which is a no-op if the time is already in UTC, or converts it to UTC if not.
resolves #1689
> Convert scheduledTimeUtc to UTC in SignalEntityAsync

- .github/pull_request_template.md
<-- Start the PR description with some context for the change. -->
Currently, the directions in the PR template aren't proper markdown comments, so they need to either be removed from every PR, or manually turned into comments so they won't render. 
As an example, see above 👀^
This PR simply turns those directions into comments so that the instructions can be preserved while editing the text without the need to modify them further.
> Turn directions in PR template into comments

- release_notes.md
- src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProviderFactory.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskJobHostConfigurationExtensions.cs
- src/WebJobs.Extensions.DurableTask/IDurabilityProviderFactory.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/Common/DurableClientBaseTests.cs
- test/Common/DurableTaskLifeCycleNotificationTest.cs
- test/Common/HttpApiHandlerTests.cs
- test/Common/TestHelpers.cs
- test/FunctionsV1/PlatformSpecificHelpers.FunctionsV1.cs
- test/FunctionsV2/DurableTaskListenerTests.cs
- test/FunctionsV2/EmulatorDurabilityProviderFactory.cs
- test/FunctionsV2/PlatformSpecificHelpers.FunctionsV2.cs
- test/FunctionsV2/RedisDurabilityProviderFactory.cs
- test/FunctionsV2/StorageProviderSelectionTests.cs
These changes allow customers to configure which storage backend they want their app to use (e.g. Azure Storage, MicrosoftSQL, or Netherite) with a new `type` attribute under `durableTask/storageProvider` in host.json (example below). The extension will register all storage backend services and then choose which one to use in the `DurableTaskExtension` constructor. Adding the ability to register all backends and then choose a storage backend allows us to deploy all storage backend packages through extension bundles.
The main changes in this PR are allowing the extension to register a collection of services through dependency injection, adding a `Name` property in `IDurabilityProviderFactory`, and choosing the `DurabilityProvider` by comparing a customers configured `type` with the `Name` …
> Adding Storage Backend Selection in host.json

- release_notes.md
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs
- test/Common/DurableClientBaseTests.cs
- test/Common/HttpApiHandlerTests.cs
- test/Common/TestHelpers.cs
- test/FunctionsV2/DurableTaskListenerTests.cs
Previously, we store the value of the webhook URL during extension
initialization with the assumption that this webhook URL never changes
after startup. This stored value is used for various IDurableClient
methods, along with the out-of-proc clients when local RPC endpoints are
disabled.
However, it turns out that in the case of slot-swap operations,
WEBSITE_HOSTNAME uses the staging slot hostname at site startup, and
only after the slot swap does the hostname change. The function host
listens for a new header value sent as a part of some ping, updating the
source of ExtensionConfigContext.GetWebhookUrl() with the new value once
the slot swap is complete. This PR makes sure we always fetch the value
from the ExtensionConfigContext instead of caching it to ensure we have
the most …
> Ensure using latest webhook url for HTTP management APIs

- src/WebJobs.Extensions.DurableTask/DurableTaskJobHostConfigurationExtensions.cs
- test/Common/DurableClientBaseTests.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestHelpers.cs
- test/FunctionsV2/PlatformSpecificHelpers.FunctionsV2.cs
These changes incorporate the changes from #1706 and register `IPlatformInformationService` in `AddDurableClientFactory()`. Without registering `IPlatformInformationService` , creating a DurableClient with Azure Storage fails because it can't find an implementation of `IPlatformInformationService` in `AzureStorageDurabilityProviderFactory`. This PR also includes a test in DurableClientBaseTests to help us catch if any new services need to be registered in `AddDurableClientFactory()` in the future.
> Register IPlatformInformationService in AddDurableClientFactory()

- release_notes.md
- src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
- src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestHelpers.cs
- test/FunctionsV2/OutOfProcTests.cs
Our previous attempt to dynamically select ports for the local RPC endpoint fixed many issues customers had, but there still exists a race condition when multiple hosts start up at the same time. To completely resolve this issue, this PR makes the following changes:
- Move the code that finds a free port closer to the code that attempts to listen on that port.
- Add a retry layer if the free port has been taken by another worker between when we found the free port and when we tried to listen to that port.
- If we somehow hit this race condition 3 times in a row, even though it should be more rare now, we gracefully fallback to using the public endpoints for out-of-process clients instead of failing to start up the host.
resolves #1273
> Fix Local RPC race condition on app startup

- release_notes.md
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskHttpActivityShim.cs
- test/Common/DurableHttpTests.cs
These changes add a way to handle when  `this.httpClient.SendAsync()` throws an `HttpRequestException` and propagate the exception to customer code. Before this change, the extension would throw an exception about serialization instead of `HttpRequestException`. By handling the `HttpRequestException` in `TaskHttpActivityShim`, an `HttpRequestException` is thrown with a descriptive message.
Resolves #1669
> Handling HttpRequestException in CallHttpAsync()

- release_notes.md
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
The context.GetWebhookUrl() method only works in the context of the
Initialize() method. In order to properly handle this case, we must use
the direct IWebhookProvider made available in FunctionsV2+, and in
FunctionsV1 we have to live with the fact that we can't dynamically
determine the current webhook URI.
> Fix bug in new Webhook URL fetch logic

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
Reconfigure the issue creation flow to point people to using the new Discussions GitHub functionality when asking features or proposing feature ideas without concrete proposals.
> Edit issue creation flow to accomodate Discussions

- release_notes.md
- src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs
Current RPC port selection logic favors ephemeral ports. This leads to
issues with the web apps sandbox.
Instead, we now use randomized port selection from an approved range of
ports.
resolves #1798
> Change local RPC port selection logic

- src/WebJobs.Extensions.DurableTask/DurableActivityContext.cs
- src/WebJobs.Extensions.DurableTask/MessagePayloadDataConverter.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/Common/TestHelpers.cs
- test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
- test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj
Unblocks: https://github.com/Azure/azure-functions-durable-extension/pull/1802
This PR simply upgrades the V1 dependency on AzureStorage from 1.7.7 to 1.8.1.
I decided against upgrading to version 1.8.5 because, starting from version 1.8.2, there are serialization changes in azureStorage that make some of our unit tests to fail. Upgrading to version 1.8.5 will require more careful cherry-picking of commits, as well as expertise in the serialization changes that took place.
resolves N/A
> Upgrade AzureStorage to 1.8.5 in V1

- README.md
It seemed our current README suggests that our Python support is still in Public Preview, when in fact it GA'ed a few months back.
This PR corrects that wording.
resolves N/A
> Mention Python GA in README

- test/Common/TestHelpers.cs
Some of our recent CIs have been timing out. I believe this is, in part, due to our relatively new "WaitUnitlTrue" helper function. `WaitUntilTrue` is supposed to time out on a fixed interval, but it's StopWatch had not been "started" so its value of "ElapsedTime" remained fixed at zero. This meant that it would never time out.
This PR "starts" this StopWatch so tests time out as expected 😄 .
resolves N/A
> Start StopWatch to prevent CI timeouts

- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
Unblocks: https://github.com/Azure/azure-functions-durable-extension/pull/1802
The PR listed above depends on the relatively recent StructuredLogging behavior in DTFx. However, this behavior is only enabled when the DTFx TaskWorker constructor receives LoggerFactory object. It appears we had not ported over that behavior yet. As a result, in the PR listed above, we were missing logs.
This PR enables the StructuredLogging EventSource providers in V1. The change is simple: we now provide the LoggerFactory to the TaskHubWorker ⚡ ⚡ 
resolves N/A
> Enable Structured Logging in V1

- src/WebJobs.Extensions.DurableTask/Bindings/OrchestrationTriggerAttributeBindingProvider.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/EndToEndTraceHelper.cs
- src/WebJobs.Extensions.DurableTask/EtwEventSource.cs
- src/WebJobs.Extensions.DurableTask/Listener/OutOfProcOrchestrationShim.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/FunctionsV2/OutOfProcTests.cs
We recently discovered a handful of telemetry mishaps that occur only to OOProc SDKs. It was determined that these were due to our existing replay logic, which can be imprecise in a few cases. Furthermore, there's evidence suggesting that our replay logic _might_ be the cause for runtime errors as well, which motivates the need to mitigate this issue further.
This PR aims to mitigate these replay imprecisions in a backwards compatible way.
First, some definitions:
- **Compound task**: A task of tasks, either: Task.WhenAll and Task.WhenAny.
- **Atomic task:** A singleton task,  i.e a Task that does not contain other tasks. For example: callActivityAsync.
- **Deep compound tasks**: A compound task containing at least 1 task that is also **compound**,  potentially  **deep** as well. For …
> Support alternative OOProc replay mechanism

- pending_docs.md
- release_notes.md
- src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProviderFactory.cs
- src/WebJobs.Extensions.DurableTask/DefaultPlatformInformationProvider.cs
- src/WebJobs.Extensions.DurableTask/IPlatformInformationService.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/TestHelpers.cs
- test/FunctionsV2/AzureStorageDurabilityProviderFactoryTests.cs
We recently learned that some customers are experiencing increased latency in their orchestration completion times in the Consumption plan. This is because we recently (https://github.com/Azure/azure-functions-durable-extension/pull/1706) changed our concurrency defaults in the Consumption plan to accommodate its resource constraints and scaling behavior.
In that process, we decreased the value of `ControlQueueBufferThreshold` from 256 to just 32. That decrease appears to blame for the increased latency.
This PR increases the default for JS and C# to be 128, a less dramatic decrease from 256. For Python, we keep the default as 32 as we theorize that the Python language worker would benefit from a small  `ControlQueueBufferThreshold` value.
This PR comes as a bit of a hot-patch and is …
> Increase ControlQueueBufferThreshold defaults in Consumption

- release_notes.md
- src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProviderFactory.cs
- src/WebJobs.Extensions.DurableTask/EventSourceListener.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/Common/DurableTaskEndToEndTests.cs
- test/FunctionsV2/AzureStorageShortenedTimerDurabilityProviderFactory.cs
- test/FunctionsV2/CustomEtwDurabilityProviderFactory.cs
- test/FunctionsV2/EmulatorDurabilityProviderFactory.cs
- test/FunctionsV2/PlatformSpecificHelpers.FunctionsV2.cs
If a custom durability provider uses its ETW event source before we
instantiate the Linux logging architecture (like Netherite's ETW event
for instantiating its orchestration service), then the
OnEventSourceCreated method will call before our constructor finishes
instantiating the event source name for the custom provider. This
happens due to the ordering of constructor calls in .NET.
To work around this, we temporarily store all event sources before our
constructor establishes the durability provider event source name so
that we can enable the correct provider when we do establish the provider name.
resolves #1796
> Fix custom backend provider logging on Linux

- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/TypedCodeProvider.cs
- src/WebJobs.Extensions.DurableTask/TypedDurableClientBindingProvider.cs
Previous PR #1813 missed the CI runs because it was from an external contributor, so some build warnings that broke our build slipped in. This PR fixes those.
> Fix build warnings from code-gen PR

- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
TypedCodeProvider was not properly initialized in FunctionsV1, leading to a null reference exception for FunctionsV1 scenarios. This PR properly initializes this type for FunctionsV1.
> Fix code-gen intialization in Functions V1

- test/DFPerfScenarios/Tests/Counter.cs
This PR fixes a simple compilation error in the DFPerfScenarios project. It updates StartCounter by adding `using Microsoft.AspNetCore.Http;` and updating the response value.
> Fix StartCounter C# Performance Test

- src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
Follow-up to: https://github.com/Azure/azure-functions-durable-extension/pull/1836
Disables OOProc state transfer logging until we find a less verbose alternative.
> Disable OOProc State Transfer Logging

- release_notes.md
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj
Upgrade from 1.8.5 to 1.8.6.
The main two improvements in this upgrade is improved support for
concurrent requests to start a singleton orchestration, along with the
required enhancements for the new steal app lease APIs.
> Update DurableTask.AzureStorage dependency

- src/DurableFunctions.TypedInterfaces/README.md
Previous attempt to fix namespace was incorrect, and now instruct people to install nuget package instead of package reference.
> Fix typed interfaces readme namespaces and simplify setup

- release_notes.md
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
This PR is increments the dependency of DurableTask.AzureStorage to v1.8.**7**. The main fix being pulled in is https://github.com/Azure/durabletask/pull/544.
> Fix message loss bug in ContinueAsNew scenarios (update DT.AzureStorage dependency)

- src/DurableFunctions.TypedInterfaces/README.md
Small update to the documentation for CodeGeneration for Durable Functions
- Remove instruction to mark the reference with specific attributes, as these attributes only make sense when adding a Project Reference, and we're talking about a PackageReference here
- Add `<EmitCompilerGeneratedFiles>` to make sure generated code is actually output somewhere
> Small documentation update for CodeGeneration for Durable Functions

- .github/ISSUE_TEMPLATE/new-release-template.md
In the v2.5.0 release, we discovered that releasing new versions of
DTFx.Redis and DTFx.Emulator is unnecessary, and leads to potential
customer confusion.
In addition, the second merge from dev into main after resetting the
release notes and the pending docs felt unecessary, as having the
release tag with those files as they were is acceptable and reduces
unnecessary work.
> Update release template with learnings from v2.5.0

- release_notes.md
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskNonexistentActivityShim.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestActivities.cs
- test/Common/TestHelpers.cs
- test/Common/TestOrchestrations.cs
- test/FunctionsV2/PlatformSpecificHelpers.FunctionsV2.cs
This PR changes the status of orchestration and activity functions that are deleted/disabled/renamed to Failed instead of Running. This clears up queue messages and cleans up nonexistent function instances.
Resolves #1729
> Improve handling of deleted/disabled/renamed orchestrator and activity functions

- release_notes.md
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
> Tweak C# docs for CreateTimer APIs

- .github/pull_request_template.md
To help us close, and track, the OutOfProc SDK feature gap: I'm adding an item to our PR checklist to make sure new features and interface changes in the in-proc C# implementation are tracked for support in OutOfProc SDK repos.
> Add an item on OutOfProc feature parity to PR checklist

- release_notes.md
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/RetryOptions.cs
- test/Common/DurableHttpTests.cs
- test/Common/TestDurableHttpRequest.cs
- test/Common/TestOrchestrations.cs
Adding in `RetryOptions` parameter to the `CallHttpAsync` context method. Allows for automatically retrying Http calls
* Adds an interface method (non-breaking)
* Implements interface method (non-breaking)
* Adds Unit tests (non-breaking)
resolves #1559
> Adding RetryOptions to CallHttpAsync()

- release_notes.md
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/Common/DurableHttpTests.cs
- test/Common/TestDurableHttpRequest.cs
Updating DurableTask.AzureStorage dependency to v1.9.2.
We're about to do a release of v1.9.2 and I want to ensure that the changes in that release don't cause any issues with the Durable Functions extension.
> Update DT.AzureStorage to 1.9.2

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
This PR optimizes the way `pendingExternalEvents` are handled by `DurableOrchestrationContext`. It reduced CPU usage by 50% and allocated memory by a lot. It replaces the stack and the generic reflection with a simpler construct that provides both, the `TaskCompletionSource<T>` and a way to retrieve the event type without obtaining the type of `tcs`
The following suite was used locally. I see no benchmarks in the repo and don't want to introduce a lot of noise in one PR.
```csharp
[Benchmark]
public Task OneEvent()
{
var wait1 = ((IDurableOrchestrationContext)context).WaitForExternalEvent("test");
context.RaiseEvent("test", null);
return wait1;
} 
[Benchmark]
public Task TwoDifferentEvents()
{
var wait1 = ((IDurableOrchestrationContext)context).WaitForExternalEvent("test");
var wait2 = …
```
> DurableOrchestrationContext events performance improvements

- src/WebJobs.Extensions.DurableTask/Listener/OutOfProcOrchestrationShim.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
We recently introduced a new OOProc replay procedure that more accurately represents composite tasks (WhenAll/WhenAny) in the extension.
In the **old** approach, **all** OOProc SDK actions would be awaited **inside** a `WhenAny` Task, which ran the risk of creating a race condition where not all tasks were scheduled at the end of the replay loop. In the new replay procedure, we instead await each task one at a time, avoiding this race condition.
However, in doing so, we've lost the ability to try-catch Activity exceptions in orchestrators. This is because awaiting a failed Task will throw an exception in the replay loop whereas, before, that exception would be "swallowed" by the surrounding `WhenAny` task.
This PR simply introduces a `WhenAny` wrapper to awaited tasks in the OOProc Shim, …
> Protect OOProc replay loop from Activity exceptions

- release_notes.md
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClientFactory.cs
Fixes a bug reported by @scale-tone (#1958).
The problem is that `DurableClient` objects are sometimes constructed without a reference to a DurabeExtension. This can cause NullReferenceExceptions when methods are accessing `this.config`. There are a number of those situations (beyond just the one found in #1958). 
This PR fixes all of them:
- `CleanEntityStorageAsync` now gets the necessary information from the durableTaskOptions and from the durabilityProvider
- Added a constructor that can pass in a client factory, when constructing DurableClient without a DurableTaskExtension 
- This client factory is used (in place of `this.config.GetClient()`) when constructing another client from within DurableClient 
- Added null checks in a few more places
* [ x] My changes **do not** require …
> Fix NullReferenceExceptions in DurableClient

- test/Common/TestOrchestrations.cs
The tests for CleanEntityStorage started failing after recent changes to the AzureStorage backend.
The reason is that the implementation seems to have improved the error handling path under nondeterminism in orchestrator, so it now properly sends unlock messages to all locks that were acquired prior to failing the orchestrator. This is a good thing... but it means that these tests were failing because they are trying to test the removal of orphaned locks, but no orphaned locks were created.
To keep this test working, I needed to use a more reliable way to create the orphaned lock. One way to do this is described in https://github.com/Azure/azure-functions-durable-extension/issues/1977#issuecomment-946240630 - essentially, the idea is to have the replay fail earlier, before the lock is …
> Fix tests for CleanEntityStorage

- release_notes.md
Resetting release_notes.md after v2.6.0 release.
> Reset release_notes.md

- test/DFPerfScenarios/host.json
Adding `"maxOrchestrationActions": 200000` to host.json to allow load tests to exceed 100,000 orchestrations. The default for `maxOrchestrationActions` is 100000.
This change avoids this failure message:
`Maximum amount of orchestration actions 100,000 has been reached. This value can be configured in host.json file as MaxOrchestrationActions.`
> Update host.json in DFPerfScenarios

- .github/ISSUE_TEMPLATE/new-release-template.md
With the latest changes to bundles, we no longer need to create a PR to update them at every extension release. The bundles repo now automatically tracks every release within a major version, so we only need to create PRs against them when releasing a new major version, which is seldom.
As for the templates repo, now we only need to update dotnet samples (`template.json files). When creating PRs against the dotnet templates, we need to target both the v3.x and v4.x branch, so two PRs will be needed in total.
> Update release instructions to include changes to bundles and templates

- src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationClient.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- test/FunctionsV2/AzureStorageDurabilityProviderFactoryTests.cs
While using `Microsoft.Azure.WebJobs.Extensions.DurableTask` I noticed a typo in `IDurableOrchestrationClient`. I figured I'd create a PR to address all instances of this same typo throughout the repository.
All instances of "defauls" have been changed to "defaults".
No issue.
> Change 'defauls' to 'defaults'

- src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs
Currently, OOProc SDKs utilizing the local RPCEndpoint will be constrained in their payload size per request: each needs to be under 30MB. In practice, this means, among other things, that large inputs to orchestrations in OOProc are bounded to be under 30MB. While this is technically a good practice, this limit is not intended and creates divergent behavior when comparing OOProc SDKs to the in-proc C# experience.
This PR removes that limitation by configuring `Kestrel` to have no size checks per request. This should be in line with the removal of size limits on the worker's GRPC channel, which has already taken place.
**On tests:** Our testing infrastructure currently does not allow us to invoke our localRPCEndpoint directly, like OOProc would, so I opted not to add any tests for this …
> Remove payload size limit in localRPCEndpoint

- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
This PR updates our ASPNetCore dependencies to get rid of `dotnet list package --vulnerable` warnings.
Those warnings were introduced by the downgrade in this PR: https://github.com/Azure/azure-functions-durable-extension/pull/1258
From my testing so far, upgrading these dependencies to `1.0.4` does not cause any conflicts with Functions V1 apps. 
resolves N/A
> Update ASPNetCore dependencies

- .github/ISSUE_TEMPLATE/new-release-template.md
Just adding a security check step, running `dotnet list package --vulnerable` on our project, to our release steps. This will warn us of whether any of our dependencies is affected by a known vulnerability, which should probably prompt us to update them.
resolves N/A
> Add security check to release instructions

- src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
- test/Common/HttpApiHandlerTests.cs
There is an issue when using durable client attribute with a specific Taskhub and using the WaitForCompletionOrCreateCheckStatusResponseAsync (the timer wait the timeout before returning status)
resolves #2040
> Fixed usage of durable client attribute not used during waiting for completion

- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Orchestrator/BindingAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Orchestrator/CancellationTokenAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Orchestrator/DateTimeAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Orchestrator/EnvironmentVariableAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Orchestrator/GuidAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Orchestrator/IOTypesAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Orchestrator/MethodInvocationAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Orchestrator/OrchestratorMethodCollector.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Orchestrator/ThreadTaskAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Orchestrator/TimerAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/WebJobs.Extensions.DurableTask.Analyzers.csproj
Incremented Analyzer version to 0.4.2
Fixed bug related to deterministic orchestrator analyzers where diagnostics created in another project caused the analyzer to crash because the syntax tree was not in the compilation being analyzed. Reserved analysis of these files to allow warnings to surface to the orchestrator calling these methods.
Fixed stack overflow bug caused by passing around the wrong semantic model when analyzing methods in other projects.
resolves #2031
> Analyzer: Resolved compilation bug and stack overflow bug

- release_notes.md
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
Incremented DurableTask.AzureStorage to 1.10.1 and the Analyzer to 0.4.2
> Incremented versions for 2.6.1 release

- azure-pipelines-release.yml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.nuspec
This PR adds the SBOM manifest to the release NuGet package. It adds a `dotnet publish` step and moves the manifest generator step to come before the `dotnet pack` step. It also adds a .nuspec file that specifies the additional files that need to get added to the NuGet package during `dotnet pack`.
> Add SBOM to Release NuGet package

- samples/correlation-csharp/getting-started.md
Fix typo in the link text for enabling storage emulator.
> Fix typo: `strorage` -> `storage`

- src/WebJobs.Extensions.DurableTask/WebJobsConnectionInfoProvider.cs
Manual testing on Functions v3 revealed a runtime issue related to the managed identity PR.  The issue is that a particular API (`GetWebJobsConnectionSection`) in the WebJobs SDK can be compiled against but doesn't exist at runtime. This seems to be a problem with the WebJobs SDK or perhaps the packaging of the Functions core tools. Regardless, this PR works around the problem by copying the WebJobs SDK code that we rely on.
The issue only impacts Functions v3. Functions v4 (running on .NET 6) works fine as-is. The conditional compilation flags attempt to isolate the workaround to just Functions v3.
FYI @wsugarman, who helped me identify this workaround.
> Fixed a regression in Functions v3

- src/WebJobs.Extensions.DurableTask/Bindings/OrchestrationTriggerAttributeBindingProvider.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
Send `Config.Options.HttpSettings.DefaultAsyncRequestSleepTimeMilliseconds`, which is used to determine the default time to wait between requests when doing HTTP polling, in the payload to out of proc SDKs. This allows OOProc SDKs to recreate extension behavior to implement callHttp polling for OOProc languages
Unblocks https://github.com/Azure/azure-functions-durable-js/issues/284, JS SDK PR: https://github.com/Azure/azure-functions-durable-js/pull/346
> Send Default Async HTTP Request Sleep Time in OOProc Payload

- src/WebJobs.Extensions.DurableTask/Bindings/OrchestrationTriggerAttributeBindingProvider.cs
Currently, Python SDK versions 1.1.0 to 1.1.3 only handle `upperSchemaVersion` values of 0 (V1) and 1 (V2). This is a problem, because `upperSchemaVersion` was supposed to support arbitrary integers to denote replay protocol versions and we just implemented `upperSchemaVersion.V3` in the Extension.
Technically speaking, the error is due to a bug in the Python SDK. However, due to the auto-upgrading nature of Bundles, I think it's important to consider how to avoid impacting existing SDKs when we're making a minor Extension release. This PR proposes one way to do that.
Essentially, we're "deprecating" the `upperSchemaVersion` field sent to the SDKs and instead utilizing a new field `newUpperSchemaVersion` to include protocol versions larger than V2. This will give the Python SDK the …
> Ensure backwards compat in upperSchemaVersion handling

- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
**The Problem**
Currently, orchestrator code is capable of blocking the WebJobs invocation thread. This prevents WebJobs from issuing a Timeout signal (and other cancellation requests) to the Durable Extension. 
A simple way to reproduce this behavior is by creating an orchestrator that spins in an infinite while loop and to set the Functions timeout to a small number, like 30 seconds. After 30 seconds, the Host will log that it is initiating a cancellation of the orchestrator code, but the orchestrator will remain executing until the Host is forcibly shut down.
For other Function types, including Activities, the Functions Host will shut down quickly on its own after a cancellation is issued.
**Root cause**
This behavior occurs due to an edge case in the WebJobs SDK. See below the WebJobs …
> Enable WebJobs-initiated cancellation of orchestrators

- release_notes.md
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
This adds a check for "illegal awaits" at the end of orchestrator code execution. If an illegal await is detected, we throw an exception.
This is necessary because currently we only check for illegal awaits each time a DF API is invoked, so we're missing the case where the illegal await occurs **without** a subsequent DF API being used.
This exception will not transition the DTFx-level orchestrator state to `Failed`, but it should result in Functions-level telemetry indicating that an illegal await took place.
Related to: https://github.com/Azure/durabletask/pull/725
> Throw on illegal await

- release_notes.md
- src/WebJobs.Extensions.DurableTask/Listener/TaskActivityShim.cs
This PR adds `FunctionsHostStoppingError` to the list of recognized Activity states in the ActivityShim. In particular, it makes `FunctionsHostStoppingError` behave like `FunctionsRuntimeError`, meaning that the Activity would be retried.
Currently, on a `FunctionsHostStoppingError`, we default to a case where an `InvalidOperationException` is thrown. This causes the result to be stored in the History as an error which cannot be de-serialized, which leads to the exception described in: https://github.com/Azure/azure-functions-durable-extension/issues/2162
A second contribution of this PR is that we change the exception type of this default case from `InvalidOperationException` to a `TaskFailure`. This is because all exceptions thrown by our shim ought to be de-serializable. 
Related to: …
> Serialize Host Stopping Event in ActivityShim

- WebJobs.Extensions.DurableTask.sln
- azure-pipelines-release-dotnet-isolated.yml
- src/Worker.Extensions.DurableTask/DefaultDurableClientContext.cs
- src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj
- src/Worker.Extensions.DurableTask/_CSharpLanguageHelpers.cs
This PR adds a release pipeline for the `Worker.Extensions.DurableTask` project and also updates it to target .NET Standard 2.0. The latter change is to enable .NET Framework support.
> .NET Isolated release pipeline + .NET Standard 2.0 support

- release_notes.md
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
- src/Worker.Extensions.DurableTask/.editorconfig
- src/Worker.Extensions.DurableTask/DefaultDurableClientContext.cs
- src/Worker.Extensions.DurableTask/DurableTaskExtensionStartup.cs
- src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs
- src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj
- test/SmokeTests/OOProcSmokeTests/DotNetIsolated/DotNetIsolated.csproj
- test/SmokeTests/OOProcSmokeTests/DotNetIsolated/HelloCitiesUntyped.cs
This PR enables a cleaner coding experience for orchestrator functions in .NET Isolated.
**Before**:
```csharp
[Function(nameof(HelloCitiesUntyped))]
public static string HelloCitiesUntyped([OrchestrationTrigger] string requestState, FunctionContext functionContext) =>
Microsoft.DurableTask.OrchestrationRunner.LoadAndRun<string, string>(requestState, async (context, _) =>
{
string result = "";
result += await context.CallActivityAsync<string>(nameof(SayHelloUntyped), "Tokyo") + " ";
result += await context.CallActivityAsync<string>(nameof(SayHelloUntyped), "London") + " ";
result += await context.CallActivityAsync<string>(nameof(SayHelloUntyped), "Seattle");
return result;
},
functionContext.InstanceServices);
```
**After**:
```csharp
[Function(nameof(HelloCitiesUntyped))]
public static …
```
> .NET Isolated middleware for orchestrator functions

- release_notes.md
- src/WebJobs.Extensions.DurableTask/DurabilityProvider.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs
- src/WebJobs.Extensions.DurableTask/ProtobufUtils.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
There is a regression in the v2.7.1 release when we moved the sidecar logic directly into the extension. Basically, we fail to cast the durability provider into `IOrchestrationServiceQueryClient` and `IOrchestrationServicePurgeClient` objects, resulting in `NotSupportedException`.  This PR fixes this by having `DurabilityProvider` implement this interface and delegate the actual work to the inner DTFx `IOrchestrationServiceClient` implementation.
Resolves https://github.com/Azure/azure-functions-durable-extension/issues/2191
Here is the Java code used for testing:
```java
@FunctionName("GetAllStatus")
public String getAllStatus(
@HttpTrigger(name = "req", methods = {HttpMethod.GET}) HttpRequestMessage<?> req,
@DurableClientInput(name = "durableContext") DurableClientContext …
```
> Fix NotImplementedException for management API calls from Java client

- .github/ISSUE_TEMPLATE/new-release-template.md
Our current DTFx release instructions are out of date. This PR updates the instructions to describe the simpler, pipeline-driven, release procedure.
> Simplify DTFx release instructions

- release_notes.md
- src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
- test/Common/HttpApiHandlerTests.cs
It appears that the instancePrefix parameter is not currently available in the HTTP API when querying instances.
This is probably a simple oversight. This PR adds an optional query parameter 'instanceIdStartsWith' so that instances can be filtered by the instance prefix, just like already supported for the internal query SDKs.
[ ] Documentation PR is ready to merge and referenced in `pending_docs.md`
[x] I've added my notes to `release_notes.md`
[x] My changes **do not** need to be backported to a previous version
[x] I have added all required tests
[x] My changes **do not** require any extra work to be leveraged by OutOfProc SDKs
[x] My changes **do not** change the version of the WebJobs.Extensions.DurableTask package
> Support instanceIdPrefix query parameter for HTTP instance queries

- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
Currently, the Durable Extension takes a dependency on DTFx.AzureStorage, which transitively takes on a dependency on DTFx.Core.
This means that the extension cannot benefit from DTFx.Core changes without an accompanying DTFx.AzureStorage release, irrespective of whether any DTFx.AzureStorage changes warrant that release.
This PR adds an explicit DTFx.Core reference to the project, to circumvent this issue.
> Add explicit DTFx.Core dependency

- release_notes.md
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
This is to address a compatibility issue for .NET Framework, which has stricter assembly versioning requirements.
> Update DTFx version dependencies

- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Entity/DispatchEntityNameAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Entity/StaticFunctionAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Orchestrator/DependencyInjectionAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Orchestrator/DeterministicMethodAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Orchestrator/ThreadTaskAnalyzer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/CodeFixProviderUtils.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/CodefixProviders/Entity/StaticFunctionCodeFixProvider.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Resources.Designer.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/Resources.resx
- src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs
- src/WebJobs.Extensions.DurableTask.Analyzers/WebJobs.Extensions.DurableTask.Analyzers.csproj
- test/WebJobs.Extensions.DurableTask.Analyzers.Test/Orchestrator/DependencyInjectionAnalyzerTests.cs
Added Dependency Injection Analyzer to our Deterministic Method Analyzers to flag variables used in deterministic methods that have been injected in orchestrator classes.
> Analyzer: Added Dependency Injection Analyzer

- src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs
Fix stack overflow exception in `FunctionsOrchestrationContext.SetCustomStatus`.
The cause is a simple incorrect call to `this.SetCustomStatus` instead of `this.innerContext.SetCustomStatus`
resolves #2246
> Fix stack overflow in SetCustomStatus

- src/WebJobs.Extensions.DurableTask/DurabilityProvider.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs
In the Azure Storage provider, some metadata state has to be kept in storage even after entities are deleted, which has led to some confusion in the past (#1364, #1418) and may require users to calls to `CleanEntityStorage` to remove garbage.
With the new backends, there is no longer any need to keep such metadata. However, by default that data still remains there because there is not currently a mechanism in place to remove it.
This PR fixes this by allowing durability providers to remove entity state from storage immediately when an entity is deleted. The trick behind this mechanism is to use the conceptual "inverse" of the autostart feature: any auto-started orchestration that ends with a continueAsNew(null) can be considered to be implicitly deleted. If it should be needed again, such …
> Add support for implicit entity deletion in the durability provider

- release_notes.md
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/IPlatformInformation.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- src/Worker.Extensions.DurableTask/AssemblyInfo.cs
- test/FunctionsV2/OutOfProcTests.cs
- test/SmokeTests/e2e-test.ps1
This is a follow-up from my hackathon project ([Durable Functions in Go](https://twitter.com/cgillum/status/1585491737438351362)). I had to make a change to the extension so that it understood "Custom" as a language worker type, and also make sure that it activated the v2 OOProc middleware code path. With these changes, it should be much easier for anyone to create a custom handler that supports Durable Functions.
Note that the full scenario also requires a change in the Azure Functions host (see https://github.com/Azure/azure-functions-host/pull/8874).
> Support for custom handlers with the V2 OOProc middleware

- release_notes.md
- src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
This PR updates the version of the Microsoft.DurableTask.Sidecar.Protobuf dependency, which includes a fix for CVE-2022-1941, due to Google.ProtoBuf and also includes support for suspend and resume operations over gRPC. This PR also updates the gRPC server implementation in this Durable extension to support rewind, suspend, and resume operations in gRPC.
Resolves https://github.com/Azure/azure-functions-durable-extension/issues/2309
This change unblocks the following parity items for .NET and Java out-of-proc SDKs:
- https://github.com/microsoft/durabletask-dotnet/issues/21
- https://github.com/microsoft/durabletask-dotnet/issues/83
- https://github.com/microsoft/durabletask-java/issues/65
- https://github.com/microsoft/durabletask-java/issues/96
> Update gRPC implementation used by out-of-proc v2 SDKs

- release_notes.md
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/OutOfProcMiddleware.cs
- src/WebJobs.Extensions.DurableTask/OutOfProcOrchestrationProtocol.cs
- src/Worker.Extensions.DurableTask/DefaultDurableClientContext.cs
- src/Worker.Extensions.DurableTask/DurableClientContext.cs
- src/Worker.Extensions.DurableTask/DurableTaskExtensionStartup.cs
- src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs
- src/Worker.Extensions.DurableTask/FunctionsDurableClientProvider.cs
- src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj
- test/SmokeTests/OOProcSmokeTests/DotNetIsolated/DotNetIsolated.csproj
- test/SmokeTests/OOProcSmokeTests/DotNetIsolated/HelloCitiesTyped.cs
This PR updates the dotnet isolated worker extension to the latest changes from https://github.com/microsoft/durabletask-dotnet
The packages have yet to be published to MyGet, so this is not buildable yet.
> Update out-of-proc extension to newest durable SDK bits

- .github/ISSUE_TEMPLATE/new-release-template.md
Added a note to publish the Protobuf package during Extension releases, which is now a dependency. This should reports such as this one: https://github.com/Azure/azure-functions-durable-extension/issues/2324
> Add note about publishing protobuf package in release template

- src/Worker.Extensions.DurableTask/DurableTaskExtensionStartup.cs
- src/Worker.Extensions.DurableTask/ObjectConverterShim.cs
Introduces an `ObjectConverterShim` which bridges the `WorkerOptions.Serializer` (from Azure Functions SDK) with the durable `DataConverter`, aligning serialization between the two.
> Configure dotnet out-of-proc worker options

- azure-pipelines-release-dotnet-isolated.yml
Updates the dotnet isolated extension release build: (1) use `nuget.config` for restore. (2) VSBuild --> DotNetCoreCLI
> Update dotnet isolated release build def

- src/Worker.Extensions.DurableTask/Constants.cs
- src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs
- src/Worker.Extensions.DurableTask/FunctionsOrchestrationContext.InputConverter.cs
- src/Worker.Extensions.DurableTask/FunctionsOrchestrationContext.cs
- test/SmokeTests/OOProcSmokeTests/DotNetIsolated/GreetUser.cs
This is a sub-optimal solution to https://github.com/microsoft/durabletask-dotnet/issues/36. The problem lies in the fact that input is [already deserialized](https://github.com/microsoft/durabletask-dotnet/blob/main/src/Worker/Core/Shims/TaskOrchestrationShim.cs#L47) based on the input type provided to `GrpcOrchestrationRunner`. We use `object` because we do not know what their actual input type is, which ends up being the default type of whatever serializer we are using (`JsonElement` for example).
This PR introduces a workaround by re-serializing and then deserializing to the desired type. A better solution will be considered later. I think overall `GetInput<T>` should go away entirely, and we should use functions binding to let the input be a parameter.
> Fix GetInput issues due to object casting

- src/WebJobs.Extensions.DurableTask/Bindings/OrchestrationTriggerAttributeBindingProvider.cs
This PR partially addresses #2338 by ensuring that serialization of OOProc payloads doesn't depend on any global default settings.
* [] Otherwise: That work is being tracked here: #issue_or_pr_in_each_sdk
> Ensure we don't rely on global defaults when serializing OOProc payloads

- src/WebJobs.Extensions.DurableTask/Bindings/OrchestrationTriggerAttributeBindingProvider.cs
- src/WebJobs.Extensions.DurableTask/DefaultPlatformInformation.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/IPlatformInformation.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
The new external PowerShell SDK requires the provided History JSON array to have enough information to reconstruct its .NET types. This is because we will feed the History to initialize the replay logic of the C#-isolated logic, which manages the replay of this new PS SDK.
To that purpose, this PR modifies `OrchestrationTriggerBinding` so that, when the external PS SDK is enabled (controlled by envvar "ExternalDurablePowerShellSDK"), the provided History JSON array includes the necessary fields to de-serialize the events back into their original DurableTask types in the new PS SDK.
N/A
> Add typename-preserving serializer for new PS external SDK

- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
The latest one On NuGet is still 2.9.0, so our new release version should be 2.9.1. Change it as titled.
> Update Package Version2.9.1

- .github/ISSUE_TEMPLATE/new-release-template.md
Removing Connor's GitHub account and adding Naiyuan's account.
This will affect who gets auto-added as assignee when a release thread is created.
> Update release instructions's assigness

- .github/pull_request_template.md
As in title. It also links to a PR example showing how to extend that range.
> Document, in PR template, that new EventIds should lie within our supported range

- release_notes.md
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
This PR updates our version of `Microsoft.AspNetCore.Mvc.WebApiCompatShim` from `2.1.0` to `2.2.0`. 
Currently, our dependency on `Microsoft.AspNetCore.Mvc.WebApiCompatShim` downloads `AspNetCore.Http` in version `2.1.0` ,which has a security advisory against it. That advisory does not apply to us at runtime because, due to _other_ dependencies, we load  `AspNetCore.Http` in version `2.2.0`. 
Still, to avoid false alarms, it would be best to update our dependencies so that stop downloading `AspNetCore.Http` v2.1.0 at all. This PR achieves just that.
N/A
> Update AspNetCore CompatShim to 2.2.0

- azure-pipelines-release-dotnet-isolated.yml
> Update ESRP to v2, remove netcore 2.1

- release_notes.md
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/EndToEndTraceHelper.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/EntityTraceFlags.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/MessageSorter.cs
- src/WebJobs.Extensions.DurableTask/EntityScheduler/SchedulerState.cs
- src/WebJobs.Extensions.DurableTask/EtwEventSource.cs
- src/WebJobs.Extensions.DurableTask/FunctionState.cs
- src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs
The current implementation of the entity batching contained a bug which caused entities that experienced a high load to stay in a suspended state for a long time (because the resume message was starved).
As a result, we observed situations in which the internal queue in the entity state grows explosively.
This PR
- fixes the suspected reason causing the long delay of the resume message.
- adds a safety measure that un-suspends any entity if it has been suspended for 10 seconds.
- adds very detailed tracing to make it easier to diagnose issues with entity size and entity batch processing in the future.
> Fix bug in entity batch processing that caused entity state size explosion

- .github/ISSUE_TEMPLATE/new-release-template.md
This will ensure that we check and tackle our GitHub security warnings prior to every release.
> Add dependabot check to release instructions

- test/Common/TestEntityClasses.cs
- test/Common/TestOrchestrations.cs
The changes in this PR reduce timing-dependence of entity unit test (CallFaultyEntity) to avoid some spurious test failures we have observed recently.
> Fix entity unit test (CallFaultyEntity)

- src/WebJobs.Extensions.DurableTask/EntityScheduler/MessageSorter.cs
The V2/V3 smoke tests have been failing with this error:
```
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0/build/Microsoft.Build.Tasks.Git.targets(24,5): warning : Unable to locate repository with working directory that contains directory '/root/src/WebJobs.Extensions.DurableTask'. [/root/src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0/build/Microsoft.Build.Tasks.Git.targets(47,5): warning : Unable to locate repository with working directory that contains directory '/root/src/WebJobs.Extensions.DurableTask'. [/root/src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj]
/root/.nuget/packages/microsoft.sourcelink.common/1.0.0/build/Microsoft.SourceLink.Common.targets(52,5): warning : …
```
> Patch V2/V3 .NET smoke tests

- release_notes.md
- src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs
Fixes `LocalGrpcListener.StartInstance` to respect `ScheduledStartTimestamp`
resolves https://github.com/microsoft/durabletask-dotnet/issues/131
> Fix gRPC orchestration start-at

- release_notes.md
- src/Worker.Extensions.DurableTask/FunctionsDurableClientProvider.cs
The `emptyHeaders` dictionary was being included in record-types built in equality & hash-code calculations, thus the cache checks were always a miss. This led to the cache growing for every function invocation and eventually we would hit connection limits (and if that werent there, memory limits). The fix is very simple. I did not add unit tests as there is no test project for the isolated worker extension yet. I did manually verify before/after via debug.
resolves #2439
> Fix hashcode/equality for client cache key

- release_notes.md
- src/Worker.Extensions.DurableTask/FunctionsOrchestrationContext.InputConverter.cs
- src/Worker.Extensions.DurableTask/FunctionsOrchestrationContext.cs
> Use JsonSerializerOptions during GetInput<T>()

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs
- src/WebJobs.Extensions.DurableTask/OverridableStates.cs
Fixes missing dedupe states in the gRPC server client when scheduling a new orchestration via `IOrchestrationServiceClient`. Without the dedupe states, we would effectively restart already running orchestrations when it was scheduled again.
resolves #2466
> Fix missing dedupe states for gRPC client server impl

- src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
resolves [#issue_for_this_pr](https://github.com/microsoft/durabletask-java/issues/112)
We used to get an unclear exception as shown in the above issue. This PR improves the `RPCException` status and message making it more clear for our customers. 
Tested result on Local:
> Improve GRPC exception type and message for duplicate instance. 

- azure-pipelines-release.yml
As in title, just removing an obsolete step.
> Remove pushing to MyGet step from release pipeline

- src/Worker.Extensions.DurableTask/AssemblyInfo.cs
Update the reference of dotnet isolated worker to Durable Functions version to v2.10.*
#2511
> Update dotnet isolated worker extension reference to v2.10.*

- src/WebJobs.Extensions.DurableTask/DefaultPlatformInformation.cs
Replaces: https://github.com/Azure/azure-functions-durable-extension/pull/2450
From the old description: This PR addresses an issue where the customer's function can fail occasionally with an ArgumentException "An item with the same key has already been added". This may occur on current accesses to the dictionary. To make these operations safe, we use a concurrent dictionary.
> Make environment dictionary concurrency-safe

- tools/triageHelper/.funcignore
- tools/triageHelper/.gitignore
- tools/triageHelper/README.md
- tools/triageHelper/function_app.py
- tools/triageHelper/host.json
- tools/triageHelper/requirements.txt
Our GitHub issue triage process spans several repos, meaning that normally we need to do the manual work of collect all open issues with the "needs: triage" label across all DF repositories.
This PR implements a Functions app that does this work for us. It utilizes the GitHub API to automatically query all "needs: triage" labels across all our repos. It can be executed both locally and on Azure.
> Add GitHub triage helper app

- .github/policies/resourceManagement.yml
- .github/workflows/smoketest-python37-v4.yml
- WebJobs.Extensions.DurableTask.sln
- test/SmokeTests/OOProcSmokeTests/durablePy/Dockerfile
This PR makes 2 changes to our GH automation:
(1) It makes our Python smoke test run on Functions V4, given that Functions V2 is EOL and is incompatible with some of the new "Python V2 programming model" changes
(2) It fixes our GH automation so that new issues have the "needs: triage" label added automatically again. This stopped working recently when FabricBot migrated to a new config language
> Patch GH automation

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
I was looking at a CRI and noticed that the link in this exception message is no longer correct. This PR points to the correct link, and also removes the "en-us" segment so that it will redirect to whatever language the user's browser is configured for.
> Update code constraint violation link

- src/WebJobs.Extensions.DurableTask/Correlation/TelemetryActivator.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
Microsoft.Azure.WebJobs.Extensions.DurableTask 2.10.0 --> 2.11.0
Microsoft.Azure.DurableTask.Core 2.13.* --> 2.14.*
Microsoft.Azure.DurableTask.AzureStorage 1.14.* --> 1.15.*
Adding Microsoft.Azure.DurableTask.ApplicationInsights v0.1.0
> Update package versions

- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
Microsoft.Azure.DurableTask.ApplicationInsights v0.1.0 --> v0.1.1
Incrementing Microsoft.Azure.WebJobs.Extensions.DurableTask from v2.11.0 to v2.11.1
> Update Microsoft.Azure.DurableTask.ApplicationInsights package

- src/Worker.Extensions.DurableTask/AssemblyInfo.cs
- src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj
Updating version to 1.0.3
Dependency updates:
Microsoft.Azure.WebJobs.Extensions.DurableTask 2.10.* --> 2.11.*
Microsoft.DurableTask.Worker.Grpc 1.0.2 --> 1.0.3
Microsoft.DurableTask.Client.Grpc 1.0.2 --> 1.0.3
> Update dependencies in Worker.Extensions.DurableTask project

- src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProvider.cs
- src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProviderFactory.cs
- src/WebJobs.Extensions.DurableTask/DurabilityProvider.cs
- src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs
With new core entity support, storage providers can now support entity queries directly. 
This PR updates the durability providers to reflect this. 
Also, for the Azure Storage durability provider, it configures the new features to be enabled by default in passthrough middleware configurations.
This PR depends on https://github.com/Azure/durabletask/pull/957.
is targeting feature branch `feature/core-entities`.
> update durability provider class for new core-entities support.

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- src/WebJobs.Extensions.DurableTask/DurableEntityStatus.cs
With new core entity support, storage providers can now support entity queries directly. 
This PR updates the `DurableClient` class to reflect this. 
This PR depends on https://github.com/Azure/durabletask/pull/957.
is targeting feature branch `feature/core-entities`.
> update DurableClient to take advantage of native entity queries

- src/WebJobs.Extensions.DurableTask/Bindings/EntityTriggerAttributeBindingProvider.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/RemoteEntityContext.cs
- src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
- src/WebJobs.Extensions.DurableTask/OutOfProcMiddleware.cs
- src/WebJobs.Extensions.DurableTask/ProtobufUtils.cs
With new core entity support, storage providers can now dispatch entity work items separately, and DT.Core processes them through in a separate dispatcher.
This PR updates the middleware passthrough to reflect this. 
This PR depends on https://github.com/Azure/durabletask/pull/953. 
is targeting feature branch `feature/core-entities`.
> implement passthrough middleware for entities

- src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs
With new core entity support, storage providers can now support entity queries natively.  
This PR updates the GrpcListener to handle entity queries using this native query support.
This PR depends on https://github.com/Azure/durabletask/pull/957.
is targeting feature branch `feature/core-entities`.
> implement entity queries for grpc listener

- release_notes.md
- src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
An argument was missed when converting to using Durable client for starting new orchestrations.
resolves #2577
> Fix orchestration input

- release_notes.md
- src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/SmokeTests/OOProcSmokeTests/DotNetIsolated/DotNetIsolated.csproj
Reverts:
https://github.com/Azure/azure-functions-durable-extension/pull/2578
https://github.com/Azure/azure-functions-durable-extension/pull/2544
resolves #2581
> Revert LocalGrpcListener usage of IDurableClient

- README.md
The version for Nuget (Microsoft.Azure.Functions.Worker.Extensions.DurableTask) is absent from the readme. This change adds it.
There also seems to be release notes missing for this Nuget for the versions 1.0.0 & 1.0.2. Is there a reason for this? Can release notes be created and backdated (happy to do this if so)
> Update readme to include 'Worker.Extensions.DurableTask' nuget

- src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs
- src/Worker.Extensions.DurableTask/EntityTriggerAttribute.cs
- src/Worker.Extensions.DurableTask/TaskEntityDispatcher.cs
Adds the dotnet isolated worker side trigger and logic to allow for entity invocation. Many APIs are stubbed out to what we expect the final dependencies to look like.
resolves https://github.com/microsoft/durabletask-dotnet/issues/188
> Entities: Add worker side entity trigger and logic

- .github/ISSUE_TEMPLATE/new-release-template.md
Since there is a new version V3 of Durable Functions and it's still in preview, it needs to be updated with the changes of Durable Functions V2. Add the two check items to ensure branch `azure-storage-v12` on DTFx and branch `v3.x` on DF extension updated with the latest changes. 
These two new-added items can be deleted once the `v3.x` becomes the new `dev`. 
> Update Release Template

- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- src/Worker.Extensions.DurableTask/AssemblyInfo.cs
- src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj
> Update packages and version for entities preview

- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
Increase the version from preview.2 to preview .3 as the DurableTask.AzureStorage package reference updates from preview.4 to preview.5. 
> Increase version number

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
This PR does two things:
1. Fixes nullability and stylecop warnings
2. Switches from Microsoft.DurableTask.Protobuf to Microsoft.DurableTask.Grpc for the proto definitions. The later was made so that the microsoft/durabletask-grpc could directly control its own packaging/release without needing to go through the proto repo.
> Switch to Microsoft.DurableTask.Grpc

- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
Delete the follwing packages since they are already included in the DT.AzureStorage v2.0.0. By this we don't need maintain the version twice in both DTFx and DF extension. 
Azure.Core 
Azure.Storage.Tables
Azure.Storage.Blobs
Azure.Storage.Queues
> Update Azure Storage package reference version

- src/WebJobs.Extensions.DurableTask/Options/AzureStorageOptions.cs
- test/FunctionsV1/PlatformSpecificHelpers.FunctionsV1.cs
- test/FunctionsV2/PlatformSpecificHelpers.FunctionsV2.cs
As titled.  Default the Partition Manager V3 at DF v3
> Default Paritition Manager V3 at Durable Function V3

- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
The change from Sidecar protobuf to `Microsoft.DurableTask.Grpc` dropped this reference we need at runtime.
> Fix grpc core

- src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProviderFactory.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
- src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs
- src/Worker.Extensions.DurableTask/FunctionsOrchestrationContext.cs
Three fixes:
- assign entity-related properties in AzureStorageOrchestrationServiceSettings. This was previously missing and therefore the host.json settings were actually being ignored.
- propagate changes from https://github.com/Azure/durabletask/pull/981
- FunctionsOrchestrationContext must override the TaskOrchestrationEntityFeature, otherwise it will throw a not supported message.
tracked in feature branch
> Core entities/various fixes and updates

- test/SmokeTests/e2e-test.ps1
Update Azurite version from `v3.20.1` to the latest `v3.26.0` as the current one is out-of-date. 
> Update Storage Emulator Azurite version

- nuget.config
- test/SmokeTests/OOProcSmokeTests/DotNetIsolated/DotNetIsolated.csproj
Update dotnet isolated smoke tests to use new preview dotnet functions worker SDK. This will address nuget restore issues, allowing us to drive smoke tests off private feeds.
> Use 1.16.0-preview1 Worker SDK for smoke tests

- release_notes.md
- src/Worker.Extensions.DurableTask/FunctionsOrchestrationContext.EntityFeature.cs
- src/Worker.Extensions.DurableTask/FunctionsOrchestrationContext.cs
- src/Worker.Extensions.DurableTask/FunctionsOrchestrator.cs
- src/Worker.Extensions.DurableTask/OrchestrationInputConverter.cs
- src/Worker.Extensions.DurableTask/TaskEntityDispatcher.cs
- src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj
- test/SmokeTests/OOProcSmokeTests/DotNetIsolated/Counter.cs
- test/SmokeTests/OOProcSmokeTests/DotNetIsolated/DotNetIsolated.csproj
Removes a check that asserts the `TaskOrchestrationContext` was accessed. It does not add much value and instead causes issues:
1. As we add extensions / extra functionality to the `TaskOrchestrationContext`, we have to ensure everything is wrapped to make the `IsAccessed=true` call. This is cumbersome.
2. An orchestration could validly have 0 work off the context and be purely computational based on its inputs, we should not block this.
1. e.g: an orchestration could follow a branch that based on the input it decides there is 0 work to be done and just returns.
> Call EnsureLegalAccess from EntityFeature in dotnet-isolated

- release_notes.md
- src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
This PR adds back the usage of `IDurableClient` when using the gRPC out-of-proc languages (.NET and Java). The previous regression is also fixed by using `RawInput`, where DurabeTask.Core will skip serializing and use the already serialized value directly.
> Use IDurableClient with RawInput for LocalGrpcListener

- src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs
Previously, when calling entity client functions on a backend that does not support entities, a `NotSupportedException` was thrown. Unfortunately, the details of that exception are lost after returning to the gRPC caller context.
To fix that, we instead throw an RpcException, whose details are well visible to the caller.
tracked in feature branch.
> Produce better error message when backend does not support entities

- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
Increase DTFx.AS to version 1.16.0.
Increase DF extension to v2.11.5. 
> Increase DTFx.AS version

- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
Since we increase both DTFx.Core and DTFx.AS, so increase the version to v2.12.0. 
> Increase version to v2.12.0

- release_notes.md
- src/Worker.Extensions.DurableTask/AssemblyInfo.cs
- src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj
Update for release of Microsoft.Azure.Functions.Worker.Extensions.DurableTask/1.0.4
> Update Worker extension to 1.0.4

- release_notes.md
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- src/Worker.Extensions.DurableTask/AssemblyInfo.cs
- src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj
> Rev package versions, update release notes

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
It appears that smoke test scripts use an old SDK which is unable to infer the type in this statement.
> Address smoke test build issue

- src/Worker.Extensions.DurableTask/FunctionsOrchestrator.cs
Adds an error log for failed orchestrations. This is only to surface the error to customers.
resolves https://github.com/microsoft/durabletask-dotnet/issues/123
> Log orchestration error

- release_notes.md
- src/WebJobs.Extensions.DurableTask/ContextImplementations/RemoteEntityContext.cs
- src/WebJobs.Extensions.DurableTask/ContextImplementations/RemoteOrchestratorContext.cs
- src/WebJobs.Extensions.DurableTask/Exceptions/EntityFailureException.cs
- src/WebJobs.Extensions.DurableTask/OutOfProcMiddleware.cs
This PR fixes an issue with failed orchestrations and entities not showing up as "failed" in telemetry.
resolves #2595
> Expose OOP invocation errors

- release_notes.md
- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableActivityContext.cs
This PR fixes an issue where when dispatching JToken values to an out-of-proc worker, we would unwrap the serialized contents, thus causing serialization to fail.
resolves #2504, https://github.com/microsoft/durabletask-dotnet/issues/199
> Fix unintentional input unwrapping for OOP workers

- release_notes.md
- src/Worker.Extensions.DurableTask/TaskEntityDispatcher.cs
As reported and diagnosed in https://github.com/Azure/azure-functions-durable-extension/issues/2679, custom serialization for isolated entities is not working properly because the settings in IServices are not passed as an argument when calling `LoadAndRunAsync` on the `GrpcRunner`.
This PR fixes this problem by passing the argument.
resolves #2679
> Fix deserialization for isolated entities

- azure-pipelines-release-nightly.yml
This is a follow up to: https://github.com/Azure/azure-functions-durable-extension/pull/2694
In this PR, I make a copy of the "Release Extension 2.x" pipeline that triggers **nightly** **iff** there's any new code merged in `dev`. If we incorporate this pipeline, we should be able to create automation that runs e2e perf tests on the same night as new code is merged into the `dev` branch. That should help us catch performance regressions faster.
Additionally, this also paves the way for potentially created a nightly package on ADO, which may have its own servicing wins. That said, this PR is primarily for E2E testing automation.
> Add a nightly release pipeline

- src/Worker.Extensions.DurableTask/ActivityInputConverter.cs
- src/Worker.Extensions.DurableTask/ActivityTriggerAttribute.cs
- src/Worker.Extensions.DurableTask/DurableClientAttribute.cs
- src/Worker.Extensions.DurableTask/DurableTaskExtensionStartup.cs
- src/Worker.Extensions.DurableTask/HTTP/HttpHeadersConverter.cs
- src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj
This PR adds an explicit `ActivityInputConverter` to work around the default Functions converter we were relying on.  Specifically, the default converter special cases a few types (such as string) which we do not want. Adding this converter also has the added benefit of ensuring consistency between orchestrations and activity deserialization.
Another change is to register `DurableTaskClientConverter` directly on `DurableClientAttribute` via `InputConverterAttribute` (this was not available when we first wrote this converter).
resolves #2674
> Add ActivityInputConverter

- azure-pipelines-release-nightly.yml
- azure-pipelines-release.yml
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
Replaces: https://github.com/Azure/azure-functions-durable-extension/pull/2707
When making a private extension release, we manually add a version suffix to the package so that it can be distinguished from an official release.
This PR automates that process in 2 ways:
(1) the CI automatically adds a version suffix when the standard/manual release pipeline is triggered in a feature branch. The version suffix will be `-pr.<yyyymmdd.<buildRev>>` where `<buildRev>` is an integer that increases every time the pipeline is triggered on a given day.
(2) the CI automatically adds a version suffix when the nightly release pipeline is triggered. The version suffix will be `-ci.<yyyymmdd.<buildRev>>` where `<buildRev>` is an integer that increases every time the pipeline is triggered on a given day.
> automatically generate version suffixes

- release_notes.md
- src/Worker.Extensions.DurableTask/DurableTaskClientExtensions.cs
- test/SmokeTests/OOProcSmokeTests/DotNetIsolated/DirectInput.cs
With AspNetCore support via extension in dotnet isolated, customers are unable to use our `CreateCheckStatusResponse` APIs due to synchronous IO not being allowed by default. While we don't want to add direct AspNetCore support at this time (would require bringing in that extension package, which is a no-go for us without our own separate package). We can in the short term add `CreateCheckStatusResponseAsync` which will fix the no-sync IO issue.
resolves #2717
> Add CreateCheckStatusResponseAsync APIs

- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
Update DurbaleTask.Core to v2.16.1 for v2.13.1 release.
> Update DurableTask.Core to v2.16.1

- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
As titled. Routine PR for v2.13.1 release. DurableTask.ApplicationInsights 0.1.3-> 0.1.4, DurableTask.AzureStorage 1.17.0 -> 1.17.1 
> Increase DTFx.AS version to v1.17.1

- .github/ISSUE_TEMPLATE/new-release-template.md
> Add dotnet isolated release process to release templates

- release_notes.md
- src/WebJobs.Extensions.DurableTask/OutOfProcMiddleware.cs
The current code is not properly handling failing entity operation batches. Specifically, for failing batches, it was failing all operations indiscriminately, instead of processing the failure details of each operation in the batch and sending them back to the orchestration caller.
This PR fixes the problem by propagating the results of the batch back to the DurableTask middleware pipeline, even if the function failed.
I think this bug could have been caught if the entity tests #2612 were run in CI, as opposed to having to run them manually (I remember these tests all passing last year but they are failing now which alerted me to this problem).
> Fix handling of entity operation errors for isolated entities

- src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableActivityContext.cs
- test/SmokeTests/OOProcSmokeTests/durableJS/DurableFunctionsOrchestratorJS/index.js
- test/SmokeTests/OOProcSmokeTests/durableJS/PrintArray/function.json
- test/SmokeTests/OOProcSmokeTests/durableJS/PrintArray/index.js
- test/SmokeTests/OOProcSmokeTests/durableJS/PrintObject/function.json
- test/SmokeTests/OOProcSmokeTests/durableJS/PrintObject/index.js
- test/SmokeTests/OOProcSmokeTests/durableJava/src/main/java/com/functions/AzureFunctions.java
- test/SmokeTests/OOProcSmokeTests/durablePy/DurableFunctionsOrchestrator/__init__.py
- test/SmokeTests/OOProcSmokeTests/durablePy/Print/__init__.py
- test/SmokeTests/OOProcSmokeTests/durablePy/Print/function.json
- test/SmokeTests/OOProcSmokeTests/durablePy/PrintArray/__init__.py
- test/SmokeTests/OOProcSmokeTests/durablePy/PrintArray/function.json
- test/SmokeTests/OOProcSmokeTests/durablePy/PrintObject/__init__.py
- test/SmokeTests/OOProcSmokeTests/durablePy/PrintObject/function.json
As in title. Also adds de-/serialization tests in the smoke tests thanks to @bachuv
> Patch deserialization bug in 2.13.1

- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
As in title. Upgrading `Azure.Identity` to `1.10.2` in our all TFMs except `.net462`, which we can't upgrade without causing the following assembly loading exception in Functions V1:
> Exception while executing function: HttpStart -> Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=5.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.",
At the very least,  I think this is a partial start, so I'd like to merge this even if we don't have an answer for Functions V1.
We need this change to address some vulnerability warnings when running `dotnet list package --vulnerable`
> Upgrade Azure.Identity to 1.10.2

- src/WebJobs.Extensions.DurableTask/ContextImplementations/RemoteOrchestratorContext.cs
- src/WebJobs.Extensions.DurableTask/OutOfProcMiddleware.cs
As diagnosed in #2743, the current code in `OutOfProcMiddleware.CallOrchestratorAsync` does not correctly propagate the results of a failed orchestration to the backend.  
The problem is that when an orchestrator function fails, the OrchestratorExecutionResult that was constructed by the executor is ignored, and instead an alternate OrchestratorExecutionResult.ForFailure is constructed from the exception returned by the function result. This is a problem because 
1.  the original failure details are lost instead of being persisted in the history.
2.  any orchestrator actions that took place prior to the failure (e.g. sending lock release messages) are ignored.
This PR fixes the problem by propagating the original `OrchestratorExecutionResult` that describes the failure (if there is one).
> Correctly propagate orchestration results of a failed orchestration

- release_notes.md
- src/WebJobs.Extensions.DurableTask/OutOfProcMiddleware.cs
Resolves https://github.com/Azure/azure-functions-durable-extension/issues/2711
There were a few edge cases that weren't being handled correctly when dealing with activity exceptions in .NET out-of-proc. The edge cases included:
- Cases when customers override `Exception.ToString()` and change the exception message formatting
- Cases when customers enable `WorkerOptions.EnableUserCodeException`
In the above cases, what we receive from the .NET Isolated worker changes from what we expect, resulting in exception information missing when customers try to handle exceptions in their orchestrator function code. The changes in this PR are meant to cover these corner cases and provide users with more accurate exception information.
> .NET out-of-proc error parsing fixes

- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- src/Worker.Extensions.DurableTask/AssemblyInfo.cs
- src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj
As in title, routine PR
resolves N/A
> Rev versions for 2.13.2 extension release

- src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj
Follow up to: https://github.com/Azure/azure-functions-durable-extension/pull/2766 and https://github.com/Azure/azure-functions-durable-extension/pull/2764
Increases:
* Microsoft.DurableTask.Client.Grpc
* Microsoft.DurableTask.Worker.Grpc
to version 1.2.2
I assume this is what's meant by "Update .NET Isolated SDK version at Worker.Extensions.Durabletask.csproj" [here](https://github.com/Azure/azure-functions-durable-extension/issues/2765)
> Rev ooproc SDK pkgs to 1.2.2

- src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs
> Set gRPC message length to int.MaxValue

- src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs
In the LocalGrpcListener's CreateInstance method, we catch an `InvalidException` and disregard it's contents. This PR ensures we log it's contents so we can better debug exceptions in this code path.
resolves N/A
> Log caught exception in LocalGrpcListener's CreateInstance method

- release_notes.md
- src/WebJobs.Extensions.DurableTask/Auth/AzureCredentialFactory.cs
Suppress execution context from the background token renewal operations. The renewal uses the logger, and so we will capture whatever current log scope is present, leaking that scope into this background thread. This is both a small memory leak and potential object disposed failure (the log scope or its contents may be disposed at any point).
> Suppress execution context from token renewal

- release_notes.md
- src/Worker.Extensions.DurableTask/DurableTaskClientExtensions.cs
Currently, the `CreateCheckStatusResponseAsync` only returns a subset of the expected URIs: it's missing the ones for suspend/resume.
This PR adds them.
resolves N/A
> Add suspend/resume URIs to createcheckresponse payload

- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
As in title, to address CVE: https://github.com/advisories/GHSA-wvxc-855f-jvrv
> Update Azure.Identity dependency to 1.11.0

- src/Worker.Extensions.DurableTask/DurableTaskClientExtensions.cs
Add HttpRequestData null handling in CreateCheckStatusResponse.
> Add HttpRequestData null handling

- release_notes.md
- src/Worker.Extensions.DurableTask/FunctionsDurableTaskClient.cs
resolves https://github.com/microsoft/durabletask-dotnet/issues/282
> Fix missing overloads on client

- src/Worker.Extensions.DurableTask/ActivityInputConverter.cs
- src/Worker.Extensions.DurableTask/ActivityTriggerAttribute.cs
Fix issue #2741 
When activity functions with only one parameter, the FunctionContext, would incorrectly have the FunctionContext set to null after ConvertAsync() at ActivityInputConverter. That's because the ContextConverter handles the `source` as null and `TargetType` as FunctionContext. This PR adds a specific case in the ActivityInputConverter to address this issue.
> Update ActivityInputConverter for Activities with FunctionContext-only parameters

- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
As titled. Routine PR for v2.13.3 release.
WebJobs.Extensions.DurableTask v2.13.2  -> v2.13.3
DTFx.Core v2.16.1 -> v2.17.0
DTFx.AzureStorage  v1.17.1 -> v1.17.2
> Increase in-proc Extension Patch Version and DTFx Dependecies Version

- src/Worker.Extensions.DurableTask/AssemblyInfo.cs
- src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj
As titled. Routine PR for release:
Worker.Extension.DurableTask 1.1.2 -> 1.1.3
Microsoft.DurableTask.Client.Grpc: 1.2.2 ->1.2.3
Microsoft.DurableTask.Worker.Grpc: 1.2.2 -> 1.2.3
Assembly info of durable extension: 2.13.2 ->2.13.3
> Increase Worker.Extension.DurableTask version and .NET out-of-proc SDK verseion

- WebJobs.Extensions.DurableTask.sln
- release_notes.md
- src/Worker.Extensions.DurableTask/AssemblyInfo.cs
- src/Worker.Extensions.DurableTask/FunctionsDurableTaskClient.cs
- src/Worker.Extensions.DurableTask/HTTP/HttpMethodConverter.cs
- test/Worker.Extensions.DurableTask.Tests/FunctionsDurableTaskClientTests.cs
- test/Worker.Extensions.DurableTask.Tests/Worker.Extensions.DurableTask.Tests.csproj
Follow up to: https://github.com/Azure/azure-functions-durable-extension/pull/2802
The PR above made the `FunctionsDurableTaskClient` override new overloads from `DurableTaskClient` which were causing issues as reported here: https://github.com/microsoft/durabletask-dotnet/issues/282#issuecomment-2114590648
Seems we missed the `TerminateInstanceAsync` API in the PR above, so this PR adds it.
This PR also adds what appears to be the first set of unit tests for the .NET isolated worker extension. In it, we're testing against this particular exception: that the `TerminateInstanceAsync` API can be invoked without triggering exceptions. I tested with and without the code change and confirmed that the test is fails without the change, and passes with it.
**Note:** the new test project I added …
> Override new "base" Terminate API

- test/Worker.Extensions.DurableTask.Tests/Worker.Extensions.DurableTask.Tests.csproj
Update Worker.Extensions.DurableTask.Tests.csproj .NET Framework Version from .NET8 to .NET6 since our release pipeline is still based on .NET 6.
> Update Worker.Extensions.DurableTask.Tests.csproj .NET Framework Version from .NET8 to .NET6

- src/Worker.Extensions.DurableTask/AssemblyInfo.cs
- src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj
As titled.
.NET dependencies version v1.2.3 -> v1.2.4
Worker extension v1.1.3 ->v1.1.4
> Upgrade .NET out-of-process Dependencies and Increase Worker Extension Version

- src/WebJobs.Extensions.DurableTask/AzureStorageAccountProvider.cs
- test/Common/AzureStorageAccountProviderTests.cs
This PR caches `TokenCredential` to resolve a memory issue that has been reported when managed identity is enabled. With these changes, we only create the `TokenCredential` object once instead of every time that `GetStorageAccountDetails()` is called. This also means that `TokenRenewalState` is also created once.
These changes were verified by enabling managed identity locally using [these instructions](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-configure-durable-functions-with-credentials#configure-your-app-to-use-client-secret-credentials) and measuring the memory in VS with and without the changes in this PR.
> Cache TokenCredential

- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
As titled. Increase Azure.Identity to the latest v1.11.4 as v1.11.0 has been deprecated.
> Increase Azure.Identity Dependency to v1.11.4

- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
As titled. Update Azure.Identity to the latest v1.11.4 as v1.11.0 became deprecated.
> Update Azure.Identity to the latest version v1.11.4

- src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
- test/Common/HttpApiHandlerTests.cs
We periodically receive questions about apps failing with the following error "Webhooks are not configured". This often occurs when running in K8s environments.
This PR augments our error message to provide guidance on how to work around this error.
> Provide actionable suggestions for when webhooks are not configured

- eng/ci/official-build.yml
- eng/templates/build.yml
This PR migrates the pipelines to 1ES pipelines. It adds 2 files - official-build.yml and build.yml. official-build.yml references build.yml and runs on any changes pushed to the main branch.
> Migrate to 1ES pipelines

- .github/workflows/validate-build-analyzer.yml
- .github/workflows/validate-build-e2e.yml
- .github/workflows/validate-build.yml
- src/WebJobs.Extensions.DurableTask.Analyzers/WebJobs.Extensions.DurableTask.Analyzers.csproj
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/Common/DurableTaskEndToEndTests.cs
- test/Common/TestDurableClient.cs
- test/Common/TestHelpers.cs
- test/FunctionsV2/CorrelationEndToEndTests.cs
- test/FunctionsV2/OutOfProcTests.cs
- test/FunctionsV2/PlatformSpecificHelpers.FunctionsV2.cs
- test/SmokeTests/SmokeTestsV1/VSSampleV1.csproj
As part of our 1ES migration - we're replacing our ADO unit, integration, and end to tests with GitHub actions that use Azurite as a backing Azure Storage store. This PR does just that: it creates 3 new GitHub actions - one for the analyzer tests, one for the E2E tests, and another for the remaining tests.
Finally, this PR also resolve a myriad of build warnings, for clean up sake.
> Replace ADO tests with GitHub actions

- samples/durable-client-managed-identity/aspnetcore-app/Controllers/TodoController.cs
- samples/durable-client-managed-identity/aspnetcore-app/Program.cs
- samples/durable-client-managed-identity/aspnetcore-app/README.md
- samples/durable-client-managed-identity/aspnetcore-app/Startup.cs
- samples/durable-client-managed-identity/aspnetcore-app/ToDoList.csproj
- samples/durable-client-managed-identity/aspnetcore-app/ToDoList.sln
- samples/durable-client-managed-identity/aspnetcore-app/appsettings.json
- samples/durable-client-managed-identity/functions-app/ClientFunction.cs
- samples/durable-client-managed-identity/functions-app/DurableClientSampleFunctionApp.csproj
- samples/durable-client-managed-identity/functions-app/README.md
- samples/durable-client-managed-identity/functions-app/Startup.cs
- samples/durable-client-managed-identity/functions-app/host.json
- samples/durable-client-managed-identity/functions-app/local.settings.json
Add samples showing how to use external durable client with identity based connection.
> Add Injected Durable Client with Identity Based Connection Samples

- test/Common/DurableTaskEndToEndTests.cs
- test/Common/HttpApiHandlerTests.cs
The `DurableEntity_CleanEntityStorage` test has been extremely flakey ever since our migration to GitHub actions.
The test works broadly as follows.
It sets up 2 orchestrators: "A" and "B".
(1) Orchestrator "A" takes a lock on Entity "E", and completes without releasing that lock.
(2) Orchestrator "B" tries to take a lock on "E", and gets stuck until "E"'s current locking by A is forcibly broken.
(3) The test sends a "release orphaned locks" request to "E" so that "B" may obtain the lock and compete.
(4) The test waits for "B" to complete, then performs some assertions.
The test would often fail on step (4), because "B" would fail to receive the lock. The reason for this is that step (3) had a race condition. When sending a "release orphaned locks" external event to "E", that external …
> Refactor entity cleanup test to make it less flakey

- eng/ci/official-build.yml
As in title, needed for 1ES integration.
May need to cherry-pick this to the v2 branch
> Run official build nightly

- samples/durable-client-managed-identity/aspnetcore-app/ToDoList.csproj
- samples/durable-client-managed-identity/functions-app/DurableClientSampleFunctionApp.csproj
Downgrade Microsoft.Azure.WebJobs.Extensions.DurableTask from v2.13.5 to v2.13.4. v2.13. 5 hasn't been released and thus the official build CI couldn't pass. We need to update this version back to v2.13.5 again once v2.13.5 finishes released since managed identity at external durable client is only supported starting from v2.13.5
> Rev Durable Functions Package at External Client Samples

- .github/workflows/codeQL.yml
- eng/templates/build.yml
Adds CodeQL GH action. It also changes the `dotnet pack` output directory, which is believed to be a pre-requisite for artifacts to be uploaded to ADO.
> Add codeql GH action, change pack directory in official pipeline

- src/Worker.Extensions.DurableTask/AssemblyInfo.cs
- src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj
As titled. 
- worker extension from v1.1.4 to v1.1.5 
- Microsoft.Azure.WebJobs.Extensions.DurableTask from v2.13.4 to v2.13.5. 
> Increase Worker Extension to v1.1.5 

- eng/ci/official-build.yml
This PR adds `dev` to the list of branches we run codeQL over. This will ensure we catch regressions in the `dev` branch, which is one of our main merge targets
> Add dev to list of CodeQL branches

- Directory.Build.targets
- WebJobs.Extensions.DurableTask.sln
When building in 1ES, source-link information gets lost due to the code-mirror'ing. This creates issues during debugging, as Visual Studio would be unable to determine where to download the source code from. This PR aims to fix that by following conventions set by the Azure Functions Host.
DF WebJobs extension version of this PR: https://github.com/Azure/durabletask/pull/1147
> Add source link reconstruction

- eng/templates/build.yml
- src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProviderFactory.cs
- src/WebJobs.Extensions.DurableTask/Options/AzureStorageOptions.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- test/SmokeTests/e2e-test.ps1
This PR was opened primarily to increase the WebJobs extension version to 2.13.6, and increase the DTFx.AS dependency to 1.17.5, which allows us to support the upcoming `AllowReplayingTerminalInstances` DTFx property.
However, the CI revealed two more problems:
(1) The Azurite version used in our tests was out of date, creating issues. So we've increased the Azurite version from 3.26 to 3.32.
(2) The 1ES build of the WebJobs extension was being flagged as non-deterministic. I added the determinism flags (`/p:FileVersionRevision=$(Build.BuildId) /p:ContinuousIntegrationBuild=true`) in our offficial build yml, which we already use in [DTFx](https://github.com/Azure/durabletask/blob/ed3ece34ba4a22b6945388acf3972e1440ea8881/eng/templates/build.yml#L47) and other packages.
> Rev WebJobs Extension to 2.13.6, Rev DTFx.AS dependency to 1.17.5, make 1ES build deterministic, increase CI Azurite version

- release_notes.md
- src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
- src/WebJobs.Extensions.DurableTask/ProtobufUtils.cs
- src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
- src/Worker.Extensions.DurableTask/AssemblyInfo.cs
- src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj
This change updates the Microsoft.DurableTask.Grpc package to the latest version (1.3.0). This is important because there was a breaking change in an earlier version of this package, making the extension incompatible with certain backend extensions. This change will fix the incompatibility.
This PR also updates the versions in the `WebJobs.Extensions.DurableTask` and `Functions.Worker.Extensions.DurableTask` projects.
Without this fix, it's possible for certain backends to run into a `MissingMethodException` on `set_CorrelationData` since that property was removed in a previous version of the `Microsoft.DurableTask.Grpc` package. This PR removes the dependency on that missing property and replaces it with the modern (TraceV2) variant. This only impacts .NET Isolated and Java. There's no …
> Update Microsoft.DurableTask.Grpc to latest version

- eng/templates/build.yml
For codeQL compliance, we need to build our Java smoke test, as it's being detected in our codebase and cannot be analyzed without being built.
> Build java smoke test on build pipeline (for codeQL compliance)
