docfx/articles/samples/sequence.md

Line 47: 'function your are calling' -> 'function you are calling'

Fixed typo

---

docfx/articles/topics/checkpointing-and-replay.md

Fixing links to Task Orchestration Executor and Task Orchestration Context.

Fixing links

---

docfx/articles/installation.md

For me following the instructions did not work if I am not running the local storage emulator and set the connection string to it or storage account in Azure.

Adding instructions for setting Storage Account

---

docfx/articles/topics/sub-orchestrations.md

Adding missing deviceId parameter to CallSubOrchestratorAsync method

Fix typo in sub-orchestrations.md

---

src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/DurableTaskEndToEndTests.cs
test/TestOrchestrations.cs

cc @cgillum 
this makes sense to me - thoughts?

Fix infinite WaitForExternalEvent firing (#141)

---

src/WebJobs.Extensions.DurableTask/Bindings/ObjectValueProvider.cs

Fix for: https://github.com/Azure/azure-functions-durable-extension/issues/137

When parameter is null, convert to empty string.

---

samples/precompiled/Monitor.cs
samples/precompiled/local.settings.json

Issue #118. Carried over from PR #145, implements requested changes from @tohling I missed before merge - extended setup guidance in comments and logging.

Replace Counter sample with Monitor sample. #118

---

.gitignore
README.md
samples/VSSample.Tests/VSSample.Tests.csproj
samples/csx/E3_Monitor/run.csx
samples/csx/E3_SendGoodWeatherAlert/run.csx
samples/precompiled/HttpSyncStart.cs
samples/precompiled/Monitor.cs
samples/precompiled/VSSample.csproj
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/WebJobs.Extensions.DurableTask.Tests.csproj

Final (hopefully) set of changes for the beta3 release.

Package updates for beta3 plus minor updates to README & samples

---

samples/VSSample.Tests/HelloSequenceActivityTests.cs
samples/VSSample.Tests/HelloSequenceOrchestratorTests.cs
samples/VSSample.Tests/HttpStartTests.cs
samples/VSSample.Tests/HttpSyncStartTests.cs
samples/precompiled/HttpStart.cs

May I ask you to review this pull request with small changes to the samples project for better references in the documentation?
Thank you!

Reorganizing sample project for better documentation use

---

samples/VSSample.Tests/HttpStartTests.cs
samples/VSSample.Tests/HttpSyncStartTests.cs
samples/VSSample.Tests/VSSample.Tests.csproj

Please review this pull request for removing fluent assertions from sample project's unit tests as we agreed in the documentation pull request - https://github.com/MicrosoftDocs/azure-docs-pr/pull/34178#pullrequestreview-102859210
Thank you!

Removing fluent assertions from sample unit tests.

---

README.md

Updated README to include monitor sample link.

Monitor sample in README

---

src/WebJobs.Extensions.DurableTask/Bindings/OrchestrationTriggerAttributeBindingProvider.cs
src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs

May I ask you when you have time to review this pull request that implements changes defined in [#208](https://github.com/Azure/azure-functions-durable-extension/issues/208)?
Thank you!

Improve exception message for multi-threaded access

---

src/WebJobs.Extensions.DurableTask/Bindings/OrchestrationTriggerAttributeBindingProvider.cs
src/WebJobs.Extensions.DurableTask/DurableOrchestrationClient.cs
src/WebJobs.Extensions.DurableTask/DurableOrchestrationClientBase.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml

May I ask you when you have time to review the following pull request for implementing issue [#224](https://github.com/Azure/azure-functions-durable-extension/issues/224) ?
Thank you!

Exposing Task Hub Name in DurableOrchestrationClientBase

---

src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
test/DurableTaskEndToEndTests.cs
test/TestOrchestrations.cs

May I ask you to check the approach I am taking for implementing this issue - [#207](https://github.com/Azure/azure-functions-durable-extension/issues/207) ?
I added the test you implemented in **origin/multi-external-event** branch.
Let me know if I need to change that. 
Thank you!

Support for executing external events with the same name in parallel 

---

src/WebJobs.Extensions.DurableTask/MessagePayloadDataConverter.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/DurableTaskEndToEndTests.cs
test/DurableTaskLifeCycleNotificationTest.cs
test/TestActivities.cs
test/TestOrchestrations.cs
test/WebJobs.Extensions.DurableTask.Tests.csproj

1. Removed guard max message payload size.
2. Updated tests for large message payloads.

Enabling large message support.

---

src/WebJobs.Extensions.DurableTask/LifeCycleNotificationHelper.cs
test/DurableTaskLifeCycleNotificationTest.cs

Hi @cgillum ,
This is the fix which you requested. Please have a look. 
https://github.com/Azure/azure-functions-durable-extension/issues/253
I also test this to deploy EventGrid Trigger, and confirm it works fine. 
```
2018-04-16T11:35:23  Welcome, you are now connected to log-streaming service.
2018-04-16T11:35:33.610 [Information] Executing 'Functions.EventGridTriggerCSharp1' (Reason='EventGrid trigger fired at 2018-04-16T11:35:33.5504257+00:00', Id=937a6058-9364-46d6-a1f2-e6e2c8ccc855)
2018-04-16T11:35:33.823 [Information] {
"hubName": "DurableFunctionsHub",
"functionName": "Sample",
"instanceId": "28fce2b524934db1a8ec8c8bc0b0cdef",
"reason": "",
"eventType": 0
}
2018-04-16T11:35:33.840 [Information] Executed 'Functions.EventGridTriggerCSharp1' (Succeeded, …
```

fix: Event Grid data payload should use lowercase letters.

---

src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
src/WebJobs.Extensions.DurableTask/StatusResponsePayload.cs
test/DurableTaskEndToEndTests.cs
test/TestOrchestrations.cs

May I ask you to review the changes in this pull request addressing [#271](https://github.com/Azure/azure-functions-durable-extension/issues/271)?
Thank you!

Adding custom status to HTTP response

---

samples/webjobssdk/chaining/App.config
samples/webjobssdk/chaining/DFWebJobsSample.csproj
samples/webjobssdk/chaining/Functions.cs
samples/webjobssdk/chaining/Program.cs
samples/webjobssdk/chaining/Properties/AssemblyInfo.cs

@cgillum The only change so far was to put functions in *Functions.cs*. LMK if you prefer to keep them in *Program.cs*.  I still have to add snippet indicators and App Insights logging provider.

WebJobs SDK sample

---

src/WebJobs.Extensions.DurableTask/DurableOrchestrationClient.cs
src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
src/WebJobs.Extensions.DurableTask/EndToEndTraceHelper.cs
src/WebJobs.Extensions.DurableTask/EtwEventSource.cs
src/WebJobs.Extensions.DurableTask/LifeCycleNotificationHelper.cs
src/WebJobs.Extensions.DurableTask/Listener/TaskActivityShim.cs
src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
test/TestHelpers.cs

May I ask you to review this pull request for [#282](https://github.com/Azure/azure-functions-durable-extension/issues/282)?
Thank you!

Remove from traces version and appname and slotname when null

---

samples/javascript/E1_HelloSequence/function.json
samples/javascript/E1_HelloSequence/index.js
samples/javascript/E1_SayHello/function.json
samples/javascript/E1_SayHello/index.js
samples/javascript/E2_BackupSiteContent/function.json
samples/javascript/E2_BackupSiteContent/index.js
samples/javascript/E2_CopyFileToBlob/function.json
samples/javascript/E2_CopyFileToBlob/index.js
samples/javascript/E2_GetFileList/function.json
samples/javascript/E2_GetFileList/index.js
samples/javascript/HttpStart/function.json
samples/javascript/HttpStart/run.csx
samples/javascript/host.json
samples/javascript/local.settings.json
samples/javascript/package-lock.json
samples/javascript/package.json

Includes HelloSequence and BackupSiteContent samples.

JavaScript samples, 2 of 4.

---

src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
test/DurableTaskEndToEndTests.cs
test/TestOrchestrations.cs

See #275 for the issue description. 
I believe this is a safe fix which will resolve the issue and not create any noticeable behavior changes for other mainstream scenarios.

Change WaitForExternalEventAsync to use Stack instead of Queue

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Update to DurableTask.AzureStorage v1.2.2

---

test/WebJobs.Extensions.DurableTask.Tests.csproj

Updating the reference in the test project to the same version used in the function project: DurableTask.AzureStorage to v1.2.2

Update test project to DurableTask.AzureStorage to v1.2.2

---

src/WebJobs.Extensions.DurableTask/LifeCycleNotificationHelper.cs
test/DurableTaskLifeCycleNotificationTest.cs
test/TestHelpers.cs

Hello.
I made a pull request of what this issue.
#331 
Please check when you have time.

EventGridTopicEndpoint in ApplicationSettings

---

samples/csx/local.settings.json
samples/fsharp/local.settings.json
samples/javascript/local.settings.json
samples/precompiled/local.settings.json

A small change intended to clarify to users Twilio's accepted phone number format.

Updated TwilioPhoneNumber app setting placeholder with E.164 format

---

src/WebJobs.Extensions.DurableTask/DurableOrchestrationClient.cs
src/WebJobs.Extensions.DurableTask/DurableOrchestrationClientBase.cs
src/WebJobs.Extensions.DurableTask/DurableOrchestrationStatus.cs
src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
src/WebJobs.Extensions.DurableTask/HttpManagementPayload.cs
src/WebJobs.Extensions.DurableTask/LifeCycleNotificationHelper.cs
src/WebJobs.Extensions.DurableTask/Listener/TaskActivityShim.cs
src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
src/WebJobs.Extensions.DurableTask/MessagePayloadDataConverter.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/TestActivities.cs
test/WebJobs.Extensions.DurableTask.Tests.csproj

This PR:
* Bumps up our package version to **1.5.0** (for the new release)
* Fixes an exception serialization regression caused by our recent move to Newtonsoft.Json when targeting netstandard2.0.
* Fixes a variety of StyleCop warnings and documentation issues that were introduced by other contributors

Update to v1.5.0 and additional fixes

---

samples/javascript/E3_GetIsClear/function.json
samples/javascript/E3_GetIsClear/index.js
samples/javascript/E3_Monitor/function.json
samples/javascript/E3_Monitor/index.js
samples/javascript/E3_SendGoodWeatherAlert/function.json
samples/javascript/E3_SendGoodWeatherAlert/index.js
samples/javascript/E4_SendSmsChallenge/function.json
samples/javascript/E4_SendSmsChallenge/index.js
samples/javascript/E4_SmsPhoneVerification/function.json
samples/javascript/E4_SmsPhoneVerification/index.js
samples/javascript/extensions.csproj
samples/javascript/local.settings.json
samples/javascript/package-lock.json
samples/javascript/package.json

clarified required TwilioPhoneNumber app setting format. Monitor sample
requires a build of Microsoft.Azure.WebJobs.Extensions.DurableTask that
includes change c29c0e8bfd97b5ea68689a7ef6de1ff14fe1a25b to work.
Step one of #329 .

Added Monitor and Human Interaction pattern samples in JavaScript,

---

samples/VSSample.Tests/VSSample.Tests.csproj
samples/csx/E2_CopyFileToBlob/run.csx
samples/csx/host.json
samples/csx/local.settings.json
samples/fsharp/BackupSiteContent.fs
samples/fsharp/DurableFSharp.fsproj
samples/fsharp/HttpStart.fs
samples/fsharp/HttpSyncStart.fs
samples/fsharp/Monitor.fs
samples/fsharp/PhoneVerification.fs
samples/fsharp/host.json
samples/fsharp/local.settings.json
samples/javascript/extensions.csproj
samples/javascript/host.json
samples/javascript/local.settings.json
samples/javascript/package-lock.json
samples/precompiled/VSSample.csproj
samples/precompiled/host.json
samples/precompiled/local.settings.json
src/WebJobs.Extensions.DurableTask/ActivityTriggerAttribute.cs
src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
src/WebJobs.Extensions.DurableTask/OrchestrationTriggerAttribute.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj

* Updating the nuget package version to v1.6.2
* Updating the WebJobs SDK references to the GA versions
* Updating all samples

Functions v2 GA Release Updates

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

This PR updates the package metadata to comply with the new package publishing requirements.

Adding missing package metadata

---

src/WebJobs.Extensions.DurableTask/DurableOrchestrationStatus.cs
test/Common/DurableTaskEndToEndTests.cs
test/Common/TestActivities.cs
test/Common/TestOrchestrations.cs

I wanted to open this PR to frame the discussion for #388.
Please review when you have time.
Thank you!

Adding deserialization capabilities for DurableOrchestrationStatus' properties

---

samples/VSSample.Tests/HelloSequenceActivityTests.cs
samples/VSSample.Tests/HelloSequenceOrchestratorTests.cs
samples/VSSample.Tests/HttpStartTests.cs
samples/precompiled/HelloSequence.cs
src/WebJobs.Extensions.DurableTask/Bindings/ActivityTriggerAttributeBindingProvider.cs
src/WebJobs.Extensions.DurableTask/DurableActivityContext.cs
src/WebJobs.Extensions.DurableTask/DurableActivityContextBase.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
test/Common/DurableTaskEndToEndTests.cs
test/Common/TestActivities.cs

I wanted to start the discussion about adding support for `DurableActivityContextBase` as described in https://github.com/Azure/azure-functions-durable-extension/issues/414  with concrete code.
Please let me know if the approach in this PR is good one or we need a change in the course.
Thank you!

Adding support for DurableActivityContextBase

---

src/WebJobs.Extensions.DurableTask/DurableTaskOptions.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
test/Common/DurableTaskEndToEndTests.cs

I wanted to start the discussion how we can improve the `TaskHubName` validation based on https://github.com/Azure/azure-functions-durable-extension/issues/505.
Please let me know if the approach in this PR is acceptable and how it should be improved.
Thank you!

Adding task hub name validation for creating storage resources

---

src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
src/WebJobs.Extensions.DurableTask/DurableOrchestrationContextBase.cs
src/WebJobs.Extensions.DurableTask/GuidManager.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
test/Common/DurableTaskEndToEndTests.cs
test/Common/TestOrchestrations.cs
test/FunctionsV2/GuidManagerTests.cs

May I ask you to review the code in this PR that is addressing the issue for generating deterministic `Guid` from the `DurableOrchestrationContext` as described here https://github.com/Azure/azure-functions-durable-extension/issues/377.
Thank you!

Adding support for deterministic GUID

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Resolves #446 
This is a second attempt at https://github.com/Azure/azure-functions-durable-extension/pull/463, originally by @mlankamp.

Downgrade dependency on Microsoft.Extensions.*

---

src/WebJobs.Extensions.DurableTask/ActivityTriggerAttribute.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
src/WebJobs.Extensions.DurableTask/OrchestrationClientAttribute.cs
src/WebJobs.Extensions.DurableTask/OrchestrationTriggerAttribute.cs
test/Common/ClientFunctions.cs
test/Common/DurableTaskEndToEndTests.cs
test/Common/DurableTaskHostExtensions.cs
test/Common/DurableTaskLifeCycleNotificationTest.cs
test/Common/SimpleNameResolver.cs
test/Common/TestHelpers.cs
test/Common/TestOrchestrations.cs
test/Common/TestOrchestratorClient.cs

* Adds `[AuthResolve]` attributes to additional attribute properties
* Cleans up the test code changes introduced in the task hub client binding PR
* Improves the reliability of the "actor" tests

Additional support for [AutoResolve] attributes, fixing tests

---

src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs

Added out-of-proc orchestration state error field/handling.

---

.github/ISSUE_TEMPLATE/bug_report.md

Added issue template for reporting bugs.

Added bug issue template

---

.github/ISSUE_TEMPLATE/bug_report.md

Corrected terminology in bug report issue template.

---

samples/javascript/HttpStart/function.json

[Article here ](https://docs.microsoft.com/en-us/azure/azure-functions/durable/quickstart-js-vscode)suggests copy-pasting the URL into a browser. To make that work, adding GET in addition to POST. 
For reference; https://github.com/Azure/azure-functions-durable-extension/pull/556

Http Method Fix Round 2

---

src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
test/Common/DurableTaskEndToEndTests.cs
test/Common/TestOrchestratorClient.cs
test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj

This PR adds tests to confirm the fixes for the following issues:
* [Message loss due to race conditions with ContinueAsNew (#67)](#67)
* [Failed to deserialize exception from TaskActivity (#459)](#459)
It also updates the test csproj files to point to more updated versions of some nuget packages.

Test updates to confirm some bug fixes

---

CONTRIBUTING.md
test/Common/DurableTaskLifeCycleNotificationTest.cs
test/Common/HttpApiHandlerTests.cs
test/Common/TestFrameworkTests.cs

- Adds correct attribute to existing tests
- Updates contributer's guide
- Adds meta test to ensure that all tests have correct attribute
Fixes #642

 Ensure all tests are running in CI pipeline 

---

src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs

Hi. I create PR for #670 .
Please check it.

Fix CreateLifeCycleNotificationHelper Error on V1Functions

---

src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationClient.cs
src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
src/WebJobs.Extensions.DurableTask/DurableTaskJobHostConfigurationExtensions.cs
src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
src/WebJobs.Extensions.DurableTask/IOrchestrationServiceFactory.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
src/WebJobs.Extensions.DurableTask/Options/AzureStorageOptions.cs
src/WebJobs.Extensions.DurableTask/Options/CommonStorageProviderOptions.cs
src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs
src/WebJobs.Extensions.DurableTask/Options/EmulatorStorageOptions.cs
src/WebJobs.Extensions.DurableTask/Options/StorageProviderOptions.cs
src/WebJobs.Extensions.DurableTask/OrchestrationClientAttribute.cs
src/WebJobs.Extensions.DurableTask/OrchestrationServiceFactory.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/Common/BindingTests.cs
test/Common/DurableOrchestrationClientBaseTests.cs
test/Common/DurableTaskEndToEndTests.cs
test/Common/DurableTaskLifeCycleNotificationTest.cs
test/Common/HttpApiHandlerTests.cs
test/Common/TestFrameworkTests.cs
test/Common/TestHelpers.cs
test/Common/TestOrchestratorClient.cs
test/FunctionsV2/PlatformSpecificHelpers.FunctionsV2.cs
test/FunctionsV2/TestDataGenerator.cs

Proof of concept for #652 with DurableTask.Emulator provider. Will eventually add work for #641 as well. 
Only added tests for the emulator provider to a few tests for now, as I didn't want to effectively double the amount of time it takes for the CI to run.

Support for storage providers other than Azure Storage

---

src/WebJobs.Extensions.DurableTask/EventGridLifeCycleNotificationHelper.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/Common/DurableTaskLifeCycleNotificationTest.cs

This also fixes some StyleCop regressions from previous PRs.
The change appears to be bigger than it really is because it also fixes newline inconsistencies that were introduced in other PRs. Turning off whitespace comparisons should help make it readable.

Add Functions v1 test covereage for basic Event Grid scenario

---

src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationClient.cs

Changed AND checks to short-circuit; currently, if state is null, the next conditional check will be evaluated and throw a null reference exception.

ReadActorState bugfix

---

src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableCommonContext.cs
src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationContext.cs
src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
src/WebJobs.Extensions.DurableTask/Listener/TaskActorShim.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
src/WebJobs.Extensions.DurableTask/OrchestrationRuntimeStatus.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/Common/BindingTests.cs
test/Common/DurableTaskEndToEndTests.cs
test/Common/DurableTaskLifeCycleNotificationTest.cs
test/Common/TestOrchestrations.cs
test/Common/TestOrchestratorClient.cs
test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj

Merge v1.8.1 changes into v2 branch

---

src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableCommonContext.cs
src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationClient.cs
src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDeterministicExecutionContext.cs
src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableEntityContext.cs
src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationClient.cs
src/WebJobs.Extensions.DurableTask/ContextInterfaces/IInterleavingContext.cs
src/WebJobs.Extensions.DurableTask/EntityScheduler/EntityCurrentOperationStatus.cs
src/WebJobs.Extensions.DurableTask/EntityScheduler/RequestMessage.cs
src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
test/Common/TestActors.cs

As discussed, *input* is a better name than *content* (#725).

Rename operation content to input

---

samples/v2/Chirper/Chirper.Service/Chirper.Service.csproj
samples/v2/Chirper/Chirper.Service/Entities/UserChirps.cs
samples/v2/Chirper/Chirper.Service/Entities/UserFollows.cs
samples/v2/Chirper/Chirper.Service/Orchestrations/GetTimeline.cs
samples/v2/Chirper/Chirper.Service/PublicRest/Chirp.cs
samples/v2/Chirper/Chirper.Service/PublicRest/HttpSurface.cs
samples/v2/Chirper/Chirper.Service/host.json
samples/v2/Chirper/Chirper.Service/local.settings.json
samples/v2/Chirper/Chirper.Service/readme.md
samples/v2/Chirper/Chirper.sln

This sample demonstrates how to create a simple, stateful, serverless REST service using 
Azure Functions and Durable Functions. 
The users of this service can: 
1. post messages (called "chirps") to their account, or delete them
2. follow or unfollow other users
3. view a timeline containing all chirps of the people they are following, sorted by timestamp
This sample is meant to highlight support for stateful entities (a new feature in 2.0), and how they 
can be used in conjunction with Durable Orchestrations.

New Chirper sample

---

src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
test/Common/DurableTaskEndToEndTests.cs
test/Common/TestOrchestrations.cs

Throw clear exception for invalid timeout in WaitForExternalEvent

---

src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationClient.cs
src/WebJobs.Extensions.DurableTask/ContextInterfaces/DurableContextExtensions.cs
src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationClient.cs
src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
src/WebJobs.Extensions.DurableTask/OrchestrationServiceFactory.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/Common/DurableOrchestrationClientBaseTests.cs
test/Common/DurableOrchestrationClientMock.cs
test/Common/HttpApiHandlerTests.cs
test/Common/TestHelpers.cs
test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj

Add .NET Core friendly HTTP types to IDurableOrchestrationClient

---

src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Refactor HTTP routing logic

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj

Update WebJobs version for V1 Function apps

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Revert #771 until #796 is fixed.

Revert Microsoft.Azure.Webjobs to version 2.2.0

---

samples/v2/entitites-csharp/Chirper/Chirper.Service/Entities/IUserChirps.cs
samples/v2/entitites-csharp/Chirper/Chirper.Service/Entities/IUserFollows.cs
samples/v2/entitites-csharp/Chirper/Chirper.Service/Entities/UserChirps.cs
samples/v2/entitites-csharp/Chirper/Chirper.Service/Entities/UserFollows.cs
samples/v2/entitites-csharp/Chirper/Chirper.Service/Orchestrations/GetTimeline.cs
samples/v2/entitites-csharp/Chirper/Chirper.Service/PublicRest/HttpSurface.cs
samples/v2/entitites-csharp/RideSharing/RideSharing/Entities/IRegionEntity.cs
samples/v2/entitites-csharp/RideSharing/RideSharing/Entities/IUserEntity.cs
samples/v2/entitites-csharp/RideSharing/RideSharing/Entities/RegionEntity.cs
samples/v2/entitites-csharp/RideSharing/RideSharing/Entities/UserEntity.cs
samples/v2/entitites-csharp/RideSharing/RideSharing/Orchestrations/AdvertiseAvailabilityAndStartSearch.cs
samples/v2/entitites-csharp/RideSharing/RideSharing/PublicRest/HttpSurface.cs
src/WebJobs.Extensions.DurableTask/EntityScheduler/Proxy/DurableEntityProxyExtensions.cs
src/WebJobs.Extensions.DurableTask/EntityScheduler/Proxy/EntityContextProxy.cs
src/WebJobs.Extensions.DurableTask/EntityScheduler/Proxy/EntityProxy.cs
src/WebJobs.Extensions.DurableTask/EntityScheduler/Proxy/EntityProxyFactory.cs
src/WebJobs.Extensions.DurableTask/EntityScheduler/Proxy/IEntityProxyContext.cs
src/WebJobs.Extensions.DurableTask/EntityScheduler/Proxy/OrchestrationClientProxy.cs
src/WebJobs.Extensions.DurableTask/EntityScheduler/Proxy/OrchestrationContextProxy.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
test/Common/DurableTaskEndToEndTests.cs
test/Common/TestEntityClasses.cs
test/Common/TestOrchestrations.cs

Adding initial EntityProxy implement.

---

src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableEntityContext.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml

Changed generic parameter names for IDurableEntityContext

---

src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
src/WebJobs.Extensions.DurableTask/DurableTaskOptions.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/Common/DurableTaskEndToEndTests.cs
test/Common/TestHelpers.cs
test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj

Fixes https://github.com/Azure/azure-functions-durable-extension/issues/693
Fixes https://github.com/Azure/azure-functions-durable-extension/issues/665

Add automatic fetching of large messages to Durable 1.0

---

samples/javascript/extensions.csproj
samples/javascript/package-lock.json
samples/javascript/package.json
src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
src/WebJobs.Extensions.DurableTask/DurableTaskOptions.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/Common/DurableTaskEndToEndTests.cs
test/Common/TestHelpers.cs
test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj

Merges latest from **dev** into **master** in preparation for the v1.8.3 release.

Durable Functions v1.8.3 release payload

---

samples/v1/VSSample.Tests/VSSample.Tests.csproj
samples/v1/fsharp/DurableFSharp.fsproj
samples/v1/javascript/extensions.csproj
samples/v1/precompiled/VSSample.csproj
samples/v1/webjobssdk/chaining/DFWebJobsSample.csproj
samples/v2/VSSample.Tests/VSSample.Tests.csproj
samples/v2/entitites-csharp/Chirper/Chirper.Service/Chirper.Service.csproj
samples/v2/entitites-csharp/RideSharing/RideSharing/RideSharing.csproj
samples/v2/fsharp/DurableFSharp.fsproj
samples/v2/javascript/extensions.csproj
samples/v2/precompiled/Counter.cs
samples/v2/precompiled/VSSample.csproj
samples/v2/redis/Redis.csproj
src/WebJobs.Extensions.DurableTask/EntityScheduler/TypedInvocationExtensions.cs
src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/Common/DurableTaskEndToEndTests.cs

- Updated package versions
- Added `Counter` sample for precompiled v2
- Minor fixes for entity HTTP handling

Updates for v2-beta1 release

---

azure-pipelines.yml

Adding YAML file for Azure Pipelines

Azure pipelines v2

---

src/WebJobs.Extensions.DurableTask/EntityScheduler/Proxy/DurableEntityProxyExtensions.cs
src/WebJobs.Extensions.DurableTask/EntityScheduler/Proxy/EntityProxy.cs
src/WebJobs.Extensions.DurableTask/EntityScheduler/Proxy/EntityProxyFactory.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml

Hi @cgillum 
Added validation of interface used as Entity Proxy.
There was a problem that the error message was difficult to understand, so adding the problematic method and interface name made it easy to identify the cause.
Ref #859

Adding validation for entity proxy interface

---

src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationClient.cs
test/Common/DurableOrchestrationClientBaseTests.cs

Added more validation for instanceId in StartNewAsync

---

src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml

This PR is related to https://github.com/Azure/azure-functions-durable-extension/pull/875 but targeting  [v2 branch](https://github.com/Azure/azure-functions-durable-extension/tree/v2)
Please let me know what should be fixed next.
Thank you!

Adding support for Python worker JSON parsing.

---

test/Common/DurableOrchestrationClientBaseTests.cs

I updated the test written with this PR: #841

DurableOrchestrationClientBaseTests Test update

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/new-release-template.md
samples/v1/javascript/package-lock.json
samples/v1/javascript/package.json
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/Common/DurableTaskEndToEndTests.cs
test/Common/TestOrchestrations.cs

Merges `dev` branch into `v2` branch for the first time since the beta1 release. 
Incorporates all of the commits that are not irrelevant for 2.0 or haven't already been cherry-picked except for edff2fc, which will be revisited separately by issue #906.

Merge dev into v2

---

samples/v2/VSSample.Tests/VSSample.Tests.csproj
samples/v2/entitites-csharp/Chirper/Chirper.Service/Chirper.Service.csproj
samples/v2/entitites-csharp/RideSharing/RideSharing/RideSharing.csproj
samples/v2/fsharp/DurableFSharp.fsproj
samples/v2/precompiled/VSSample.csproj
samples/v2/redis/Redis.csproj
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Preparing for beta2 release.
Addresses version incrementing of extension and the references in the sample for #909.

Increment nuget package version v2.0.0-beta2

---

samples/v2/entitites-csharp/Chirper/Chirper.Service/PublicRest/HttpSurface.cs
samples/v2/entitites-csharp/RideSharing/RideSharing/PublicRest/HttpSurface.cs

Entity samples were not updated to reflect breaking changes.

Fix Durable Entities samples to reflect breaking API changes

---

samples/v2/fsharp/BackupSiteContent.fs
samples/v2/fsharp/DurableFSharp.fsproj
samples/v2/fsharp/HelloSequence.fs
samples/v2/fsharp/HttpStart.fs
samples/v2/fsharp/HttpSyncStart.fs
samples/v2/fsharp/Monitor.fs
samples/v2/fsharp/PhoneVerification.fs
samples/v2/javascript/extensions.csproj
samples/v2/javascript/package-lock.json
samples/v2/javascript/package.json

Neither the F# and JS samples were working with our V2 releases, so I made the appropriate code/config changes.

Fix Javascript and F# samples for Durable 2.0

---

src/WebJobs.Extensions.DurableTask/DeterministicAttribute.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net471.xml
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Added the Deterministic Attribute for use with the Durable Functions Roslyn Analyzer.

Added Deterministic Attribute

---

src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs
test/Common/DurableTaskLifeCycleNotificationTest.cs
test/Common/TestHelpers.cs
test/FunctionsV1/PlatformSpecificHelpers.FunctionsV1.cs
test/FunctionsV2/PlatformSpecificHelpers.FunctionsV2.cs

Use Dependency Injection to resolve Lifecycle Notification Helper (only Function v2)
Ref #775

Resolve custom lifecycle helper using Dependency Injection

---

src/WebJobs.Extensions.DurableTask/DurableHttpRequest.cs
src/WebJobs.Extensions.DurableTask/ITokenSource.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net471.xml
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-netstandard2.0.xml
src/WebJobs.Extensions.DurableTask/Options/HttpOptions.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/FunctionsV2/OutOfProcTests.cs

Resolves https://github.com/Azure/azure-functions-durable-extension/issues/912.
Most of the work is the custom serialization logic to support the proposed out-of-proc schema.
I also included some other small changes to Durable HTTP that I wanted to sneak in before GA.

Durable HTTP Managed Identities for out-of-proc

---

src/WebJobs.Extensions.DurableTask/Bindings/BindingHelper.cs
src/WebJobs.Extensions.DurableTask/Bindings/EntityTriggerAttributeBindingProvider.cs
src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
src/WebJobs.Extensions.DurableTask/Listener/OutOfProcOrchestrationShim.cs
src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net471.xml
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-netstandard2.0.xml

Necessary tweaks to make entities work in out of proc languages, like Durable JS.

Additional modifications required for durable entities out of process

---

src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
src/WebJobs.Extensions.DurableTask/ContextInterfaces/DurableContextExtensions.cs
src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationClient.cs
src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net471.xml
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-netstandard2.0.xml
test/Common/DurableTaskEndToEndTests.cs
test/Common/HttpApiHandlerTests.cs

Added configuration to CreateCheckStatusResponse for the http response code when an orchestrator failed

---

src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationClient.cs
src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
test/Common/TestDurableClient.cs

Removed rewind uri from Http status payload

---

src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
src/WebJobs.Extensions.DurableTask/HttpManagementPayload.cs

Fixed namespace for HttpManagementPayload

---

src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProviderFactory.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net471.xml
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-netstandard2.0.xml
src/WebJobs.Extensions.DurableTask/Options/AzureStorageOptions.cs

Make ControlQueueBufferThreshold configurable for Azure Storage

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj

- Updates **Microsoft.Azure.WebJobs.Extensions.DurableTask** to **v2.0.0** (no more beta)
- Updates **Microsoft.Azure.DurableTask.AzureStorage** dependency to **v1.6.5**
Resolves #975

Update nuget package versions

---

src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProviderFactory.cs
src/WebJobs.Extensions.DurableTask/Bindings/ActivityTriggerAttributeBindingProvider.cs
src/WebJobs.Extensions.DurableTask/Bindings/EntityTriggerAttributeBindingProvider.cs
src/WebJobs.Extensions.DurableTask/Bindings/OrchestrationTriggerAttributeBindingProvider.cs
src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
src/WebJobs.Extensions.DurableTask/Listener/DurableTaskListener.cs
src/WebJobs.Extensions.DurableTask/Listener/DurableTaskScaleMonitor.cs
src/WebJobs.Extensions.DurableTask/Listener/DurableTaskTriggerMetrics.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/FunctionsV2/DurableTaskListenerTests.cs
test/FunctionsV2/DurableTaskScaleMonitorTests.cs
test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj

Resolves https://github.com/Azure/azure-functions-host/issues/4957
This is a mostly-done PR. I'm in the process of adding unit tests. Creating this PR early to speed up the feedback process.

Runtime scale implementation for Durable extension

---

src/WebJobs.Extensions.DurableTask.Analyzers/WebJobs.Extensions.DurableTask.Analyzers.csproj

Updated the version of the durable functions analyzer to 0.1.2

Analyzer: updated version

---

src/WebJobs.Extensions.DurableTask.Analyzers/ActivityFunctionCall.cs
src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs
src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionReturnTypeAnalyzer.cs
src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Binding/ClientAnalyzer.cs
src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Binding/EntityContextAnalyzer.cs
src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Binding/OrchestratorContextAnalyzer.cs
src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Entity/ClassNameAnalyzer.cs
src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Entity/DispatchClassNameAnalyzer.cs
src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Entity/StaticFunctionAnalyzer.cs
src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs
src/WebJobs.Extensions.DurableTask.Analyzers/WebJobs.Extensions.DurableTask.Analyzers.csproj

Fixed FunctionAnalyzer from throwing a NullReferenceException.
This PR also refactors some of the code in FunctionAnalyzer and some of the classes that use similar methods.
resolves #999

Analyzer: Fixed NullReferenceException in FuncitonAnalyzer

---

NuGet.Config
src/WebJobs.Extensions.DurableTask/Bindings/ActivityTriggerAttributeBindingProvider.cs
test/Common/DurableTaskEndToEndTests.cs
test/Common/TestActivities.cs

Allows activity functions to be manually triggered in Azure Portal

---

samples/csx/E3_Monitor/run.csx
samples/javascript/E3_Monitor/index.js

Fixes https://github.com/MicrosoftDocs/azure-docs/issues/13111

Simplify replay logger logic in monitor example

---

samples/entitites-csharp/Chirper/Chirper.Service/PublicRest/HttpSurface.cs

Fix bug in chirper sample

---

src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs

- Functions V3 now sets AllowSynchronousIO = false
- JsonSerializer.Deserialize<T> calls Read on stream (throws exception)
Fixes #1039

Update HttpApiHandler to work with AllowSynchronousIO = false

---

src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProvider.cs
src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableEntityClient.cs
src/WebJobs.Extensions.DurableTask/DurableEntityStatus.cs
src/WebJobs.Extensions.DurableTask/EntityQuery.cs
src/WebJobs.Extensions.DurableTask/EntityQueryResult.cs
src/WebJobs.Extensions.DurableTask/EntityScheduler/EntityId.cs
src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net471.xml
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
src/WebJobs.Extensions.DurableTask/OrchestrationStatusQueryCondition.cs
test/Common/DurableTaskEndToEndTests.cs
test/Common/HttpApiHandlerTests.cs
test/Common/TestDataGenerator.cs
test/Common/TestOrchestrations.cs

Added ListEntitiesAsync Api

---

src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs

Optional setting to attempt to address #1112

Add preview host.json setting for graceful shutdowns

---

samples/VSSample.Tests/VSSample.Tests.csproj
samples/csx/README.md
samples/csx/extensions.csproj
samples/entitites-csharp/Chirper/Chirper.Service/Chirper.Service.csproj
samples/entitites-csharp/RideSharing/RideSharing/RideSharing.csproj
samples/fsharp/DurableFSharp.fsproj
samples/fsharp/README.md
samples/javascript/README.md
samples/javascript/extensions.csproj
samples/precompiled/VSSample.csproj
src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProvider.cs
src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
src/WebJobs.Extensions.DurableTask/DurableEntityStatus.cs
src/WebJobs.Extensions.DurableTask/EntityQuery.cs
src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net471.xml
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
src/WebJobs.Extensions.DurableTask/OrchestrationStatusQueryCondition.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/Common/DurableTaskEndToEndTests.cs
test/Common/HttpApiHandlerTests.cs

- Resolves https://github.com/Azure/azure-functions-durable-extension/issues/1117
- Updated samples to point to v2.1.0

Last minute updates for v2.1.0 release

---

src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs

Fixed NullReferenceException when deserializing a request body using the start orchestration HTTP API

---

src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
src/WebJobs.Extensions.DurableTask/Listener/TaskActivityShim.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj

- Improves stability when running on Consumption plan
- Also updates DTFx dependency

Abort activity function execution on unexpected exceptions (#1139)

---

src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProvider.cs
src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationClient.cs
src/WebJobs.Extensions.DurableTask/DurabilityProvider.cs
src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
test/Common/HttpApiHandlerTests.cs
test/Common/TestDurableClient.cs

resolves #1147 
resolves #1116

Deprecated non-paged GetStatusAsync APIs

---

src/WebJobs.Extensions.DurableTask/Bindings/BindingHelper.cs
src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
src/WebJobs.Extensions.DurableTask/DurableTaskJobHostConfigurationExtensions.cs
src/WebJobs.Extensions.DurableTask/DurableTaskOptions.cs
src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
src/WebJobs.Extensions.DurableTask/IApplicationLifetimeWrapper.cs
src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-netstandard2.0.xml
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/Common/BindingTests.cs
test/Common/ClientFunctions.cs
test/Common/DurableTaskEndToEndTests.cs
test/Common/DurableTaskHostExtensions.cs
test/Common/DurableTaskLifeCycleNotificationTest.cs
test/Common/HttpApiHandlerTests.cs
test/Common/ITestHost.cs
test/Common/TestHelpers.cs
test/Common/TestHostShutdownNotificationService.cs
test/FunctionsV1/PlatformSpecificHelpers.FunctionsV1.cs
test/FunctionsV2/OutOfProcTests.cs
test/FunctionsV2/PlatformSpecificHelpers.FunctionsV2.cs

For non-C#, we use a Kestrel server to listen for HTTP management requests on http://127.0.0.1:17071

Local HTTP server for out-of-proc (#1166)

---

src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
test/Common/DurableTaskEndToEndTests.cs

Fixed orchestration status error message

---

src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs

Same PR as https://github.com/Azure/azure-functions-durable-extension/pull/1201, but targeting the v1 branch.

Fixed null-ref exception in local HTTP listener (V1)

---

src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationClient.cs

Resolves https://github.com/Azure/azure-functions-durable-extension/issues/1193

Updated documentation for TerminateAsync

---

src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs

Update SignalEntity to call entity from other function app

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Changed WebApiCompatShim version

---

src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableActivityContext.cs
src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
src/WebJobs.Extensions.DurableTask/DurableHttpRequest.cs
src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
src/WebJobs.Extensions.DurableTask/EntityScheduler/RequestMessage.cs
src/WebJobs.Extensions.DurableTask/EntityScheduler/ResponseMessage.cs
src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
src/WebJobs.Extensions.DurableTask/Listener/TaskActivityShim.cs
src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs
src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
src/WebJobs.Extensions.DurableTask/MessagePayloadDataConverter.cs
src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/Common/DurableHttpTests.cs
test/Common/DurableTaskEndToEndTests.cs
test/Common/TestActivities.cs
test/Common/TestOrchestrations.cs
test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj

related to https://github.com/Azure/durabletask/pull/376
resolves #1155

Set custom DataConverter for OrchestrationContext in TaskOrchestrationShim

---

src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs
src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Binding/OrchestratorContextAnalyzer.cs
src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Entity/ClassNameAnalyzer.cs
src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Entity/DispatchEntityNameAnalyzer.cs
src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Entity/StaticFunctionAnalyzer.cs
src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/EntityInterface/InterfaceAnalyzer.cs
src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Orchestrator/OrchestratorAnalyzer.cs
src/WebJobs.Extensions.DurableTask.Analyzers/CodefixProviders/Entity/DispatchEntityNameCodeFixProvider.cs
src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs
test/WebJobs.Extensions.DurableTask.Analyzers.Test/ActivityFunction/NameAnalyzerTests.cs

Fix #1287 
Analyzer looks for function name as const.

Analyzer - Read Function name from `const`.

---

src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs
src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj

resolves #1269
I'm unsure at this point if these are the only places that I'd need to pass this to the durable task framework.

Added use of custom error serializer in DTFx.

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Updated analyzer reference to 0.2.1

Updated analyzer reference

---

src/WebJobs.Extensions.DurableTask/Listener/OutOfProcOrchestrationShim.cs
src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs

Accidentally merged a previous PR without addressing all of the
feedback. This PR finishes addressing that feedback.

Add more comments for OutOfProc exception handling

---

src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs
test/Common/DurableTaskEndToEndTests.cs

Allow for dynamic port usage for local RPC in use

---

src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs

Port PR #1360 for Durable 1.x so extension bundles v1 can get the fix.

Make worker ids unique for App Service VMSS Environment

---

src/WebJobs.Extensions.DurableTask/DurableHttpClientFactory.cs
test/DFPerfScenarios/Common.cs
test/DFPerfScenarios/DFPerfScenarios.csproj
test/DFPerfScenarios/DFPerfScenarios.sln
test/DFPerfScenarios/Tests/ManySequencesTest.cs
test/DFPerfScenarios/host.json
test/DFPerfScenarios/local.settings.json

This PR adds the performance testing project that we use for validating extension releases.

Add DFPerfScenarios test project

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Increase package version for 2.3.1 release

---

src/WebJobs.Extensions.DurableTask/LinuxAppServiceLogger.cs
test/Common/DurableTaskEndToEndTests.cs

Promoting dev to master for 2.3.1 release, now with fixed CI test and extra logging fields

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Updated Analyzer dependency to 0.3.2

Updated Analyzer reference version

---

src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs
src/WebJobs.Extensions.DurableTask.Analyzers/WebJobs.Extensions.DurableTask.Analyzers.csproj
src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
src/WebJobs.Extensions.DurableTask/EndToEndTraceHelper.cs
src/WebJobs.Extensions.DurableTask/EventSourceListener.cs
src/WebJobs.Extensions.DurableTask/LinuxAppServiceFileLogger.cs
src/WebJobs.Extensions.DurableTask/LinuxAppServiceLogger.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
src/WebJobs.Extensions.DurableTask/Options/TraceOptions.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/Common/DurableTaskEndToEndTests.cs
test/Common/TestHelpers.cs

As in title, this is the third promotion of dev to master for the 2.3.1 release. Hopefully the last one as well :)

Promote to master for 2.3.1 release - 3rd instance

---

azure-pipelines.yml

Should fix the issue found here: https://developercommunity.visualstudio.com/content/problem/1257247/working-devops-pipeline-starts-to-fail-with-unrela.html.

Update Nuget installer version in DevOps Pipeline

---

src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
src/WebJobs.Extensions.DurableTask/HttpManagementPayload.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
test/Common/DurableTaskEndToEndTests.cs
test/Common/HttpApiHandlerTests.cs

Changed restartUri to restartPostUri to make it clear that we require http post.

Changed restartUri to restartPostUri

---

samples/correlation-csharp/FunctionAppCorrelation/FunctionAppCorrelation.csproj
samples/correlation-csharp/FunctionAppCorrelation/SimpleCorrelationDemo.cs
samples/correlation-csharp/FunctionAppCorrelation/SimpleOrchestration.cs
samples/correlation-csharp/FunctionAppCorrelation/host.json
samples/correlation-csharp/configuration.md

I did a little manual testing last night and found a few small issues.

Fixes to correlation sample and instructions

---

src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableEntityContext.cs

[PR for context](https://github.com/Azure/azure-docs-sdk-dotnet/pull/1286)
A user contributed the following. Unfortunately the reference content is 1-way, so I need to make the fix here.

Doc update contribution from @donald93

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Routine PR for release 2.4.1: upgrading extension version and dependency on azure storage.

Update versions for release 2.4.1

---

src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net461.xml
test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj

Updated Emulator and Redis versions

Updated Emulator and Redis versions (#1659)

---

src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProviderFactory.cs
src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs

Patch PlatformInfoProvider exception in Functions V1

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Point to hardcoded commit of our LICENSE.md file, so that the license
for this release remains static.

Update nuget license URL to our MIT license

---

pending_docs.md
release_notes.md

Reset release notes and pending docs for next release

---

pending_docs.md
release_notes.md

Merge dev to main

---

src/WebJobs.Extensions.DurableTask/ProviderUtils.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Undo accidental deletion of the ProviderUtils class

---

src/WebJobs.Extensions.DurableTask/ProviderUtils.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Merge dev into main for 2.4.3 release

Merge dev into main

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Updating the version to 2.5.0 as the last step in the 2.4.3 release (#1753).

Update version to 2.5.0

---

test/Common/DurableTaskEndToEndTests.cs
test/Common/TestHelpers.cs

Applying the latest suggestions to the linux telemetry tests in: https://github.com/Azure/azure-functions-durable-extension/pull/1802
resolves N/A

Apply minor improvements to linux telemetry tests

---

release_notes.md
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj

Fixes the following CVE vulnerabilities:
-CVE-2019-0548
-CVE-2021-26701
Resolves #1660

Update transitive dependencies with CVE vulnerabilities

---

pending_docs.md
release_notes.md

Reset release_notes.md for v2.5.0 release

---

src/DurableFunctions.TypedInterfaces/README.md
src/DurableFunctions.TypedInterfaces/SourceGenerator/DurableFunctions.TypedInterfaces.csproj

Fix README and nuget package details in preparation for release of DurableFunctions.TypedInterfaces 0.1.0-preview

Prepare typed interface release

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Increment version post v.2.5.0 release

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Incremented DurableTask.AzureStorage from 1.8.7 to 1.9.0

Incremented versions for 2.5.1 release

---

release_notes.md

Merge dev into main after resetting release notes for v2.5.1 release

Merge dev into main for 2.5.1

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Updating the version to 2.5.2 as the last step in the 2.5.1 release

Increment version to 2.5.2

---

release_notes.md
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Incremented version for 2.6.0 release

Incremented version to 2.6.0

---

README.md

This PR adds a publication section to our README, to give visibility to our research efforts.
After merging this change, I'll make a similar PR for the docs site.
resolves N/A

Add publications section to README

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Incrementing version post v2.6.0 release.

Increment version post v2.6.0 release

---

samples/javascript/E3_Monitor/index.js
samples/javascript/E4_SmsPhoneVerification/index.js
samples/javascript/package-lock.json
samples/javascript/package.json

The samples for Monitors (E3) and Human Interaction (E4) use the Moment.js library (<https://github.com/moment/moment/>). According to its project status the library is in maintenance mode and not recommended for new project (see: [GitHub Project Status](https://github.com/moment/moment/#project-status)). In addition it comes with certain drawbacks compared to newer libraries (see <https://momentjs.com/docs/#/-project-status/>).
The project references alternatives for its usage and this pull request contains a proposal to adopt this by switching over to [Luxon](https://moment.github.io/luxon/index.html) . 
There is no open issue

JavaScript Code: Replacement of moment.js with Luxon

---

azure-pipelines.yml

Updating the pipeline to use 1ES hosted VM.

Update pipeline to use 1ES hosted VM

---

azure-pipelines.yml

Temporarily removing pool changes to unblock the Azure pipeline since it's failing with authorization issues related to these changes.

Removing pool changes

---

release_notes.md

Resetting release_notes.md (v2.6.1 release)

Reset release_notes.md

---

src/WebJobs.Extensions.DurableTask/Listener/OutOfProcOrchestrationShim.cs

Previously, in `ProcessAsyncActionsV1` in the `OutOfProcOrchestrationShim`, we didn't have an explicit API for `WhenAny` and `WhenAll` tasks. Instead, we scheduled all tasks wrapped in an `await Task.WhenAny()`, as seen [here](https://github.com/Azure/azure-functions-durable-extension/blob/56348c050a24a3f7f5fd94733b78489b863aff40/src/WebJobs.Extensions.DurableTask/Listener/OutOfProcOrchestrationShim.cs#L243). Since the result of a `Task.WhenAny()` is another `Task`, this also had the nice side effect of wrapping any exceptions thrown by the sheduled `Task`s in a `Task` so that it can be passed to the SDKs, giving user code the ability to try-catch their own exceptions. However, since this approach didn't explicitly schedule an `WhenAll` task when the user asked for one, this led to some …

Allow Internal Code to Throw Exceptions in OOProc Shim

---

.github/ISSUE_TEMPLATE/new-release-template.md
.github/workflows/smoketest-dotnet-isolated-v4.yml
.github/workflows/smoketest-dotnet-v2.yml
.github/workflows/smoketest-dotnet-v3.yml
.github/workflows/smoketest-node14-v4.yml
.github/workflows/smoketest-python37-v2.yml
WebJobs.Extensions.DurableTask.sln
release_notes.md
src/WebJobs.Extensions.DurableTask/Bindings/OrchestrationTriggerAttributeBindingProvider.cs
src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
src/WebJobs.Extensions.DurableTask/DurableTaskJobHostConfigurationExtensions.cs
src/WebJobs.Extensions.DurableTask/HostLifecycleService.cs
src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask-net462.xml
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
src/WebJobs.Extensions.DurableTask/OutOfProcMiddleware.cs
src/WebJobs.Extensions.DurableTask/ProtobufUtils.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
src/WebJobs.Extensions.DurableTask/WebJobsConnectionInfoProvider.cs
src/WebJobs.Extensions.DurableTask/_CSharpLanguageHelpers.cs
test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj
test/SmokeTests/OOProcSmokeTests/DotNetIsolated/Dockerfile
test/SmokeTests/OOProcSmokeTests/durablePy/Dockerfile
test/SmokeTests/OOProcSmokeTests/durablePy/proxies.json
test/SmokeTests/SmokeTestsV2/Dockerfile
test/SmokeTests/SmokeTestsV2/HttpStart.cs
test/SmokeTests/e2e-test.ps1

Routine PR, merging in preparation for release.

Merge dev into main for 2.7.1 release

---

release_notes.md
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Promote dev to main for 2.7.2 release (attempt 2)

---

README.md

This PR makes a few minor improvements and updates to the README, listed below:
1. It lists DF PowerShell as GA
2. It lists DF Java as Public Preview
3. It updates an out of date installation instruction for the Extension
4. It lists the Netherite paper as accepted to VLDB'22

Update content of README

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Incremented Analyzer dependency 0.4.* -> 0.5.*

Incremented Analyzer Dependency

---

src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
src/Worker.Extensions.DurableTask/AssemblyInfo.cs

Set extension version to 2.8.0

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Increase version for 2.8.1 release

---

src/Worker.Extensions.DurableTask/ObjectConverterShim.cs

Fix encoding and deserialization for `ObjectConverterShim`.

Fix ObjectConverterShim encoding and deserialization

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Increase Version to 2.9.1

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Increase version for private release of entity suspension patch

---

release_notes.md
src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
test/Common/DurableTaskEndToEndTests.cs
test/Common/TestEntities.cs
test/Common/TestEntityClasses.cs
test/Common/TestOrchestrations.cs

Fix entity deserialization for class-based entities so it reflects custom serialization settings

---

release_notes.md
src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs
src/Worker.Extensions.DurableTask/FunctionsDurableClientProvider.cs
src/Worker.Extensions.DurableTask/FunctionsOrchestrationContext.cs
src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj

Draft PR to get some eyes on this. Will be filling out the PR description properly soon. I am also aware some stuff is pointing to incorrect versions (1.0.0-rc.2 should be 1.0.0)

Update Durable Functions .NET isolated extension with new changes

---

release_notes.md

Updated release_notes.md and reset the sections.

Update release_notes.md after v2.9.1 release

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Updating Microsoft.Azure.WebJobs.Extensions.DurableTask version from 2.9.1 to 2.9.2

Increment Microsoft.Azure.WebJobs.Extensions.DurableTask version to 2.9.2

---

.github/ISSUE_TEMPLATE/new-release-template.md
.github/pull_request_template.md
README.md
azure-pipelines-release-dotnet-isolated.yml
release_notes.md
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Promote dev to main for 2.9.2 release

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

As in title, part of: https://github.com/Azure/azure-functions-durable-extension/issues/2405

Increase version to 2.9.3

---

.github/ISSUE_TEMPLATE/new-release-template.md
release_notes.md
src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableEntityContext.cs
src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
src/WebJobs.Extensions.DurableTask/EndToEndTraceHelper.cs
src/WebJobs.Extensions.DurableTask/EntityScheduler/EntityTraceFlags.cs
src/WebJobs.Extensions.DurableTask/EntityScheduler/MessageSorter.cs
src/WebJobs.Extensions.DurableTask/EntityScheduler/SchedulerState.cs
src/WebJobs.Extensions.DurableTask/EtwEventSource.cs
src/WebJobs.Extensions.DurableTask/FunctionState.cs
src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs
src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs
src/WebJobs.Extensions.DurableTask/ProtobufUtils.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/Common/TestEntityClasses.cs
test/Common/TestOrchestrations.cs

As in title, routine PR. Related to: https://github.com/Azure/azure-functions-durable-extension/pull/2415

Merge dev to main for 2.9.3 release

---

release_notes.md

Updated release_notes.md and reset the sections.

Update release_notes.md after v2.9.3 release

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Updating Microsoft.Azure.WebJobs.Extensions.DurableTask version from 2.9.3 to 2.9.4

Increment Microsoft.Azure.WebJobs.Extensions.DurableTask version to 2.9.4

---

release_notes.md
src/WebJobs.Extensions.DurableTask/OutOfProcMiddleware.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Prepare release 2.9.5 - Merge dev to main

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

As in title, routine PR for release

Increase version to 2.9.6

---

src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProviderFactory.cs
src/WebJobs.Extensions.DurableTask/Options/AzureStorageOptions.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Add host.json settings for partition manager V3. The default setting is true. 
Partition manager V3 PR: https://github.com/Azure/durabletask/pull/899
Mark this PR as draft cause this will be valid only after table partition manager PR to be merged.

Add host.settings for partition manager V3

---

src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml

Update `src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml` for the new added `useTablePartitioinManagement` setting in host.json

Update DurableTask.xml for the new added partition manager v3 setting

---

azure-pipelines-release.yml
src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProviderFactory.cs
src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
src/WebJobs.Extensions.DurableTask/Options/AzureStorageOptions.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

Release plan for v 2.10.0. Mentioned in issue #2511

Release plan - Merge dev to main

---

test/DFPerfScenarios/Common.cs
test/DFPerfScenarios/DFPerfScenarios.sln
test/DFPerfScenarios/DFPerfScenariosV4.csproj
test/DFPerfScenarios/Tests/Counter.cs
test/DFPerfScenarios/Tests/FanOutFanIn.cs
test/DFPerfScenarios/Tests/ManySequencesTest.cs
test/DFPerfScenarios/Tests/SubOrchestrationFanOutFanIn.cs
test/DFPerfScenarios/host.json
test/DFPerfScenarios/local.settings.json
test/DFPerfScenariosV1/Common.cs
test/DFPerfScenariosV1/DFPerfScenarios.sln
test/DFPerfScenariosV1/DFPerfScenariosV1.csproj
test/DFPerfScenariosV1/Tests/Counter.cs
test/DFPerfScenariosV1/Tests/FanOutFanIn.cs
test/DFPerfScenariosV1/Tests/ManySequencesTest.cs
test/DFPerfScenariosV1/Tests/SubOrchestrationFanOutFanIn.cs
test/DFPerfScenariosV1/host.json
test/DFPerfScenariosV1/local.settings.json

This reverts commit c2afd5dc8ac389bb36d900d3f4e209a22b9864c0. There were build errors by removing the perf tests so reverting the commit for now and will remove the tests in a later PR.

Revert " Remove old perf tests (#2537)"

---

.github/ISSUE_TEMPLATE/new-release-template.md

Updating release template with ADO feed links instead of MyGet links as well as other minor changes.

Update release template

---

.github/ISSUE_TEMPLATE/new-release-template.md
.github/policies/resourceManagement.yml
release_notes.md
src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
src/Worker.Extensions.DurableTask/AssemblyInfo.cs
src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj

Merge dev to main for 2.11.2 release

---

release_notes.md
src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/SmokeTests/OOProcSmokeTests/DotNetIsolated/DotNetIsolated.csproj

Merge dev to main for 2.11.3 release

---

src/WebJobs.Extensions.DurableTask/Bindings/EntityTriggerAttributeBindingProvider.cs
src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
src/WebJobs.Extensions.DurableTask/DurabilityProvider.cs
src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs
src/WebJobs.Extensions.DurableTask/OutOfProcMiddleware.cs
src/WebJobs.Extensions.DurableTask/ProtobufUtils.cs
src/Worker.Extensions.DurableTask/FunctionsDurableTaskClient.cs

Fixes a host of small errors in the newly added code.
Goes into feature branch. Checklist is tracked by feature branch.

Various fixes

---

src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProviderFactory.cs
src/WebJobs.Extensions.DurableTask/ProtobufUtils.cs

propagate changes from https://github.com/Azure/durabletask/pull/957
checklist is tracked by feature branch.

simplify how entities are excluded from instance queries

---

test/SmokeTests/OOProcSmokeTests/DotNetIsolated/Counter.cs

Adds a simple entity example to the DotNetIsolated smoke test.
goes into feature branch. Checklist items are tracked by the feature branch.

add an entity example to the DotNetIsolated smoke test project.

---

src/Worker.Extensions.DurableTask/TaskEntityDispatcher.cs

Small fix required for entities. I had this locally but somehow did not push it with the last PR of fixes.
checklist is tracked by feature branch.

another small fix that got lost somewhere.

---

src/WebJobs.Extensions.DurableTask/Bindings/OrchestrationTriggerAttributeBindingProvider.cs
src/WebJobs.Extensions.DurableTask/ContextImplementations/RemoteOrchestratorContext.cs
src/WebJobs.Extensions.DurableTask/OutOfProcMiddleware.cs
src/WebJobs.Extensions.DurableTask/ProtobufUtils.cs

adds the necessary plumbing to ensure that the `TaskOrchestrationEntityParameters` are passed along to the remote orchestrator. 
checklist is tracked in feature branch.

Fix parameter passing

---

src/Worker.Extensions.DurableTask/TaskEntityDispatcher.cs

Adds API to directly handle entity operations via a `TaskEntityOperation` callback.

Add callback handler for entity dispatching

---

src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs
src/Worker.Extensions.DurableTask/DurableTaskExtensionStartup.cs
src/Worker.Extensions.DurableTask/FunctionsDurableClientProvider.cs

Propagate changes from PRs
https://github.com/Azure/durabletask/pull/985
https://github.com/microsoft/durabletask-dotnet/pull/204
https://github.com/microsoft/durabletask-dotnet/pull/205
checklist is tracked in feature branch.

Core entities/propagate changes

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj

Quick PR to review dependencies for entities-preview.2

Rev dependencies to entities-preview.2

---

azure-pipelines.yml
release_notes.md
src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs
src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/Common/DurableTaskEndToEndTests.cs

Fix bug in how entity queries are translated to the new entity query support in `IEntityOrchestrationService`.
tracked with feature branch.

fix translation of legacy query to new entity query support

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
src/Worker.Extensions.DurableTask/AssemblyInfo.cs
src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj
test/SmokeTests/OOProcSmokeTests/DotNetIsolated/DotNetIsolated.csproj

As in title, in preparation for 2.13.0 release. 
Related: https://github.com/microsoft/durabletask-dotnet/pull/238

Remove preview suffixes

---

src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj

Update worker extension version

---

src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj

Merge dev into main for worker extension v1.1.0 release

---

release_notes.md

Update release notes and rev worker extension to 1.1.1

Update release notes for Worker ext 1.1.1

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj

rev DTFx.Core version for 2.13.2 release

---

.github/workflows/validate-build-analyzer.yml
.github/workflows/validate-build-e2e.yml
.github/workflows/validate-build.yml

As in title, part of 1ES migration. Want the GH actions to run on PRs to dev branch as well

Add dev as trigger branch for gh acitons

---

samples/durable-client-managed-identity/functions-app/README.md

As titled. update the ReadMe to be clearer and also add instructions about the format.

Update External Durable Client ReadMe.md

---

src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
test/SmokeTests/e2e-test.ps1

Rev version and DTFx.dep

---

eng/templates/build.yml

Add net worker steps to 1ES official build

---

tools/triageHelper/function_app.py

As in title, simple updates to the triage helper tool, DrDurable

Remove unused code in DrDurable, add missing PS repo

---

release_notes.md
src/Worker.Extensions.DurableTask/AssemblyInfo.cs
src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj

As in title, preparing for release.

rev worker extension version to 1.1.6, update dependencies and release notes

---

src/Worker.Extensions.DurableTask/Worker.Extensions.DurableTask.csproj

- System.Text.Json from 6.0.0 -> 6.0.10
resolves https://github.com/advisories/GHSA-8g4q-xg66-9fp4

Bump System.Text.Json
